// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/inproxy_broker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InproxyBroker struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MetadataClient           *MetadataClient        `protobuf:"bytes,1,opt,name=metadata_client,json=metadataClient,proto3,oneof" json:"metadata_client,omitempty"`
	MetadataDevice           *MetadataDevice        `protobuf:"bytes,2,opt,name=metadata_device,json=metadataDevice,proto3,oneof" json:"metadata_device,omitempty"`
	MetadataSession          *MetadataSession       `protobuf:"bytes,3,opt,name=metadata_session,json=metadataSession,proto3,oneof" json:"metadata_session,omitempty"`
	MetadataServerEntry      *MetadataServerEntry   `protobuf:"bytes,4,opt,name=metadata_server_entry,json=metadataServerEntry,proto3,oneof" json:"metadata_server_entry,omitempty"`
	MetadataMeek             *MetadataMeek          `protobuf:"bytes,5,opt,name=metadata_meek,json=metadataMeek,proto3,oneof" json:"metadata_meek,omitempty"`
	AppliedTacticsTag        *string                `protobuf:"bytes,100,opt,name=applied_tactics_tag,json=appliedTacticsTag,proto3,oneof" json:"applied_tactics_tag,omitempty"` //LowCardinality
	DialDuration             *int64                 `protobuf:"varint,101,opt,name=dial_duration,json=dialDuration,proto3,oneof" json:"dial_duration,omitempty"`
	DialPortNumber           *int64                 `protobuf:"varint,102,opt,name=dial_port_number,json=dialPortNumber,proto3,oneof" json:"dial_port_number,omitempty"`
	EgressRegion             *string                `protobuf:"bytes,103,opt,name=egress_region,json=egressRegion,proto3,oneof" json:"egress_region,omitempty"` //LowCardinality
	EstablishedTunnelsCount  *int64                 `protobuf:"varint,104,opt,name=established_tunnels_count,json=establishedTunnelsCount,proto3,oneof" json:"established_tunnels_count,omitempty"`
	FrontingProviderId       *string                `protobuf:"bytes,105,opt,name=fronting_provider_id,json=frontingProviderId,proto3,oneof" json:"fronting_provider_id,omitempty"` //LowCardinality
	IsReplay                 *bool                  `protobuf:"varint,106,opt,name=is_replay,json=isReplay,proto3,oneof" json:"is_replay,omitempty"`
	NetworkLatencyMultiplier *float64               `protobuf:"fixed64,113,opt,name=network_latency_multiplier,json=networkLatencyMultiplier,proto3,oneof" json:"network_latency_multiplier,omitempty"`
	NetworkType              *string                `protobuf:"bytes,114,opt,name=network_type,json=networkType,proto3,oneof" json:"network_type,omitempty"`                  //LowCardinality
	RelayProtocol            *string                `protobuf:"bytes,115,opt,name=relay_protocol,json=relayProtocol,proto3,oneof" json:"relay_protocol,omitempty"`            //LowCardinality
	SshClientVersion         *string                `protobuf:"bytes,116,opt,name=ssh_client_version,json=sshClientVersion,proto3,oneof" json:"ssh_client_version,omitempty"` //LowCardinality
	StoredTacticsTag         *string                `protobuf:"bytes,117,opt,name=stored_tactics_tag,json=storedTacticsTag,proto3,oneof" json:"stored_tactics_tag,omitempty"` //LowCardinality
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InproxyBroker) Reset() {
	*x = InproxyBroker{}
	mi := &file_proto_inproxy_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InproxyBroker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InproxyBroker) ProtoMessage() {}

func (x *InproxyBroker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inproxy_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InproxyBroker.ProtoReflect.Descriptor instead.
func (*InproxyBroker) Descriptor() ([]byte, []int) {
	return file_proto_inproxy_broker_proto_rawDescGZIP(), []int{0}
}

func (x *InproxyBroker) GetMetadataClient() *MetadataClient {
	if x != nil {
		return x.MetadataClient
	}
	return nil
}

func (x *InproxyBroker) GetMetadataDevice() *MetadataDevice {
	if x != nil {
		return x.MetadataDevice
	}
	return nil
}

func (x *InproxyBroker) GetMetadataSession() *MetadataSession {
	if x != nil {
		return x.MetadataSession
	}
	return nil
}

func (x *InproxyBroker) GetMetadataServerEntry() *MetadataServerEntry {
	if x != nil {
		return x.MetadataServerEntry
	}
	return nil
}

func (x *InproxyBroker) GetMetadataMeek() *MetadataMeek {
	if x != nil {
		return x.MetadataMeek
	}
	return nil
}

func (x *InproxyBroker) GetAppliedTacticsTag() string {
	if x != nil && x.AppliedTacticsTag != nil {
		return *x.AppliedTacticsTag
	}
	return ""
}

func (x *InproxyBroker) GetDialDuration() int64 {
	if x != nil && x.DialDuration != nil {
		return *x.DialDuration
	}
	return 0
}

func (x *InproxyBroker) GetDialPortNumber() int64 {
	if x != nil && x.DialPortNumber != nil {
		return *x.DialPortNumber
	}
	return 0
}

func (x *InproxyBroker) GetEgressRegion() string {
	if x != nil && x.EgressRegion != nil {
		return *x.EgressRegion
	}
	return ""
}

func (x *InproxyBroker) GetEstablishedTunnelsCount() int64 {
	if x != nil && x.EstablishedTunnelsCount != nil {
		return *x.EstablishedTunnelsCount
	}
	return 0
}

func (x *InproxyBroker) GetFrontingProviderId() string {
	if x != nil && x.FrontingProviderId != nil {
		return *x.FrontingProviderId
	}
	return ""
}

func (x *InproxyBroker) GetIsReplay() bool {
	if x != nil && x.IsReplay != nil {
		return *x.IsReplay
	}
	return false
}

func (x *InproxyBroker) GetNetworkLatencyMultiplier() float64 {
	if x != nil && x.NetworkLatencyMultiplier != nil {
		return *x.NetworkLatencyMultiplier
	}
	return 0
}

func (x *InproxyBroker) GetNetworkType() string {
	if x != nil && x.NetworkType != nil {
		return *x.NetworkType
	}
	return ""
}

func (x *InproxyBroker) GetRelayProtocol() string {
	if x != nil && x.RelayProtocol != nil {
		return *x.RelayProtocol
	}
	return ""
}

func (x *InproxyBroker) GetSshClientVersion() string {
	if x != nil && x.SshClientVersion != nil {
		return *x.SshClientVersion
	}
	return ""
}

func (x *InproxyBroker) GetStoredTacticsTag() string {
	if x != nil && x.StoredTacticsTag != nil {
		return *x.StoredTacticsTag
	}
	return ""
}

var File_proto_inproxy_broker_proto protoreflect.FileDescriptor

const file_proto_inproxy_broker_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/inproxy_broker.proto\x12\bpsiphond\x1a\x14proto/metadata.proto\"\xc3\n" +
	"\n" +
	"\rInproxyBroker\x12F\n" +
	"\x0fmetadata_client\x18\x01 \x01(\v2\x18.psiphond.MetadataClientH\x00R\x0emetadataClient\x88\x01\x01\x12F\n" +
	"\x0fmetadata_device\x18\x02 \x01(\v2\x18.psiphond.MetadataDeviceH\x01R\x0emetadataDevice\x88\x01\x01\x12I\n" +
	"\x10metadata_session\x18\x03 \x01(\v2\x19.psiphond.MetadataSessionH\x02R\x0fmetadataSession\x88\x01\x01\x12V\n" +
	"\x15metadata_server_entry\x18\x04 \x01(\v2\x1d.psiphond.MetadataServerEntryH\x03R\x13metadataServerEntry\x88\x01\x01\x12@\n" +
	"\rmetadata_meek\x18\x05 \x01(\v2\x16.psiphond.MetadataMeekH\x04R\fmetadataMeek\x88\x01\x01\x123\n" +
	"\x13applied_tactics_tag\x18d \x01(\tH\x05R\x11appliedTacticsTag\x88\x01\x01\x12(\n" +
	"\rdial_duration\x18e \x01(\x03H\x06R\fdialDuration\x88\x01\x01\x12-\n" +
	"\x10dial_port_number\x18f \x01(\x03H\aR\x0edialPortNumber\x88\x01\x01\x12(\n" +
	"\regress_region\x18g \x01(\tH\bR\fegressRegion\x88\x01\x01\x12?\n" +
	"\x19established_tunnels_count\x18h \x01(\x03H\tR\x17establishedTunnelsCount\x88\x01\x01\x125\n" +
	"\x14fronting_provider_id\x18i \x01(\tH\n" +
	"R\x12frontingProviderId\x88\x01\x01\x12 \n" +
	"\tis_replay\x18j \x01(\bH\vR\bisReplay\x88\x01\x01\x12A\n" +
	"\x1anetwork_latency_multiplier\x18q \x01(\x01H\fR\x18networkLatencyMultiplier\x88\x01\x01\x12&\n" +
	"\fnetwork_type\x18r \x01(\tH\rR\vnetworkType\x88\x01\x01\x12*\n" +
	"\x0erelay_protocol\x18s \x01(\tH\x0eR\rrelayProtocol\x88\x01\x01\x121\n" +
	"\x12ssh_client_version\x18t \x01(\tH\x0fR\x10sshClientVersion\x88\x01\x01\x121\n" +
	"\x12stored_tactics_tag\x18u \x01(\tH\x10R\x10storedTacticsTag\x88\x01\x01B\x12\n" +
	"\x10_metadata_clientB\x12\n" +
	"\x10_metadata_deviceB\x13\n" +
	"\x11_metadata_sessionB\x18\n" +
	"\x16_metadata_server_entryB\x10\n" +
	"\x0e_metadata_meekB\x16\n" +
	"\x14_applied_tactics_tagB\x10\n" +
	"\x0e_dial_durationB\x13\n" +
	"\x11_dial_port_numberB\x10\n" +
	"\x0e_egress_regionB\x1c\n" +
	"\x1a_established_tunnels_countB\x17\n" +
	"\x15_fronting_provider_idB\f\n" +
	"\n" +
	"_is_replayB\x1d\n" +
	"\x1b_network_latency_multiplierB\x0f\n" +
	"\r_network_typeB\x11\n" +
	"\x0f_relay_protocolB\x15\n" +
	"\x13_ssh_client_versionB\x15\n" +
	"\x13_stored_tactics_tagB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_inproxy_broker_proto_rawDescOnce sync.Once
	file_proto_inproxy_broker_proto_rawDescData []byte
)

func file_proto_inproxy_broker_proto_rawDescGZIP() []byte {
	file_proto_inproxy_broker_proto_rawDescOnce.Do(func() {
		file_proto_inproxy_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inproxy_broker_proto_rawDesc), len(file_proto_inproxy_broker_proto_rawDesc)))
	})
	return file_proto_inproxy_broker_proto_rawDescData
}

var file_proto_inproxy_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_inproxy_broker_proto_goTypes = []any{
	(*InproxyBroker)(nil),       // 0: psiphond.InproxyBroker
	(*MetadataClient)(nil),      // 1: psiphond.MetadataClient
	(*MetadataDevice)(nil),      // 2: psiphond.MetadataDevice
	(*MetadataSession)(nil),     // 3: psiphond.MetadataSession
	(*MetadataServerEntry)(nil), // 4: psiphond.MetadataServerEntry
	(*MetadataMeek)(nil),        // 5: psiphond.MetadataMeek
}
var file_proto_inproxy_broker_proto_depIdxs = []int32{
	1, // 0: psiphond.InproxyBroker.metadata_client:type_name -> psiphond.MetadataClient
	2, // 1: psiphond.InproxyBroker.metadata_device:type_name -> psiphond.MetadataDevice
	3, // 2: psiphond.InproxyBroker.metadata_session:type_name -> psiphond.MetadataSession
	4, // 3: psiphond.InproxyBroker.metadata_server_entry:type_name -> psiphond.MetadataServerEntry
	5, // 4: psiphond.InproxyBroker.metadata_meek:type_name -> psiphond.MetadataMeek
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_inproxy_broker_proto_init() }
func file_proto_inproxy_broker_proto_init() {
	if File_proto_inproxy_broker_proto != nil {
		return
	}
	file_proto_metadata_proto_init()
	file_proto_inproxy_broker_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inproxy_broker_proto_rawDesc), len(file_proto_inproxy_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_inproxy_broker_proto_goTypes,
		DependencyIndexes: file_proto_inproxy_broker_proto_depIdxs,
		MessageInfos:      file_proto_inproxy_broker_proto_msgTypes,
	}.Build()
	File_proto_inproxy_broker_proto = out.File
	file_proto_inproxy_broker_proto_goTypes = nil
	file_proto_inproxy_broker_proto_depIdxs = nil
}
