// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orphan_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrphanPacket struct {
	state                                                protoimpl.MessageState `protogen:"open.v1"`
	DownstreamPacketRejectedDisallowedDomain             uint64                 `protobuf:"varint,100,opt,name=downstream_packet_rejected_disallowed_domain,json=downstreamPacketRejectedDisallowedDomain,proto3" json:"downstream_packet_rejected_disallowed_domain,omitempty"`
	DownstreamPacketRejectedDisallowedTcpDestinationPort uint64                 `protobuf:"varint,101,opt,name=downstream_packet_rejected_disallowed_tcp_destination_port,json=downstreamPacketRejectedDisallowedTcpDestinationPort,proto3" json:"downstream_packet_rejected_disallowed_tcp_destination_port,omitempty"`
	DownstreamPacketRejectedDisallowedUdpDestinationPort uint64                 `protobuf:"varint,102,opt,name=downstream_packet_rejected_disallowed_udp_destination_port,json=downstreamPacketRejectedDisallowedUdpDestinationPort,proto3" json:"downstream_packet_rejected_disallowed_udp_destination_port,omitempty"`
	DownstreamPacketRejectedInvalidDestinationAddress    uint64                 `protobuf:"varint,103,opt,name=downstream_packet_rejected_invalid_destination_address,json=downstreamPacketRejectedInvalidDestinationAddress,proto3" json:"downstream_packet_rejected_invalid_destination_address,omitempty"`
	DownstreamPacketRejectedInvalidDnsMessage            uint64                 `protobuf:"varint,104,opt,name=downstream_packet_rejected_invalid_dns_message,json=downstreamPacketRejectedInvalidDnsMessage,proto3" json:"downstream_packet_rejected_invalid_dns_message,omitempty"`
	DownstreamPacketRejectedInvalidIpHeaderOptions       uint64                 `protobuf:"varint,105,opt,name=downstream_packet_rejected_invalid_ip_header_options,json=downstreamPacketRejectedInvalidIpHeaderOptions,proto3" json:"downstream_packet_rejected_invalid_ip_header_options,omitempty"`
	DownstreamPacketRejectedInvalidIpHeaderProtocol      uint64                 `protobuf:"varint,106,opt,name=downstream_packet_rejected_invalid_ip_header_protocol,json=downstreamPacketRejectedInvalidIpHeaderProtocol,proto3" json:"downstream_packet_rejected_invalid_ip_header_protocol,omitempty"`
	DownstreamPacketRejectedInvalidIpHeaderVersion       uint64                 `protobuf:"varint,107,opt,name=downstream_packet_rejected_invalid_ip_header_version,json=downstreamPacketRejectedInvalidIpHeaderVersion,proto3" json:"downstream_packet_rejected_invalid_ip_header_version,omitempty"`
	DownstreamPacketRejectedInvalidIpPacketLength        uint64                 `protobuf:"varint,108,opt,name=downstream_packet_rejected_invalid_ip_packet_length,json=downstreamPacketRejectedInvalidIpPacketLength,proto3" json:"downstream_packet_rejected_invalid_ip_packet_length,omitempty"`
	DownstreamPacketRejectedInvalidTcpPacketLength       uint64                 `protobuf:"varint,109,opt,name=downstream_packet_rejected_invalid_tcp_packet_length,json=downstreamPacketRejectedInvalidTcpPacketLength,proto3" json:"downstream_packet_rejected_invalid_tcp_packet_length,omitempty"`
	DownstreamPacketRejectedNoClient                     uint64                 `protobuf:"varint,110,opt,name=downstream_packet_rejected_no_client,json=downstreamPacketRejectedNoClient,proto3" json:"downstream_packet_rejected_no_client,omitempty"`
	DownstreamPacketRejectedNoDnsResolvers               uint64                 `protobuf:"varint,111,opt,name=downstream_packet_rejected_no_dns_resolvers,json=downstreamPacketRejectedNoDnsResolvers,proto3" json:"downstream_packet_rejected_no_dns_resolvers,omitempty"`
	DownstreamPacketRejectedNoOriginalAddress            uint64                 `protobuf:"varint,112,opt,name=downstream_packet_rejected_no_original_address,json=downstreamPacketRejectedNoOriginalAddress,proto3" json:"downstream_packet_rejected_no_original_address,omitempty"`
	DownstreamPacketRejectedNoSession                    uint64                 `protobuf:"varint,113,opt,name=downstream_packet_rejected_no_session,json=downstreamPacketRejectedNoSession,proto3" json:"downstream_packet_rejected_no_session,omitempty"`
	UpstreamPacketRejectedDisallowedDomain               uint64                 `protobuf:"varint,114,opt,name=upstream_packet_rejected_disallowed_domain,json=upstreamPacketRejectedDisallowedDomain,proto3" json:"upstream_packet_rejected_disallowed_domain,omitempty"`
	UpstreamPacketRejectedDisallowedTcpDestinationPort   uint64                 `protobuf:"varint,115,opt,name=upstream_packet_rejected_disallowed_tcp_destination_port,json=upstreamPacketRejectedDisallowedTcpDestinationPort,proto3" json:"upstream_packet_rejected_disallowed_tcp_destination_port,omitempty"`
	UpstreamPacketRejectedDisallowedUdpDestinationPort   uint64                 `protobuf:"varint,116,opt,name=upstream_packet_rejected_disallowed_udp_destination_port,json=upstreamPacketRejectedDisallowedUdpDestinationPort,proto3" json:"upstream_packet_rejected_disallowed_udp_destination_port,omitempty"`
	UpstreamPacketRejectedInvalidDestinationAddress      uint64                 `protobuf:"varint,117,opt,name=upstream_packet_rejected_invalid_destination_address,json=upstreamPacketRejectedInvalidDestinationAddress,proto3" json:"upstream_packet_rejected_invalid_destination_address,omitempty"`
	UpstreamPacketRejectedInvalidDnsMessage              uint64                 `protobuf:"varint,118,opt,name=upstream_packet_rejected_invalid_dns_message,json=upstreamPacketRejectedInvalidDnsMessage,proto3" json:"upstream_packet_rejected_invalid_dns_message,omitempty"`
	UpstreamPacketRejectedInvalidIpHeaderOptions         uint64                 `protobuf:"varint,119,opt,name=upstream_packet_rejected_invalid_ip_header_options,json=upstreamPacketRejectedInvalidIpHeaderOptions,proto3" json:"upstream_packet_rejected_invalid_ip_header_options,omitempty"`
	UpstreamPacketRejectedInvalidIpHeaderProtocol        uint64                 `protobuf:"varint,120,opt,name=upstream_packet_rejected_invalid_ip_header_protocol,json=upstreamPacketRejectedInvalidIpHeaderProtocol,proto3" json:"upstream_packet_rejected_invalid_ip_header_protocol,omitempty"`
	UpstreamPacketRejectedInvalidIpHeaderVersion         uint64                 `protobuf:"varint,121,opt,name=upstream_packet_rejected_invalid_ip_header_version,json=upstreamPacketRejectedInvalidIpHeaderVersion,proto3" json:"upstream_packet_rejected_invalid_ip_header_version,omitempty"`
	UpstreamPacketRejectedInvalidIpPacketLength          uint64                 `protobuf:"varint,122,opt,name=upstream_packet_rejected_invalid_ip_packet_length,json=upstreamPacketRejectedInvalidIpPacketLength,proto3" json:"upstream_packet_rejected_invalid_ip_packet_length,omitempty"`
	UpstreamPacketRejectedInvalidTcpPacketLength         uint64                 `protobuf:"varint,123,opt,name=upstream_packet_rejected_invalid_tcp_packet_length,json=upstreamPacketRejectedInvalidTcpPacketLength,proto3" json:"upstream_packet_rejected_invalid_tcp_packet_length,omitempty"`
	UpstreamPacketRejectedNoClient                       uint64                 `protobuf:"varint,124,opt,name=upstream_packet_rejected_no_client,json=upstreamPacketRejectedNoClient,proto3" json:"upstream_packet_rejected_no_client,omitempty"`
	UpstreamPacketRejectedNoDnsResolvers                 uint64                 `protobuf:"varint,125,opt,name=upstream_packet_rejected_no_dns_resolvers,json=upstreamPacketRejectedNoDnsResolvers,proto3" json:"upstream_packet_rejected_no_dns_resolvers,omitempty"`
	UpstreamPacketRejectedNoOriginalAddress              uint64                 `protobuf:"varint,126,opt,name=upstream_packet_rejected_no_original_address,json=upstreamPacketRejectedNoOriginalAddress,proto3" json:"upstream_packet_rejected_no_original_address,omitempty"`
	UpstreamPacketRejectedNoSession                      uint64                 `protobuf:"varint,127,opt,name=upstream_packet_rejected_no_session,json=upstreamPacketRejectedNoSession,proto3" json:"upstream_packet_rejected_no_session,omitempty"`
	unknownFields                                        protoimpl.UnknownFields
	sizeCache                                            protoimpl.SizeCache
}

func (x *OrphanPacket) Reset() {
	*x = OrphanPacket{}
	mi := &file_proto_orphan_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphanPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphanPacket) ProtoMessage() {}

func (x *OrphanPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orphan_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphanPacket.ProtoReflect.Descriptor instead.
func (*OrphanPacket) Descriptor() ([]byte, []int) {
	return file_proto_orphan_packet_proto_rawDescGZIP(), []int{0}
}

func (x *OrphanPacket) GetDownstreamPacketRejectedDisallowedDomain() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedDisallowedDomain
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedDisallowedTcpDestinationPort() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedDisallowedTcpDestinationPort
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedDisallowedUdpDestinationPort() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedDisallowedUdpDestinationPort
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidDestinationAddress() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidDestinationAddress
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidDnsMessage() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidDnsMessage
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidIpHeaderOptions() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidIpHeaderOptions
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidIpHeaderProtocol() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidIpHeaderProtocol
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidIpHeaderVersion() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidIpHeaderVersion
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidIpPacketLength() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidIpPacketLength
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedInvalidTcpPacketLength() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedInvalidTcpPacketLength
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedNoClient() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedNoClient
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedNoDnsResolvers() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedNoDnsResolvers
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedNoOriginalAddress() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedNoOriginalAddress
	}
	return 0
}

func (x *OrphanPacket) GetDownstreamPacketRejectedNoSession() uint64 {
	if x != nil {
		return x.DownstreamPacketRejectedNoSession
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedDisallowedDomain() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedDisallowedDomain
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedDisallowedTcpDestinationPort() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedDisallowedTcpDestinationPort
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedDisallowedUdpDestinationPort() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedDisallowedUdpDestinationPort
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidDestinationAddress() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidDestinationAddress
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidDnsMessage() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidDnsMessage
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidIpHeaderOptions() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidIpHeaderOptions
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidIpHeaderProtocol() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidIpHeaderProtocol
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidIpHeaderVersion() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidIpHeaderVersion
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidIpPacketLength() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidIpPacketLength
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedInvalidTcpPacketLength() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedInvalidTcpPacketLength
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedNoClient() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedNoClient
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedNoDnsResolvers() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedNoDnsResolvers
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedNoOriginalAddress() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedNoOriginalAddress
	}
	return 0
}

func (x *OrphanPacket) GetUpstreamPacketRejectedNoSession() uint64 {
	if x != nil {
		return x.UpstreamPacketRejectedNoSession
	}
	return 0
}

var File_proto_orphan_packet_proto protoreflect.FileDescriptor

const file_proto_orphan_packet_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orphan_packet.proto\x12\bpsiphond\"\xba\x16\n" +
	"\fOrphanPacket\x12^\n" +
	",downstream_packet_rejected_disallowed_domain\x18d \x01(\x04R(downstreamPacketRejectedDisallowedDomain\x12x\n" +
	":downstream_packet_rejected_disallowed_tcp_destination_port\x18e \x01(\x04R4downstreamPacketRejectedDisallowedTcpDestinationPort\x12x\n" +
	":downstream_packet_rejected_disallowed_udp_destination_port\x18f \x01(\x04R4downstreamPacketRejectedDisallowedUdpDestinationPort\x12q\n" +
	"6downstream_packet_rejected_invalid_destination_address\x18g \x01(\x04R1downstreamPacketRejectedInvalidDestinationAddress\x12a\n" +
	".downstream_packet_rejected_invalid_dns_message\x18h \x01(\x04R)downstreamPacketRejectedInvalidDnsMessage\x12l\n" +
	"4downstream_packet_rejected_invalid_ip_header_options\x18i \x01(\x04R.downstreamPacketRejectedInvalidIpHeaderOptions\x12n\n" +
	"5downstream_packet_rejected_invalid_ip_header_protocol\x18j \x01(\x04R/downstreamPacketRejectedInvalidIpHeaderProtocol\x12l\n" +
	"4downstream_packet_rejected_invalid_ip_header_version\x18k \x01(\x04R.downstreamPacketRejectedInvalidIpHeaderVersion\x12j\n" +
	"3downstream_packet_rejected_invalid_ip_packet_length\x18l \x01(\x04R-downstreamPacketRejectedInvalidIpPacketLength\x12l\n" +
	"4downstream_packet_rejected_invalid_tcp_packet_length\x18m \x01(\x04R.downstreamPacketRejectedInvalidTcpPacketLength\x12N\n" +
	"$downstream_packet_rejected_no_client\x18n \x01(\x04R downstreamPacketRejectedNoClient\x12[\n" +
	"+downstream_packet_rejected_no_dns_resolvers\x18o \x01(\x04R&downstreamPacketRejectedNoDnsResolvers\x12a\n" +
	".downstream_packet_rejected_no_original_address\x18p \x01(\x04R)downstreamPacketRejectedNoOriginalAddress\x12P\n" +
	"%downstream_packet_rejected_no_session\x18q \x01(\x04R!downstreamPacketRejectedNoSession\x12Z\n" +
	"*upstream_packet_rejected_disallowed_domain\x18r \x01(\x04R&upstreamPacketRejectedDisallowedDomain\x12t\n" +
	"8upstream_packet_rejected_disallowed_tcp_destination_port\x18s \x01(\x04R2upstreamPacketRejectedDisallowedTcpDestinationPort\x12t\n" +
	"8upstream_packet_rejected_disallowed_udp_destination_port\x18t \x01(\x04R2upstreamPacketRejectedDisallowedUdpDestinationPort\x12m\n" +
	"4upstream_packet_rejected_invalid_destination_address\x18u \x01(\x04R/upstreamPacketRejectedInvalidDestinationAddress\x12]\n" +
	",upstream_packet_rejected_invalid_dns_message\x18v \x01(\x04R'upstreamPacketRejectedInvalidDnsMessage\x12h\n" +
	"2upstream_packet_rejected_invalid_ip_header_options\x18w \x01(\x04R,upstreamPacketRejectedInvalidIpHeaderOptions\x12j\n" +
	"3upstream_packet_rejected_invalid_ip_header_protocol\x18x \x01(\x04R-upstreamPacketRejectedInvalidIpHeaderProtocol\x12h\n" +
	"2upstream_packet_rejected_invalid_ip_header_version\x18y \x01(\x04R,upstreamPacketRejectedInvalidIpHeaderVersion\x12f\n" +
	"1upstream_packet_rejected_invalid_ip_packet_length\x18z \x01(\x04R+upstreamPacketRejectedInvalidIpPacketLength\x12h\n" +
	"2upstream_packet_rejected_invalid_tcp_packet_length\x18{ \x01(\x04R,upstreamPacketRejectedInvalidTcpPacketLength\x12J\n" +
	"\"upstream_packet_rejected_no_client\x18| \x01(\x04R\x1eupstreamPacketRejectedNoClient\x12W\n" +
	")upstream_packet_rejected_no_dns_resolvers\x18} \x01(\x04R$upstreamPacketRejectedNoDnsResolvers\x12]\n" +
	",upstream_packet_rejected_no_original_address\x18~ \x01(\x04R'upstreamPacketRejectedNoOriginalAddress\x12L\n" +
	"#upstream_packet_rejected_no_session\x18\x7f \x01(\x04R\x1fupstreamPacketRejectedNoSessionB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_orphan_packet_proto_rawDescOnce sync.Once
	file_proto_orphan_packet_proto_rawDescData []byte
)

func file_proto_orphan_packet_proto_rawDescGZIP() []byte {
	file_proto_orphan_packet_proto_rawDescOnce.Do(func() {
		file_proto_orphan_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orphan_packet_proto_rawDesc), len(file_proto_orphan_packet_proto_rawDesc)))
	})
	return file_proto_orphan_packet_proto_rawDescData
}

var file_proto_orphan_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_orphan_packet_proto_goTypes = []any{
	(*OrphanPacket)(nil), // 0: psiphond.OrphanPacket
}
var file_proto_orphan_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orphan_packet_proto_init() }
func file_proto_orphan_packet_proto_init() {
	if File_proto_orphan_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orphan_packet_proto_rawDesc), len(file_proto_orphan_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_orphan_packet_proto_goTypes,
		DependencyIndexes: file_proto_orphan_packet_proto_depIdxs,
		MessageInfos:      file_proto_orphan_packet_proto_msgTypes,
	}.Build()
	File_proto_orphan_packet_proto = out.File
	file_proto_orphan_packet_proto_goTypes = nil
	file_proto_orphan_packet_proto_depIdxs = nil
}
