// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: proto/remote_server_list.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteServerList struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MetadataClient          *MetadataClient        `protobuf:"bytes,1,opt,name=metadata_client,json=metadataClient,proto3" json:"metadata_client,omitempty"`
	MetadataSession         *MetadataSession       `protobuf:"bytes,2,opt,name=metadata_session,json=metadataSession,proto3" json:"metadata_session,omitempty"`
	Authenticated           bool                   `protobuf:"varint,3,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	AuthorizedAccessTypes   string                 `protobuf:"bytes,4,opt,name=authorized_access_types,json=authorizedAccessTypes,proto3" json:"authorized_access_types,omitempty"` //LowCardinality
	Bytes                   uint64                 `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	DeviceLocation          string                 `protobuf:"bytes,6,opt,name=device_location,json=deviceLocation,proto3" json:"device_location,omitempty"`
	Duration                uint64                 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Etag                    string                 `protobuf:"bytes,8,opt,name=etag,proto3" json:"etag,omitempty"`                                                         //LowCardinality
	FrontingProviderId      string                 `protobuf:"bytes,9,opt,name=fronting_provider_id,json=frontingProviderId,proto3" json:"fronting_provider_id,omitempty"` //LowCardinality
	MeekDialDomain          string                 `protobuf:"bytes,10,opt,name=meek_dial_domain,json=meekDialDomain,proto3" json:"meek_dial_domain,omitempty"`
	MeekHostHeader          string                 `protobuf:"bytes,11,opt,name=meek_host_header,json=meekHostHeader,proto3" json:"meek_host_header,omitempty"`                              //LowCardinality
	MeekResolvedIpAddress   string                 `protobuf:"bytes,12,opt,name=meek_resolved_ip_address,json=meekResolvedIpAddress,proto3" json:"meek_resolved_ip_address,omitempty"`       //LowCardinality
	MeekSniServerName       string                 `protobuf:"bytes,13,opt,name=meek_sni_server_name,json=meekSniServerName,proto3" json:"meek_sni_server_name,omitempty"`                   //LowCardinality
	MeekTransformedHostName string                 `protobuf:"bytes,14,opt,name=meek_transformed_host_name,json=meekTransformedHostName,proto3" json:"meek_transformed_host_name,omitempty"` //LowCardinality
	TlsFragmented           bool                   `protobuf:"varint,15,opt,name=tls_fragmented,json=tlsFragmented,proto3" json:"tls_fragmented,omitempty"`
	TlsProfile              string                 `protobuf:"bytes,16,opt,name=tls_profile,json=tlsProfile,proto3" json:"tls_profile,omitempty"` //LowCardinality
	TlsVersion              string                 `protobuf:"bytes,17,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"` //LowCardinality
	Tunneled                bool                   `protobuf:"varint,18,opt,name=tunneled,proto3" json:"tunneled,omitempty"`
	Url                     string                 `protobuf:"bytes,19,opt,name=url,proto3" json:"url,omitempty"`                              //LowCardinality
	UserAgent               string                 `protobuf:"bytes,20,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` //LowCardinality
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RemoteServerList) Reset() {
	*x = RemoteServerList{}
	mi := &file_proto_remote_server_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteServerList) ProtoMessage() {}

func (x *RemoteServerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remote_server_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteServerList.ProtoReflect.Descriptor instead.
func (*RemoteServerList) Descriptor() ([]byte, []int) {
	return file_proto_remote_server_list_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteServerList) GetMetadataClient() *MetadataClient {
	if x != nil {
		return x.MetadataClient
	}
	return nil
}

func (x *RemoteServerList) GetMetadataSession() *MetadataSession {
	if x != nil {
		return x.MetadataSession
	}
	return nil
}

func (x *RemoteServerList) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *RemoteServerList) GetAuthorizedAccessTypes() string {
	if x != nil {
		return x.AuthorizedAccessTypes
	}
	return ""
}

func (x *RemoteServerList) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *RemoteServerList) GetDeviceLocation() string {
	if x != nil {
		return x.DeviceLocation
	}
	return ""
}

func (x *RemoteServerList) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RemoteServerList) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *RemoteServerList) GetFrontingProviderId() string {
	if x != nil {
		return x.FrontingProviderId
	}
	return ""
}

func (x *RemoteServerList) GetMeekDialDomain() string {
	if x != nil {
		return x.MeekDialDomain
	}
	return ""
}

func (x *RemoteServerList) GetMeekHostHeader() string {
	if x != nil {
		return x.MeekHostHeader
	}
	return ""
}

func (x *RemoteServerList) GetMeekResolvedIpAddress() string {
	if x != nil {
		return x.MeekResolvedIpAddress
	}
	return ""
}

func (x *RemoteServerList) GetMeekSniServerName() string {
	if x != nil {
		return x.MeekSniServerName
	}
	return ""
}

func (x *RemoteServerList) GetMeekTransformedHostName() string {
	if x != nil {
		return x.MeekTransformedHostName
	}
	return ""
}

func (x *RemoteServerList) GetTlsFragmented() bool {
	if x != nil {
		return x.TlsFragmented
	}
	return false
}

func (x *RemoteServerList) GetTlsProfile() string {
	if x != nil {
		return x.TlsProfile
	}
	return ""
}

func (x *RemoteServerList) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

func (x *RemoteServerList) GetTunneled() bool {
	if x != nil {
		return x.Tunneled
	}
	return false
}

func (x *RemoteServerList) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RemoteServerList) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_proto_remote_server_list_proto protoreflect.FileDescriptor

const file_proto_remote_server_list_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/remote_server_list.proto\x12\bpsiphond\x1a\x14proto/metadata.proto\"\xcb\x06\n" +
	"\x10RemoteServerList\x12A\n" +
	"\x0fmetadata_client\x18\x01 \x01(\v2\x18.psiphond.MetadataClientR\x0emetadataClient\x12D\n" +
	"\x10metadata_session\x18\x02 \x01(\v2\x19.psiphond.MetadataSessionR\x0fmetadataSession\x12$\n" +
	"\rauthenticated\x18\x03 \x01(\bR\rauthenticated\x126\n" +
	"\x17authorized_access_types\x18\x04 \x01(\tR\x15authorizedAccessTypes\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x04R\x05bytes\x12'\n" +
	"\x0fdevice_location\x18\x06 \x01(\tR\x0edeviceLocation\x12\x1a\n" +
	"\bduration\x18\a \x01(\x04R\bduration\x12\x12\n" +
	"\x04etag\x18\b \x01(\tR\x04etag\x120\n" +
	"\x14fronting_provider_id\x18\t \x01(\tR\x12frontingProviderId\x12(\n" +
	"\x10meek_dial_domain\x18\n" +
	" \x01(\tR\x0emeekDialDomain\x12(\n" +
	"\x10meek_host_header\x18\v \x01(\tR\x0emeekHostHeader\x127\n" +
	"\x18meek_resolved_ip_address\x18\f \x01(\tR\x15meekResolvedIpAddress\x12/\n" +
	"\x14meek_sni_server_name\x18\r \x01(\tR\x11meekSniServerName\x12;\n" +
	"\x1ameek_transformed_host_name\x18\x0e \x01(\tR\x17meekTransformedHostName\x12%\n" +
	"\x0etls_fragmented\x18\x0f \x01(\bR\rtlsFragmented\x12\x1f\n" +
	"\vtls_profile\x18\x10 \x01(\tR\n" +
	"tlsProfile\x12\x1f\n" +
	"\vtls_version\x18\x11 \x01(\tR\n" +
	"tlsVersion\x12\x1a\n" +
	"\btunneled\x18\x12 \x01(\bR\btunneled\x12\x10\n" +
	"\x03url\x18\x13 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x14 \x01(\tR\tuserAgentB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_remote_server_list_proto_rawDescOnce sync.Once
	file_proto_remote_server_list_proto_rawDescData []byte
)

func file_proto_remote_server_list_proto_rawDescGZIP() []byte {
	file_proto_remote_server_list_proto_rawDescOnce.Do(func() {
		file_proto_remote_server_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_remote_server_list_proto_rawDesc), len(file_proto_remote_server_list_proto_rawDesc)))
	})
	return file_proto_remote_server_list_proto_rawDescData
}

var file_proto_remote_server_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_remote_server_list_proto_goTypes = []any{
	(*RemoteServerList)(nil), // 0: psiphond.RemoteServerList
	(*MetadataClient)(nil),   // 1: psiphond.MetadataClient
	(*MetadataSession)(nil),  // 2: psiphond.MetadataSession
}
var file_proto_remote_server_list_proto_depIdxs = []int32{
	1, // 0: psiphond.RemoteServerList.metadata_client:type_name -> psiphond.MetadataClient
	2, // 1: psiphond.RemoteServerList.metadata_session:type_name -> psiphond.MetadataSession
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_remote_server_list_proto_init() }
func file_proto_remote_server_list_proto_init() {
	if File_proto_remote_server_list_proto != nil {
		return
	}
	file_proto_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_remote_server_list_proto_rawDesc), len(file_proto_remote_server_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_remote_server_list_proto_goTypes,
		DependencyIndexes: file_proto_remote_server_list_proto_depIdxs,
		MessageInfos:      file_proto_remote_server_list_proto_msgTypes,
	}.Build()
	File_proto_remote_server_list_proto = out.File
	file_proto_remote_server_list_proto_goTypes = nil
	file_proto_remote_server_list_proto_depIdxs = nil
}
