// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/server_blocklist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerBlocklistHit struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MetadataClient     *MetadataClient        `protobuf:"bytes,1,opt,name=metadata_client,json=metadataClient,proto3,oneof" json:"metadata_client,omitempty"`
	MetadataDevice     *MetadataDevice        `protobuf:"bytes,2,opt,name=metadata_device,json=metadataDevice,proto3,oneof" json:"metadata_device,omitempty"`
	MetadataSession    *MetadataSession       `protobuf:"bytes,3,opt,name=metadata_session,json=metadataSession,proto3,oneof" json:"metadata_session,omitempty"`
	BlocklistIpAddress *string                `protobuf:"bytes,100,opt,name=blocklist_ip_address,json=blocklistIpAddress,proto3,oneof" json:"blocklist_ip_address,omitempty"` //LowCardinality
	BlocklistSource    *string                `protobuf:"bytes,101,opt,name=blocklist_source,json=blocklistSource,proto3,oneof" json:"blocklist_source,omitempty"`            //LowCardinality
	BlocklistSubject   *string                `protobuf:"bytes,102,opt,name=blocklist_subject,json=blocklistSubject,proto3,oneof" json:"blocklist_subject,omitempty"`         //LowCardinality
	EgressRegion       *string                `protobuf:"bytes,103,opt,name=egress_region,json=egressRegion,proto3,oneof" json:"egress_region,omitempty"`                     //LowCardinality
	LastConnected      *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=last_connected,json=lastConnected,proto3,oneof" json:"last_connected,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerBlocklistHit) Reset() {
	*x = ServerBlocklistHit{}
	mi := &file_proto_server_blocklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerBlocklistHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerBlocklistHit) ProtoMessage() {}

func (x *ServerBlocklistHit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_blocklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerBlocklistHit.ProtoReflect.Descriptor instead.
func (*ServerBlocklistHit) Descriptor() ([]byte, []int) {
	return file_proto_server_blocklist_proto_rawDescGZIP(), []int{0}
}

func (x *ServerBlocklistHit) GetMetadataClient() *MetadataClient {
	if x != nil {
		return x.MetadataClient
	}
	return nil
}

func (x *ServerBlocklistHit) GetMetadataDevice() *MetadataDevice {
	if x != nil {
		return x.MetadataDevice
	}
	return nil
}

func (x *ServerBlocklistHit) GetMetadataSession() *MetadataSession {
	if x != nil {
		return x.MetadataSession
	}
	return nil
}

func (x *ServerBlocklistHit) GetBlocklistIpAddress() string {
	if x != nil && x.BlocklistIpAddress != nil {
		return *x.BlocklistIpAddress
	}
	return ""
}

func (x *ServerBlocklistHit) GetBlocklistSource() string {
	if x != nil && x.BlocklistSource != nil {
		return *x.BlocklistSource
	}
	return ""
}

func (x *ServerBlocklistHit) GetBlocklistSubject() string {
	if x != nil && x.BlocklistSubject != nil {
		return *x.BlocklistSubject
	}
	return ""
}

func (x *ServerBlocklistHit) GetEgressRegion() string {
	if x != nil && x.EgressRegion != nil {
		return *x.EgressRegion
	}
	return ""
}

func (x *ServerBlocklistHit) GetLastConnected() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConnected
	}
	return nil
}

var File_proto_server_blocklist_proto protoreflect.FileDescriptor

const file_proto_server_blocklist_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/server_blocklist.proto\x12\bpsiphond\x1a\x14proto/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x05\n" +
	"\x12ServerBlocklistHit\x12F\n" +
	"\x0fmetadata_client\x18\x01 \x01(\v2\x18.psiphond.MetadataClientH\x00R\x0emetadataClient\x88\x01\x01\x12F\n" +
	"\x0fmetadata_device\x18\x02 \x01(\v2\x18.psiphond.MetadataDeviceH\x01R\x0emetadataDevice\x88\x01\x01\x12I\n" +
	"\x10metadata_session\x18\x03 \x01(\v2\x19.psiphond.MetadataSessionH\x02R\x0fmetadataSession\x88\x01\x01\x125\n" +
	"\x14blocklist_ip_address\x18d \x01(\tH\x03R\x12blocklistIpAddress\x88\x01\x01\x12.\n" +
	"\x10blocklist_source\x18e \x01(\tH\x04R\x0fblocklistSource\x88\x01\x01\x120\n" +
	"\x11blocklist_subject\x18f \x01(\tH\x05R\x10blocklistSubject\x88\x01\x01\x12(\n" +
	"\regress_region\x18g \x01(\tH\x06R\fegressRegion\x88\x01\x01\x12F\n" +
	"\x0elast_connected\x18h \x01(\v2\x1a.google.protobuf.TimestampH\aR\rlastConnected\x88\x01\x01B\x12\n" +
	"\x10_metadata_clientB\x12\n" +
	"\x10_metadata_deviceB\x13\n" +
	"\x11_metadata_sessionB\x17\n" +
	"\x15_blocklist_ip_addressB\x13\n" +
	"\x11_blocklist_sourceB\x14\n" +
	"\x12_blocklist_subjectB\x10\n" +
	"\x0e_egress_regionB\x11\n" +
	"\x0f_last_connectedB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_server_blocklist_proto_rawDescOnce sync.Once
	file_proto_server_blocklist_proto_rawDescData []byte
)

func file_proto_server_blocklist_proto_rawDescGZIP() []byte {
	file_proto_server_blocklist_proto_rawDescOnce.Do(func() {
		file_proto_server_blocklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_blocklist_proto_rawDesc), len(file_proto_server_blocklist_proto_rawDesc)))
	})
	return file_proto_server_blocklist_proto_rawDescData
}

var file_proto_server_blocklist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_server_blocklist_proto_goTypes = []any{
	(*ServerBlocklistHit)(nil),    // 0: psiphond.ServerBlocklistHit
	(*MetadataClient)(nil),        // 1: psiphond.MetadataClient
	(*MetadataDevice)(nil),        // 2: psiphond.MetadataDevice
	(*MetadataSession)(nil),       // 3: psiphond.MetadataSession
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_server_blocklist_proto_depIdxs = []int32{
	1, // 0: psiphond.ServerBlocklistHit.metadata_client:type_name -> psiphond.MetadataClient
	2, // 1: psiphond.ServerBlocklistHit.metadata_device:type_name -> psiphond.MetadataDevice
	3, // 2: psiphond.ServerBlocklistHit.metadata_session:type_name -> psiphond.MetadataSession
	4, // 3: psiphond.ServerBlocklistHit.last_connected:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_server_blocklist_proto_init() }
func file_proto_server_blocklist_proto_init() {
	if File_proto_server_blocklist_proto != nil {
		return
	}
	file_proto_metadata_proto_init()
	file_proto_server_blocklist_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_blocklist_proto_rawDesc), len(file_proto_server_blocklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_server_blocklist_proto_goTypes,
		DependencyIndexes: file_proto_server_blocklist_proto_depIdxs,
		MessageInfos:      file_proto_server_blocklist_proto_msgTypes,
	}.Build()
	File_proto_server_blocklist_proto = out.File
	file_proto_server_blocklist_proto_goTypes = nil
	file_proto_server_blocklist_proto_depIdxs = nil
}
