// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/server_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerPacket struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TcpIpv4ApplicationBytesDown uint64                 `protobuf:"varint,100,opt,name=tcp_ipv4_application_bytes_down,json=tcpIpv4ApplicationBytesDown,proto3" json:"tcp_ipv4_application_bytes_down,omitempty"`
	TcpIpv4ApplicationBytesUp   uint64                 `protobuf:"varint,101,opt,name=tcp_ipv4_application_bytes_up,json=tcpIpv4ApplicationBytesUp,proto3" json:"tcp_ipv4_application_bytes_up,omitempty"`
	TcpIpv4BytesDown            uint64                 `protobuf:"varint,102,opt,name=tcp_ipv4_bytes_down,json=tcpIpv4BytesDown,proto3" json:"tcp_ipv4_bytes_down,omitempty"`
	TcpIpv4BytesUp              uint64                 `protobuf:"varint,103,opt,name=tcp_ipv4_bytes_up,json=tcpIpv4BytesUp,proto3" json:"tcp_ipv4_bytes_up,omitempty"`
	TcpIpv4PacketsDown          uint64                 `protobuf:"varint,104,opt,name=tcp_ipv4_packets_down,json=tcpIpv4PacketsDown,proto3" json:"tcp_ipv4_packets_down,omitempty"`
	TcpIpv4PacketsUp            uint64                 `protobuf:"varint,105,opt,name=tcp_ipv4_packets_up,json=tcpIpv4PacketsUp,proto3" json:"tcp_ipv4_packets_up,omitempty"`
	TcpIpv6ApplicationBytesDown uint64                 `protobuf:"varint,106,opt,name=tcp_ipv6_application_bytes_down,json=tcpIpv6ApplicationBytesDown,proto3" json:"tcp_ipv6_application_bytes_down,omitempty"`
	TcpIpv6ApplicationBytesUp   uint64                 `protobuf:"varint,107,opt,name=tcp_ipv6_application_bytes_up,json=tcpIpv6ApplicationBytesUp,proto3" json:"tcp_ipv6_application_bytes_up,omitempty"`
	TcpIpv6BytesDown            uint64                 `protobuf:"varint,108,opt,name=tcp_ipv6_bytes_down,json=tcpIpv6BytesDown,proto3" json:"tcp_ipv6_bytes_down,omitempty"`
	TcpIpv6BytesUp              uint64                 `protobuf:"varint,109,opt,name=tcp_ipv6_bytes_up,json=tcpIpv6BytesUp,proto3" json:"tcp_ipv6_bytes_up,omitempty"`
	TcpIpv6PacketsDown          uint64                 `protobuf:"varint,110,opt,name=tcp_ipv6_packets_down,json=tcpIpv6PacketsDown,proto3" json:"tcp_ipv6_packets_down,omitempty"`
	TcpIpv6PacketsUp            uint64                 `protobuf:"varint,111,opt,name=tcp_ipv6_packets_up,json=tcpIpv6PacketsUp,proto3" json:"tcp_ipv6_packets_up,omitempty"`
	UdpIpv4ApplicationBytesDown uint64                 `protobuf:"varint,112,opt,name=udp_ipv4_application_bytes_down,json=udpIpv4ApplicationBytesDown,proto3" json:"udp_ipv4_application_bytes_down,omitempty"`
	UdpIpv4ApplicationBytesUp   uint64                 `protobuf:"varint,113,opt,name=udp_ipv4_application_bytes_up,json=udpIpv4ApplicationBytesUp,proto3" json:"udp_ipv4_application_bytes_up,omitempty"`
	UdpIpv4BytesDown            uint64                 `protobuf:"varint,114,opt,name=udp_ipv4_bytes_down,json=udpIpv4BytesDown,proto3" json:"udp_ipv4_bytes_down,omitempty"`
	UdpIpv4BytesUp              uint64                 `protobuf:"varint,115,opt,name=udp_ipv4_bytes_up,json=udpIpv4BytesUp,proto3" json:"udp_ipv4_bytes_up,omitempty"`
	UdpIpv4PacketsDown          uint64                 `protobuf:"varint,116,opt,name=udp_ipv4_packets_down,json=udpIpv4PacketsDown,proto3" json:"udp_ipv4_packets_down,omitempty"`
	UdpIpv4PacketsUp            uint64                 `protobuf:"varint,117,opt,name=udp_ipv4_packets_up,json=udpIpv4PacketsUp,proto3" json:"udp_ipv4_packets_up,omitempty"`
	UdpIpv6ApplicationBytesDown uint64                 `protobuf:"varint,118,opt,name=udp_ipv6_application_bytes_down,json=udpIpv6ApplicationBytesDown,proto3" json:"udp_ipv6_application_bytes_down,omitempty"`
	UdpIpv6ApplicationBytesUp   uint64                 `protobuf:"varint,119,opt,name=udp_ipv6_application_bytes_up,json=udpIpv6ApplicationBytesUp,proto3" json:"udp_ipv6_application_bytes_up,omitempty"`
	UdpIpv6BytesDown            uint64                 `protobuf:"varint,120,opt,name=udp_ipv6_bytes_down,json=udpIpv6BytesDown,proto3" json:"udp_ipv6_bytes_down,omitempty"`
	UdpIpv6BytesUp              uint64                 `protobuf:"varint,121,opt,name=udp_ipv6_bytes_up,json=udpIpv6BytesUp,proto3" json:"udp_ipv6_bytes_up,omitempty"`
	UdpIpv6PacketsDown          uint64                 `protobuf:"varint,122,opt,name=udp_ipv6_packets_down,json=udpIpv6PacketsDown,proto3" json:"udp_ipv6_packets_down,omitempty"`
	UdpIpv6PacketsUp            uint64                 `protobuf:"varint,123,opt,name=udp_ipv6_packets_up,json=udpIpv6PacketsUp,proto3" json:"udp_ipv6_packets_up,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_proto_server_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_proto_server_packet_proto_rawDescGZIP(), []int{0}
}

func (x *ServerPacket) GetTcpIpv4ApplicationBytesDown() uint64 {
	if x != nil {
		return x.TcpIpv4ApplicationBytesDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv4ApplicationBytesUp() uint64 {
	if x != nil {
		return x.TcpIpv4ApplicationBytesUp
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv4BytesDown() uint64 {
	if x != nil {
		return x.TcpIpv4BytesDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv4BytesUp() uint64 {
	if x != nil {
		return x.TcpIpv4BytesUp
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv4PacketsDown() uint64 {
	if x != nil {
		return x.TcpIpv4PacketsDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv4PacketsUp() uint64 {
	if x != nil {
		return x.TcpIpv4PacketsUp
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6ApplicationBytesDown() uint64 {
	if x != nil {
		return x.TcpIpv6ApplicationBytesDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6ApplicationBytesUp() uint64 {
	if x != nil {
		return x.TcpIpv6ApplicationBytesUp
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6BytesDown() uint64 {
	if x != nil {
		return x.TcpIpv6BytesDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6BytesUp() uint64 {
	if x != nil {
		return x.TcpIpv6BytesUp
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6PacketsDown() uint64 {
	if x != nil {
		return x.TcpIpv6PacketsDown
	}
	return 0
}

func (x *ServerPacket) GetTcpIpv6PacketsUp() uint64 {
	if x != nil {
		return x.TcpIpv6PacketsUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4ApplicationBytesDown() uint64 {
	if x != nil {
		return x.UdpIpv4ApplicationBytesDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4ApplicationBytesUp() uint64 {
	if x != nil {
		return x.UdpIpv4ApplicationBytesUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4BytesDown() uint64 {
	if x != nil {
		return x.UdpIpv4BytesDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4BytesUp() uint64 {
	if x != nil {
		return x.UdpIpv4BytesUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4PacketsDown() uint64 {
	if x != nil {
		return x.UdpIpv4PacketsDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv4PacketsUp() uint64 {
	if x != nil {
		return x.UdpIpv4PacketsUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6ApplicationBytesDown() uint64 {
	if x != nil {
		return x.UdpIpv6ApplicationBytesDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6ApplicationBytesUp() uint64 {
	if x != nil {
		return x.UdpIpv6ApplicationBytesUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6BytesDown() uint64 {
	if x != nil {
		return x.UdpIpv6BytesDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6BytesUp() uint64 {
	if x != nil {
		return x.UdpIpv6BytesUp
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6PacketsDown() uint64 {
	if x != nil {
		return x.UdpIpv6PacketsDown
	}
	return 0
}

func (x *ServerPacket) GetUdpIpv6PacketsUp() uint64 {
	if x != nil {
		return x.UdpIpv6PacketsUp
	}
	return 0
}

var File_proto_server_packet_proto protoreflect.FileDescriptor

const file_proto_server_packet_proto_rawDesc = "" +
	"\n" +
	"\x19proto/server_packet.proto\x12\bpsiphond\"\x9e\n" +
	"\n" +
	"\fServerPacket\x12D\n" +
	"\x1ftcp_ipv4_application_bytes_down\x18d \x01(\x04R\x1btcpIpv4ApplicationBytesDown\x12@\n" +
	"\x1dtcp_ipv4_application_bytes_up\x18e \x01(\x04R\x19tcpIpv4ApplicationBytesUp\x12-\n" +
	"\x13tcp_ipv4_bytes_down\x18f \x01(\x04R\x10tcpIpv4BytesDown\x12)\n" +
	"\x11tcp_ipv4_bytes_up\x18g \x01(\x04R\x0etcpIpv4BytesUp\x121\n" +
	"\x15tcp_ipv4_packets_down\x18h \x01(\x04R\x12tcpIpv4PacketsDown\x12-\n" +
	"\x13tcp_ipv4_packets_up\x18i \x01(\x04R\x10tcpIpv4PacketsUp\x12D\n" +
	"\x1ftcp_ipv6_application_bytes_down\x18j \x01(\x04R\x1btcpIpv6ApplicationBytesDown\x12@\n" +
	"\x1dtcp_ipv6_application_bytes_up\x18k \x01(\x04R\x19tcpIpv6ApplicationBytesUp\x12-\n" +
	"\x13tcp_ipv6_bytes_down\x18l \x01(\x04R\x10tcpIpv6BytesDown\x12)\n" +
	"\x11tcp_ipv6_bytes_up\x18m \x01(\x04R\x0etcpIpv6BytesUp\x121\n" +
	"\x15tcp_ipv6_packets_down\x18n \x01(\x04R\x12tcpIpv6PacketsDown\x12-\n" +
	"\x13tcp_ipv6_packets_up\x18o \x01(\x04R\x10tcpIpv6PacketsUp\x12D\n" +
	"\x1fudp_ipv4_application_bytes_down\x18p \x01(\x04R\x1budpIpv4ApplicationBytesDown\x12@\n" +
	"\x1dudp_ipv4_application_bytes_up\x18q \x01(\x04R\x19udpIpv4ApplicationBytesUp\x12-\n" +
	"\x13udp_ipv4_bytes_down\x18r \x01(\x04R\x10udpIpv4BytesDown\x12)\n" +
	"\x11udp_ipv4_bytes_up\x18s \x01(\x04R\x0eudpIpv4BytesUp\x121\n" +
	"\x15udp_ipv4_packets_down\x18t \x01(\x04R\x12udpIpv4PacketsDown\x12-\n" +
	"\x13udp_ipv4_packets_up\x18u \x01(\x04R\x10udpIpv4PacketsUp\x12D\n" +
	"\x1fudp_ipv6_application_bytes_down\x18v \x01(\x04R\x1budpIpv6ApplicationBytesDown\x12@\n" +
	"\x1dudp_ipv6_application_bytes_up\x18w \x01(\x04R\x19udpIpv6ApplicationBytesUp\x12-\n" +
	"\x13udp_ipv6_bytes_down\x18x \x01(\x04R\x10udpIpv6BytesDown\x12)\n" +
	"\x11udp_ipv6_bytes_up\x18y \x01(\x04R\x0eudpIpv6BytesUp\x121\n" +
	"\x15udp_ipv6_packets_down\x18z \x01(\x04R\x12udpIpv6PacketsDown\x12-\n" +
	"\x13udp_ipv6_packets_up\x18{ \x01(\x04R\x10udpIpv6PacketsUpB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_server_packet_proto_rawDescOnce sync.Once
	file_proto_server_packet_proto_rawDescData []byte
)

func file_proto_server_packet_proto_rawDescGZIP() []byte {
	file_proto_server_packet_proto_rawDescOnce.Do(func() {
		file_proto_server_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_packet_proto_rawDesc), len(file_proto_server_packet_proto_rawDesc)))
	})
	return file_proto_server_packet_proto_rawDescData
}

var file_proto_server_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_server_packet_proto_goTypes = []any{
	(*ServerPacket)(nil), // 0: psiphond.ServerPacket
}
var file_proto_server_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_server_packet_proto_init() }
func file_proto_server_packet_proto_init() {
	if File_proto_server_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_packet_proto_rawDesc), len(file_proto_server_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_server_packet_proto_goTypes,
		DependencyIndexes: file_proto_server_packet_proto_depIdxs,
		MessageInfos:      file_proto_server_packet_proto_msgTypes,
	}.Build()
	File_proto_server_packet_proto = out.File
	file_proto_server_packet_proto_goTypes = nil
	file_proto_server_packet_proto_depIdxs = nil
}
