// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: proto/server_load.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerLoadProtocol struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`     //LowCardinality
	Protocol           string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` //LowCardinality
	AcceptedClients    int64                  `protobuf:"varint,3,opt,name=accepted_clients,json=acceptedClients,proto3" json:"accepted_clients,omitempty"`
	EstablishedClients int64                  `protobuf:"varint,4,opt,name=established_clients,json=establishedClients,proto3" json:"established_clients,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerLoadProtocol) Reset() {
	*x = ServerLoadProtocol{}
	mi := &file_proto_server_load_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLoadProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoadProtocol) ProtoMessage() {}

func (x *ServerLoadProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_load_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoadProtocol.ProtoReflect.Descriptor instead.
func (*ServerLoadProtocol) Descriptor() ([]byte, []int) {
	return file_proto_server_load_proto_rawDescGZIP(), []int{0}
}

func (x *ServerLoadProtocol) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerLoadProtocol) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServerLoadProtocol) GetAcceptedClients() int64 {
	if x != nil {
		return x.AcceptedClients
	}
	return 0
}

func (x *ServerLoadProtocol) GetEstablishedClients() int64 {
	if x != nil {
		return x.EstablishedClients
	}
	return 0
}

type ServerLoadDNS struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DnsServer         string                 `protobuf:"bytes,1,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"` //LowCardinality
	DnsCount          int64                  `protobuf:"varint,2,opt,name=dns_count,json=dnsCount,proto3" json:"dns_count,omitempty"`
	DnsDuration       int64                  `protobuf:"varint,3,opt,name=dns_duration,json=dnsDuration,proto3" json:"dns_duration,omitempty"`
	DnsFailedCount    int64                  `protobuf:"varint,4,opt,name=dns_failed_count,json=dnsFailedCount,proto3" json:"dns_failed_count,omitempty"`
	DnsFailedDuration int64                  `protobuf:"varint,5,opt,name=dns_failed_duration,json=dnsFailedDuration,proto3" json:"dns_failed_duration,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerLoadDNS) Reset() {
	*x = ServerLoadDNS{}
	mi := &file_proto_server_load_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLoadDNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoadDNS) ProtoMessage() {}

func (x *ServerLoadDNS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_load_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoadDNS.ProtoReflect.Descriptor instead.
func (*ServerLoadDNS) Descriptor() ([]byte, []int) {
	return file_proto_server_load_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLoadDNS) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

func (x *ServerLoadDNS) GetDnsCount() int64 {
	if x != nil {
		return x.DnsCount
	}
	return 0
}

func (x *ServerLoadDNS) GetDnsDuration() int64 {
	if x != nil {
		return x.DnsDuration
	}
	return 0
}

func (x *ServerLoadDNS) GetDnsFailedCount() int64 {
	if x != nil {
		return x.DnsFailedCount
	}
	return 0
}

func (x *ServerLoadDNS) GetDnsFailedDuration() int64 {
	if x != nil {
		return x.DnsFailedDuration
	}
	return 0
}

type ServerLoad struct {
	state                                   protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent                              float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	HeapAlloc                               uint64                 `protobuf:"varint,2,opt,name=heap_alloc,json=heapAlloc,proto3" json:"heap_alloc,omitempty"`
	HeapIdle                                uint64                 `protobuf:"varint,3,opt,name=heap_idle,json=heapIdle,proto3" json:"heap_idle,omitempty"`
	HeapInuse                               uint64                 `protobuf:"varint,4,opt,name=heap_inuse,json=heapInuse,proto3" json:"heap_inuse,omitempty"`
	HeapObjects                             uint64                 `protobuf:"varint,5,opt,name=heap_objects,json=heapObjects,proto3" json:"heap_objects,omitempty"`
	HeapReleased                            uint64                 `protobuf:"varint,6,opt,name=heap_released,json=heapReleased,proto3" json:"heap_released,omitempty"`
	HeapSys                                 uint64                 `protobuf:"varint,7,opt,name=heap_sys,json=heapSys,proto3" json:"heap_sys,omitempty"`
	NetworkBytesReceived                    int64                  `protobuf:"varint,8,opt,name=network_bytes_received,json=networkBytesReceived,proto3" json:"network_bytes_received,omitempty"`
	NetworkBytesSent                        int64                  `protobuf:"varint,9,opt,name=network_bytes_sent,json=networkBytesSent,proto3" json:"network_bytes_sent,omitempty"`
	EstablishTunnels                        bool                   `protobuf:"varint,10,opt,name=establish_tunnels,json=establishTunnels,proto3" json:"establish_tunnels,omitempty"`
	EstablishTunnelsLimitedCount            int64                  `protobuf:"varint,11,opt,name=establish_tunnels_limited_count,json=establishTunnelsLimitedCount,proto3" json:"establish_tunnels_limited_count,omitempty"`
	LastGc                                  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_gc,json=lastGc,proto3" json:"last_gc,omitempty"`
	NumForcedGc                             uint32                 `protobuf:"varint,13,opt,name=num_forced_gc,json=numForcedGc,proto3" json:"num_forced_gc,omitempty"`
	NumGc                                   uint32                 `protobuf:"varint,14,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	NumGoroutine                            uint32                 `protobuf:"varint,15,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	ReplayDeleteReplayCount                 int64                  `protobuf:"varint,16,opt,name=replay_delete_replay_count,json=replayDeleteReplayCount,proto3" json:"replay_delete_replay_count,omitempty"`
	ReplayFailedReplayCount                 int64                  `protobuf:"varint,17,opt,name=replay_failed_replay_count,json=replayFailedReplayCount,proto3" json:"replay_failed_replay_count,omitempty"`
	ReplayGetReplayHitCount                 int64                  `protobuf:"varint,18,opt,name=replay_get_replay_hit_count,json=replayGetReplayHitCount,proto3" json:"replay_get_replay_hit_count,omitempty"`
	ReplayGetReplayMissCount                int64                  `protobuf:"varint,19,opt,name=replay_get_replay_miss_count,json=replayGetReplayMissCount,proto3" json:"replay_get_replay_miss_count,omitempty"`
	ReplayMaxCacheEntries                   int64                  `protobuf:"varint,20,opt,name=replay_max_cache_entries,json=replayMaxCacheEntries,proto3" json:"replay_max_cache_entries,omitempty"`
	ReplaySetReplayCount                    int64                  `protobuf:"varint,21,opt,name=replay_set_replay_count,json=replaySetReplayCount,proto3" json:"replay_set_replay_count,omitempty"`
	ServerTacticsCacheHitCount              int64                  `protobuf:"varint,22,opt,name=server_tactics_cache_hit_count,json=serverTacticsCacheHitCount,proto3" json:"server_tactics_cache_hit_count,omitempty"`
	ServerTacticsCacheMissCount             int64                  `protobuf:"varint,23,opt,name=server_tactics_cache_miss_count,json=serverTacticsCacheMissCount,proto3" json:"server_tactics_cache_miss_count,omitempty"`
	ServerTacticsMaxCacheEntries            int64                  `protobuf:"varint,24,opt,name=server_tactics_max_cache_entries,json=serverTacticsMaxCacheEntries,proto3" json:"server_tactics_max_cache_entries,omitempty"`
	ServerTacticsMaxParameterReferences     int64                  `protobuf:"varint,25,opt,name=server_tactics_max_parameter_references,json=serverTacticsMaxParameterReferences,proto3" json:"server_tactics_max_parameter_references,omitempty"`
	TcpIpv4PortForwardDialedCount           int64                  `protobuf:"varint,26,opt,name=tcp_ipv4_port_forward_dialed_count,json=tcpIpv4PortForwardDialedCount,proto3" json:"tcp_ipv4_port_forward_dialed_count,omitempty"`
	TcpIpv4PortForwardDialedDuration        int64                  `protobuf:"varint,27,opt,name=tcp_ipv4_port_forward_dialed_duration,json=tcpIpv4PortForwardDialedDuration,proto3" json:"tcp_ipv4_port_forward_dialed_duration,omitempty"`
	TcpIpv4PortForwardFailedCount           int64                  `protobuf:"varint,28,opt,name=tcp_ipv4_port_forward_failed_count,json=tcpIpv4PortForwardFailedCount,proto3" json:"tcp_ipv4_port_forward_failed_count,omitempty"`
	TcpIpv4PortForwardFailedDuration        int64                  `protobuf:"varint,29,opt,name=tcp_ipv4_port_forward_failed_duration,json=tcpIpv4PortForwardFailedDuration,proto3" json:"tcp_ipv4_port_forward_failed_duration,omitempty"`
	TcpIpv6PortForwardDialedCount           int64                  `protobuf:"varint,30,opt,name=tcp_ipv6_port_forward_dialed_count,json=tcpIpv6PortForwardDialedCount,proto3" json:"tcp_ipv6_port_forward_dialed_count,omitempty"`
	TcpIpv6PortForwardDialedDuration        int64                  `protobuf:"varint,31,opt,name=tcp_ipv6_port_forward_dialed_duration,json=tcpIpv6PortForwardDialedDuration,proto3" json:"tcp_ipv6_port_forward_dialed_duration,omitempty"`
	TcpIpv6PortForwardFailedCount           int64                  `protobuf:"varint,32,opt,name=tcp_ipv6_port_forward_failed_count,json=tcpIpv6PortForwardFailedCount,proto3" json:"tcp_ipv6_port_forward_failed_count,omitempty"`
	TcpIpv6PortForwardFailedDuration        int64                  `protobuf:"varint,33,opt,name=tcp_ipv6_port_forward_failed_duration,json=tcpIpv6PortForwardFailedDuration,proto3" json:"tcp_ipv6_port_forward_failed_duration,omitempty"`
	TcpPortForwardDialedCount               int64                  `protobuf:"varint,34,opt,name=tcp_port_forward_dialed_count,json=tcpPortForwardDialedCount,proto3" json:"tcp_port_forward_dialed_count,omitempty"`
	TcpPortForwardDialedDuration            int64                  `protobuf:"varint,35,opt,name=tcp_port_forward_dialed_duration,json=tcpPortForwardDialedDuration,proto3" json:"tcp_port_forward_dialed_duration,omitempty"`
	TcpPortForwardFailedCount               int64                  `protobuf:"varint,36,opt,name=tcp_port_forward_failed_count,json=tcpPortForwardFailedCount,proto3" json:"tcp_port_forward_failed_count,omitempty"`
	TcpPortForwardFailedDuration            int64                  `protobuf:"varint,37,opt,name=tcp_port_forward_failed_duration,json=tcpPortForwardFailedDuration,proto3" json:"tcp_port_forward_failed_duration,omitempty"`
	TcpPortForwardRejectedDialingLimitCount int64                  `protobuf:"varint,38,opt,name=tcp_port_forward_rejected_dialing_limit_count,json=tcpPortForwardRejectedDialingLimitCount,proto3" json:"tcp_port_forward_rejected_dialing_limit_count,omitempty"`
	TcpPortForwardRejectedDisallowedCount   int64                  `protobuf:"varint,39,opt,name=tcp_port_forward_rejected_disallowed_count,json=tcpPortForwardRejectedDisallowedCount,proto3" json:"tcp_port_forward_rejected_disallowed_count,omitempty"`
	TcpPortForwards                         int64                  `protobuf:"varint,40,opt,name=tcp_port_forwards,json=tcpPortForwards,proto3" json:"tcp_port_forwards,omitempty"`
	UdpPortForwardRejectedDisallowedCount   int64                  `protobuf:"varint,41,opt,name=udp_port_forward_rejected_disallowed_count,json=udpPortForwardRejectedDisallowedCount,proto3" json:"udp_port_forward_rejected_disallowed_count,omitempty"`
	UdpPortForwards                         int64                  `protobuf:"varint,42,opt,name=udp_port_forwards,json=udpPortForwards,proto3" json:"udp_port_forwards,omitempty"`
	TotalTcpPortForwards                    int64                  `protobuf:"varint,43,opt,name=total_tcp_port_forwards,json=totalTcpPortForwards,proto3" json:"total_tcp_port_forwards,omitempty"`
	TotalUdpPortForwards                    int64                  `protobuf:"varint,44,opt,name=total_udp_port_forwards,json=totalUdpPortForwards,proto3" json:"total_udp_port_forwards,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *ServerLoad) Reset() {
	*x = ServerLoad{}
	mi := &file_proto_server_load_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoad) ProtoMessage() {}

func (x *ServerLoad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_load_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoad.ProtoReflect.Descriptor instead.
func (*ServerLoad) Descriptor() ([]byte, []int) {
	return file_proto_server_load_proto_rawDescGZIP(), []int{2}
}

func (x *ServerLoad) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ServerLoad) GetHeapAlloc() uint64 {
	if x != nil {
		return x.HeapAlloc
	}
	return 0
}

func (x *ServerLoad) GetHeapIdle() uint64 {
	if x != nil {
		return x.HeapIdle
	}
	return 0
}

func (x *ServerLoad) GetHeapInuse() uint64 {
	if x != nil {
		return x.HeapInuse
	}
	return 0
}

func (x *ServerLoad) GetHeapObjects() uint64 {
	if x != nil {
		return x.HeapObjects
	}
	return 0
}

func (x *ServerLoad) GetHeapReleased() uint64 {
	if x != nil {
		return x.HeapReleased
	}
	return 0
}

func (x *ServerLoad) GetHeapSys() uint64 {
	if x != nil {
		return x.HeapSys
	}
	return 0
}

func (x *ServerLoad) GetNetworkBytesReceived() int64 {
	if x != nil {
		return x.NetworkBytesReceived
	}
	return 0
}

func (x *ServerLoad) GetNetworkBytesSent() int64 {
	if x != nil {
		return x.NetworkBytesSent
	}
	return 0
}

func (x *ServerLoad) GetEstablishTunnels() bool {
	if x != nil {
		return x.EstablishTunnels
	}
	return false
}

func (x *ServerLoad) GetEstablishTunnelsLimitedCount() int64 {
	if x != nil {
		return x.EstablishTunnelsLimitedCount
	}
	return 0
}

func (x *ServerLoad) GetLastGc() *timestamppb.Timestamp {
	if x != nil {
		return x.LastGc
	}
	return nil
}

func (x *ServerLoad) GetNumForcedGc() uint32 {
	if x != nil {
		return x.NumForcedGc
	}
	return 0
}

func (x *ServerLoad) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *ServerLoad) GetNumGoroutine() uint32 {
	if x != nil {
		return x.NumGoroutine
	}
	return 0
}

func (x *ServerLoad) GetReplayDeleteReplayCount() int64 {
	if x != nil {
		return x.ReplayDeleteReplayCount
	}
	return 0
}

func (x *ServerLoad) GetReplayFailedReplayCount() int64 {
	if x != nil {
		return x.ReplayFailedReplayCount
	}
	return 0
}

func (x *ServerLoad) GetReplayGetReplayHitCount() int64 {
	if x != nil {
		return x.ReplayGetReplayHitCount
	}
	return 0
}

func (x *ServerLoad) GetReplayGetReplayMissCount() int64 {
	if x != nil {
		return x.ReplayGetReplayMissCount
	}
	return 0
}

func (x *ServerLoad) GetReplayMaxCacheEntries() int64 {
	if x != nil {
		return x.ReplayMaxCacheEntries
	}
	return 0
}

func (x *ServerLoad) GetReplaySetReplayCount() int64 {
	if x != nil {
		return x.ReplaySetReplayCount
	}
	return 0
}

func (x *ServerLoad) GetServerTacticsCacheHitCount() int64 {
	if x != nil {
		return x.ServerTacticsCacheHitCount
	}
	return 0
}

func (x *ServerLoad) GetServerTacticsCacheMissCount() int64 {
	if x != nil {
		return x.ServerTacticsCacheMissCount
	}
	return 0
}

func (x *ServerLoad) GetServerTacticsMaxCacheEntries() int64 {
	if x != nil {
		return x.ServerTacticsMaxCacheEntries
	}
	return 0
}

func (x *ServerLoad) GetServerTacticsMaxParameterReferences() int64 {
	if x != nil {
		return x.ServerTacticsMaxParameterReferences
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv4PortForwardDialedCount() int64 {
	if x != nil {
		return x.TcpIpv4PortForwardDialedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv4PortForwardDialedDuration() int64 {
	if x != nil {
		return x.TcpIpv4PortForwardDialedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv4PortForwardFailedCount() int64 {
	if x != nil {
		return x.TcpIpv4PortForwardFailedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv4PortForwardFailedDuration() int64 {
	if x != nil {
		return x.TcpIpv4PortForwardFailedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv6PortForwardDialedCount() int64 {
	if x != nil {
		return x.TcpIpv6PortForwardDialedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv6PortForwardDialedDuration() int64 {
	if x != nil {
		return x.TcpIpv6PortForwardDialedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv6PortForwardFailedCount() int64 {
	if x != nil {
		return x.TcpIpv6PortForwardFailedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpIpv6PortForwardFailedDuration() int64 {
	if x != nil {
		return x.TcpIpv6PortForwardFailedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardDialedCount() int64 {
	if x != nil {
		return x.TcpPortForwardDialedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardDialedDuration() int64 {
	if x != nil {
		return x.TcpPortForwardDialedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardFailedCount() int64 {
	if x != nil {
		return x.TcpPortForwardFailedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardFailedDuration() int64 {
	if x != nil {
		return x.TcpPortForwardFailedDuration
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardRejectedDialingLimitCount() int64 {
	if x != nil {
		return x.TcpPortForwardRejectedDialingLimitCount
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwardRejectedDisallowedCount() int64 {
	if x != nil {
		return x.TcpPortForwardRejectedDisallowedCount
	}
	return 0
}

func (x *ServerLoad) GetTcpPortForwards() int64 {
	if x != nil {
		return x.TcpPortForwards
	}
	return 0
}

func (x *ServerLoad) GetUdpPortForwardRejectedDisallowedCount() int64 {
	if x != nil {
		return x.UdpPortForwardRejectedDisallowedCount
	}
	return 0
}

func (x *ServerLoad) GetUdpPortForwards() int64 {
	if x != nil {
		return x.UdpPortForwards
	}
	return 0
}

func (x *ServerLoad) GetTotalTcpPortForwards() int64 {
	if x != nil {
		return x.TotalTcpPortForwards
	}
	return 0
}

func (x *ServerLoad) GetTotalUdpPortForwards() int64 {
	if x != nil {
		return x.TotalUdpPortForwards
	}
	return 0
}

var File_proto_server_load_proto protoreflect.FileDescriptor

const file_proto_server_load_proto_rawDesc = "" +
	"\n" +
	"\x17proto/server_load.proto\x12\bpsiphond\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\x12ServerLoadProtocol\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12)\n" +
	"\x10accepted_clients\x18\x03 \x01(\x03R\x0facceptedClients\x12/\n" +
	"\x13established_clients\x18\x04 \x01(\x03R\x12establishedClients\"\xc8\x01\n" +
	"\rServerLoadDNS\x12\x1d\n" +
	"\n" +
	"dns_server\x18\x01 \x01(\tR\tdnsServer\x12\x1b\n" +
	"\tdns_count\x18\x02 \x01(\x03R\bdnsCount\x12!\n" +
	"\fdns_duration\x18\x03 \x01(\x03R\vdnsDuration\x12(\n" +
	"\x10dns_failed_count\x18\x04 \x01(\x03R\x0ednsFailedCount\x12.\n" +
	"\x13dns_failed_duration\x18\x05 \x01(\x03R\x11dnsFailedDuration\"\xc8\x14\n" +
	"\n" +
	"ServerLoad\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1d\n" +
	"\n" +
	"heap_alloc\x18\x02 \x01(\x04R\theapAlloc\x12\x1b\n" +
	"\theap_idle\x18\x03 \x01(\x04R\bheapIdle\x12\x1d\n" +
	"\n" +
	"heap_inuse\x18\x04 \x01(\x04R\theapInuse\x12!\n" +
	"\fheap_objects\x18\x05 \x01(\x04R\vheapObjects\x12#\n" +
	"\rheap_released\x18\x06 \x01(\x04R\fheapReleased\x12\x19\n" +
	"\bheap_sys\x18\a \x01(\x04R\aheapSys\x124\n" +
	"\x16network_bytes_received\x18\b \x01(\x03R\x14networkBytesReceived\x12,\n" +
	"\x12network_bytes_sent\x18\t \x01(\x03R\x10networkBytesSent\x12+\n" +
	"\x11establish_tunnels\x18\n" +
	" \x01(\bR\x10establishTunnels\x12E\n" +
	"\x1festablish_tunnels_limited_count\x18\v \x01(\x03R\x1cestablishTunnelsLimitedCount\x123\n" +
	"\alast_gc\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x06lastGc\x12\"\n" +
	"\rnum_forced_gc\x18\r \x01(\rR\vnumForcedGc\x12\x15\n" +
	"\x06num_gc\x18\x0e \x01(\rR\x05numGc\x12#\n" +
	"\rnum_goroutine\x18\x0f \x01(\rR\fnumGoroutine\x12;\n" +
	"\x1areplay_delete_replay_count\x18\x10 \x01(\x03R\x17replayDeleteReplayCount\x12;\n" +
	"\x1areplay_failed_replay_count\x18\x11 \x01(\x03R\x17replayFailedReplayCount\x12<\n" +
	"\x1breplay_get_replay_hit_count\x18\x12 \x01(\x03R\x17replayGetReplayHitCount\x12>\n" +
	"\x1creplay_get_replay_miss_count\x18\x13 \x01(\x03R\x18replayGetReplayMissCount\x127\n" +
	"\x18replay_max_cache_entries\x18\x14 \x01(\x03R\x15replayMaxCacheEntries\x125\n" +
	"\x17replay_set_replay_count\x18\x15 \x01(\x03R\x14replaySetReplayCount\x12B\n" +
	"\x1eserver_tactics_cache_hit_count\x18\x16 \x01(\x03R\x1aserverTacticsCacheHitCount\x12D\n" +
	"\x1fserver_tactics_cache_miss_count\x18\x17 \x01(\x03R\x1bserverTacticsCacheMissCount\x12F\n" +
	" server_tactics_max_cache_entries\x18\x18 \x01(\x03R\x1cserverTacticsMaxCacheEntries\x12T\n" +
	"'server_tactics_max_parameter_references\x18\x19 \x01(\x03R#serverTacticsMaxParameterReferences\x12I\n" +
	"\"tcp_ipv4_port_forward_dialed_count\x18\x1a \x01(\x03R\x1dtcpIpv4PortForwardDialedCount\x12O\n" +
	"%tcp_ipv4_port_forward_dialed_duration\x18\x1b \x01(\x03R tcpIpv4PortForwardDialedDuration\x12I\n" +
	"\"tcp_ipv4_port_forward_failed_count\x18\x1c \x01(\x03R\x1dtcpIpv4PortForwardFailedCount\x12O\n" +
	"%tcp_ipv4_port_forward_failed_duration\x18\x1d \x01(\x03R tcpIpv4PortForwardFailedDuration\x12I\n" +
	"\"tcp_ipv6_port_forward_dialed_count\x18\x1e \x01(\x03R\x1dtcpIpv6PortForwardDialedCount\x12O\n" +
	"%tcp_ipv6_port_forward_dialed_duration\x18\x1f \x01(\x03R tcpIpv6PortForwardDialedDuration\x12I\n" +
	"\"tcp_ipv6_port_forward_failed_count\x18  \x01(\x03R\x1dtcpIpv6PortForwardFailedCount\x12O\n" +
	"%tcp_ipv6_port_forward_failed_duration\x18! \x01(\x03R tcpIpv6PortForwardFailedDuration\x12@\n" +
	"\x1dtcp_port_forward_dialed_count\x18\" \x01(\x03R\x19tcpPortForwardDialedCount\x12F\n" +
	" tcp_port_forward_dialed_duration\x18# \x01(\x03R\x1ctcpPortForwardDialedDuration\x12@\n" +
	"\x1dtcp_port_forward_failed_count\x18$ \x01(\x03R\x19tcpPortForwardFailedCount\x12F\n" +
	" tcp_port_forward_failed_duration\x18% \x01(\x03R\x1ctcpPortForwardFailedDuration\x12^\n" +
	"-tcp_port_forward_rejected_dialing_limit_count\x18& \x01(\x03R'tcpPortForwardRejectedDialingLimitCount\x12Y\n" +
	"*tcp_port_forward_rejected_disallowed_count\x18' \x01(\x03R%tcpPortForwardRejectedDisallowedCount\x12*\n" +
	"\x11tcp_port_forwards\x18( \x01(\x03R\x0ftcpPortForwards\x12Y\n" +
	"*udp_port_forward_rejected_disallowed_count\x18) \x01(\x03R%udpPortForwardRejectedDisallowedCount\x12*\n" +
	"\x11udp_port_forwards\x18* \x01(\x03R\x0fudpPortForwards\x125\n" +
	"\x17total_tcp_port_forwards\x18+ \x01(\x03R\x14totalTcpPortForwards\x125\n" +
	"\x17total_udp_port_forwards\x18, \x01(\x03R\x14totalUdpPortForwardsB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_server_load_proto_rawDescOnce sync.Once
	file_proto_server_load_proto_rawDescData []byte
)

func file_proto_server_load_proto_rawDescGZIP() []byte {
	file_proto_server_load_proto_rawDescOnce.Do(func() {
		file_proto_server_load_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_load_proto_rawDesc), len(file_proto_server_load_proto_rawDesc)))
	})
	return file_proto_server_load_proto_rawDescData
}

var file_proto_server_load_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_server_load_proto_goTypes = []any{
	(*ServerLoadProtocol)(nil),    // 0: psiphond.ServerLoadProtocol
	(*ServerLoadDNS)(nil),         // 1: psiphond.ServerLoadDNS
	(*ServerLoad)(nil),            // 2: psiphond.ServerLoad
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_server_load_proto_depIdxs = []int32{
	3, // 0: psiphond.ServerLoad.last_gc:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_server_load_proto_init() }
func file_proto_server_load_proto_init() {
	if File_proto_server_load_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_load_proto_rawDesc), len(file_proto_server_load_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_server_load_proto_goTypes,
		DependencyIndexes: file_proto_server_load_proto_depIdxs,
		MessageInfos:      file_proto_server_load_proto_msgTypes,
	}.Build()
	File_proto_server_load_proto = out.File
	file_proto_server_load_proto_goTypes = nil
	file_proto_server_load_proto_depIdxs = nil
}
