// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: proto/server_tunnel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerTunnel struct {
	state                                         protoimpl.MessageState `protogen:"open.v1"`
	MetadataClient                                *MetadataClient        `protobuf:"bytes,1,opt,name=metadata_client,json=metadataClient,proto3" json:"metadata_client,omitempty"`
	MetadataDevice                                *MetadataDevice        `protobuf:"bytes,2,opt,name=metadata_device,json=metadataDevice,proto3" json:"metadata_device,omitempty"`
	MetadataSession                               *MetadataSession       `protobuf:"bytes,3,opt,name=metadata_session,json=metadataSession,proto3" json:"metadata_session,omitempty"`
	MetadataServerEntry                           *MetadataServerEntry   `protobuf:"bytes,4,opt,name=metadata_server_entry,json=metadataServerEntry,proto3" json:"metadata_server_entry,omitempty"`
	MetadataMeek                                  *MetadataMeek          `protobuf:"bytes,5,opt,name=metadata_meek,json=metadataMeek,proto3" json:"metadata_meek,omitempty"`
	TunnelId                                      string                 `protobuf:"bytes,6,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	AppliedTacticsTag                             string                 `protobuf:"bytes,7,opt,name=applied_tactics_tag,json=appliedTacticsTag,proto3" json:"applied_tactics_tag,omitempty"`             //LowCardinality
	AuthorizedAccessTypes                         string                 `protobuf:"bytes,8,opt,name=authorized_access_types,json=authorizedAccessTypes,proto3" json:"authorized_access_types,omitempty"` //LowCardinality
	BurstDownstreamFirstBytes                     uint64                 `protobuf:"varint,9,opt,name=burst_downstream_first_bytes,json=burstDownstreamFirstBytes,proto3" json:"burst_downstream_first_bytes,omitempty"`
	BurstDownstreamFirstDuration                  uint64                 `protobuf:"varint,10,opt,name=burst_downstream_first_duration,json=burstDownstreamFirstDuration,proto3" json:"burst_downstream_first_duration,omitempty"`
	BurstDownstreamFirstOffset                    uint64                 `protobuf:"varint,11,opt,name=burst_downstream_first_offset,json=burstDownstreamFirstOffset,proto3" json:"burst_downstream_first_offset,omitempty"`
	BurstDownstreamFirstRate                      uint64                 `protobuf:"varint,12,opt,name=burst_downstream_first_rate,json=burstDownstreamFirstRate,proto3" json:"burst_downstream_first_rate,omitempty"`
	BurstDownstreamLastBytes                      uint64                 `protobuf:"varint,13,opt,name=burst_downstream_last_bytes,json=burstDownstreamLastBytes,proto3" json:"burst_downstream_last_bytes,omitempty"`
	BurstDownstreamLastDuration                   uint64                 `protobuf:"varint,14,opt,name=burst_downstream_last_duration,json=burstDownstreamLastDuration,proto3" json:"burst_downstream_last_duration,omitempty"`
	BurstDownstreamLastOffset                     uint64                 `protobuf:"varint,15,opt,name=burst_downstream_last_offset,json=burstDownstreamLastOffset,proto3" json:"burst_downstream_last_offset,omitempty"`
	BurstDownstreamLastRate                       uint64                 `protobuf:"varint,16,opt,name=burst_downstream_last_rate,json=burstDownstreamLastRate,proto3" json:"burst_downstream_last_rate,omitempty"`
	BurstDownstreamMaxBytes                       uint64                 `protobuf:"varint,17,opt,name=burst_downstream_max_bytes,json=burstDownstreamMaxBytes,proto3" json:"burst_downstream_max_bytes,omitempty"`
	BurstDownstreamMaxDuration                    uint64                 `protobuf:"varint,18,opt,name=burst_downstream_max_duration,json=burstDownstreamMaxDuration,proto3" json:"burst_downstream_max_duration,omitempty"`
	BurstDownstreamMaxOffset                      uint64                 `protobuf:"varint,19,opt,name=burst_downstream_max_offset,json=burstDownstreamMaxOffset,proto3" json:"burst_downstream_max_offset,omitempty"`
	BurstDownstreamMaxRate                        uint64                 `protobuf:"varint,20,opt,name=burst_downstream_max_rate,json=burstDownstreamMaxRate,proto3" json:"burst_downstream_max_rate,omitempty"`
	BurstDownstreamMinBytes                       uint64                 `protobuf:"varint,21,opt,name=burst_downstream_min_bytes,json=burstDownstreamMinBytes,proto3" json:"burst_downstream_min_bytes,omitempty"`
	BurstDownstreamMinDuration                    uint64                 `protobuf:"varint,22,opt,name=burst_downstream_min_duration,json=burstDownstreamMinDuration,proto3" json:"burst_downstream_min_duration,omitempty"`
	BurstDownstreamMinOffset                      uint64                 `protobuf:"varint,23,opt,name=burst_downstream_min_offset,json=burstDownstreamMinOffset,proto3" json:"burst_downstream_min_offset,omitempty"`
	BurstDownstreamMinRate                        uint64                 `protobuf:"varint,24,opt,name=burst_downstream_min_rate,json=burstDownstreamMinRate,proto3" json:"burst_downstream_min_rate,omitempty"`
	BurstUpstreamFirstBytes                       uint64                 `protobuf:"varint,25,opt,name=burst_upstream_first_bytes,json=burstUpstreamFirstBytes,proto3" json:"burst_upstream_first_bytes,omitempty"`
	BurstUpstreamFirstDuration                    uint64                 `protobuf:"varint,26,opt,name=burst_upstream_first_duration,json=burstUpstreamFirstDuration,proto3" json:"burst_upstream_first_duration,omitempty"`
	BurstUpstreamFirstOffset                      uint64                 `protobuf:"varint,27,opt,name=burst_upstream_first_offset,json=burstUpstreamFirstOffset,proto3" json:"burst_upstream_first_offset,omitempty"`
	BurstUpstreamFirstRate                        uint64                 `protobuf:"varint,28,opt,name=burst_upstream_first_rate,json=burstUpstreamFirstRate,proto3" json:"burst_upstream_first_rate,omitempty"`
	BurstUpstreamLastBytes                        uint64                 `protobuf:"varint,29,opt,name=burst_upstream_last_bytes,json=burstUpstreamLastBytes,proto3" json:"burst_upstream_last_bytes,omitempty"`
	BurstUpstreamLastDuration                     uint64                 `protobuf:"varint,30,opt,name=burst_upstream_last_duration,json=burstUpstreamLastDuration,proto3" json:"burst_upstream_last_duration,omitempty"`
	BurstUpstreamLastOffset                       uint64                 `protobuf:"varint,31,opt,name=burst_upstream_last_offset,json=burstUpstreamLastOffset,proto3" json:"burst_upstream_last_offset,omitempty"`
	BurstUpstreamLastRate                         uint64                 `protobuf:"varint,32,opt,name=burst_upstream_last_rate,json=burstUpstreamLastRate,proto3" json:"burst_upstream_last_rate,omitempty"`
	BurstUpstreamMaxBytes                         uint64                 `protobuf:"varint,33,opt,name=burst_upstream_max_bytes,json=burstUpstreamMaxBytes,proto3" json:"burst_upstream_max_bytes,omitempty"`
	BurstUpstreamMaxDuration                      uint64                 `protobuf:"varint,34,opt,name=burst_upstream_max_duration,json=burstUpstreamMaxDuration,proto3" json:"burst_upstream_max_duration,omitempty"`
	BurstUpstreamMaxOffset                        uint64                 `protobuf:"varint,35,opt,name=burst_upstream_max_offset,json=burstUpstreamMaxOffset,proto3" json:"burst_upstream_max_offset,omitempty"`
	BurstUpstreamMaxRate                          uint64                 `protobuf:"varint,36,opt,name=burst_upstream_max_rate,json=burstUpstreamMaxRate,proto3" json:"burst_upstream_max_rate,omitempty"`
	BurstUpstreamMinBytes                         uint64                 `protobuf:"varint,37,opt,name=burst_upstream_min_bytes,json=burstUpstreamMinBytes,proto3" json:"burst_upstream_min_bytes,omitempty"`
	BurstUpstreamMinDuration                      uint64                 `protobuf:"varint,38,opt,name=burst_upstream_min_duration,json=burstUpstreamMinDuration,proto3" json:"burst_upstream_min_duration,omitempty"`
	BurstUpstreamMinOffset                        uint64                 `protobuf:"varint,39,opt,name=burst_upstream_min_offset,json=burstUpstreamMinOffset,proto3" json:"burst_upstream_min_offset,omitempty"`
	BurstUpstreamMinRate                          uint64                 `protobuf:"varint,40,opt,name=burst_upstream_min_rate,json=burstUpstreamMinRate,proto3" json:"burst_upstream_min_rate,omitempty"`
	Bytes                                         int64                  `protobuf:"varint,41,opt,name=bytes,proto3" json:"bytes,omitempty"`
	BytesDownTcp                                  int64                  `protobuf:"varint,42,opt,name=bytes_down_tcp,json=bytesDownTcp,proto3" json:"bytes_down_tcp,omitempty"`
	BytesDownUdp                                  int64                  `protobuf:"varint,43,opt,name=bytes_down_udp,json=bytesDownUdp,proto3" json:"bytes_down_udp,omitempty"`
	BytesUpTcp                                    int64                  `protobuf:"varint,44,opt,name=bytes_up_tcp,json=bytesUpTcp,proto3" json:"bytes_up_tcp,omitempty"`
	BytesUpUdp                                    int64                  `protobuf:"varint,45,opt,name=bytes_up_udp,json=bytesUpUdp,proto3" json:"bytes_up_udp,omitempty"`
	CandidateNumber                               uint64                 `protobuf:"varint,46,opt,name=candidate_number,json=candidateNumber,proto3" json:"candidate_number,omitempty"`
	DialDuration                                  uint64                 `protobuf:"varint,47,opt,name=dial_duration,json=dialDuration,proto3" json:"dial_duration,omitempty"`
	DialPortNumber                                uint64                 `protobuf:"varint,48,opt,name=dial_port_number,json=dialPortNumber,proto3" json:"dial_port_number,omitempty"`
	DnsAttempt                                    uint64                 `protobuf:"varint,49,opt,name=dns_attempt,json=dnsAttempt,proto3" json:"dns_attempt,omitempty"`
	DnsPreferred                                  string                 `protobuf:"bytes,50,opt,name=dns_preferred,json=dnsPreferred,proto3" json:"dns_preferred,omitempty"`       //LowCardinality
	DnsPreresolved                                string                 `protobuf:"bytes,51,opt,name=dns_preresolved,json=dnsPreresolved,proto3" json:"dns_preresolved,omitempty"` //LowCardinality
	DnsQnameMismatches                            uint64                 `protobuf:"varint,52,opt,name=dns_qname_mismatches,json=dnsQnameMismatches,proto3" json:"dns_qname_mismatches,omitempty"`
	DnsQnameRandomCasing                          bool                   `protobuf:"varint,53,opt,name=dns_qname_random_casing,json=dnsQnameRandomCasing,proto3" json:"dns_qname_random_casing,omitempty"`
	DnsTransform                                  string                 `protobuf:"bytes,54,opt,name=dns_transform,json=dnsTransform,proto3" json:"dns_transform,omitempty"` //LowCardinality
	DownstreamBytesFragmented                     uint64                 `protobuf:"varint,55,opt,name=downstream_bytes_fragmented,json=downstreamBytesFragmented,proto3" json:"downstream_bytes_fragmented,omitempty"`
	DownstreamMaxBytesWritten                     uint64                 `protobuf:"varint,56,opt,name=downstream_max_bytes_written,json=downstreamMaxBytesWritten,proto3" json:"downstream_max_bytes_written,omitempty"`
	DownstreamMaxDelayed                          uint64                 `protobuf:"varint,57,opt,name=downstream_max_delayed,json=downstreamMaxDelayed,proto3" json:"downstream_max_delayed,omitempty"`
	DownstreamMinBytesWritten                     uint64                 `protobuf:"varint,58,opt,name=downstream_min_bytes_written,json=downstreamMinBytesWritten,proto3" json:"downstream_min_bytes_written,omitempty"`
	DownstreamMinDelayed                          uint64                 `protobuf:"varint,59,opt,name=downstream_min_delayed,json=downstreamMinDelayed,proto3" json:"downstream_min_delayed,omitempty"`
	DownstreamOsshPadding                         uint64                 `protobuf:"varint,60,opt,name=downstream_ossh_padding,json=downstreamOsshPadding,proto3" json:"downstream_ossh_padding,omitempty"`
	Duration                                      uint64                 `protobuf:"varint,61,opt,name=duration,proto3" json:"duration,omitempty"`
	EgressRegion                                  string                 `protobuf:"bytes,62,opt,name=egress_region,json=egressRegion,proto3" json:"egress_region,omitempty"` //LowCardinality
	EstablishedTunnelsCount                       uint64                 `protobuf:"varint,63,opt,name=established_tunnels_count,json=establishedTunnelsCount,proto3" json:"established_tunnels_count,omitempty"`
	EstablishmentDuration                         uint64                 `protobuf:"varint,64,opt,name=establishment_duration,json=establishmentDuration,proto3" json:"establishment_duration,omitempty"`
	FrontingProviderId                            string                 `protobuf:"bytes,65,opt,name=fronting_provider_id,json=frontingProviderId,proto3" json:"fronting_provider_id,omitempty"` //LowCardinality
	HandshakeCompleted                            bool                   `protobuf:"varint,66,opt,name=handshake_completed,json=handshakeCompleted,proto3" json:"handshake_completed,omitempty"`
	HttpTransform                                 string                 `protobuf:"bytes,67,opt,name=http_transform,json=httpTransform,proto3" json:"http_transform,omitempty"` //LowCardinality
	IsFirstTunnelInSession                        bool                   `protobuf:"varint,68,opt,name=is_first_tunnel_in_session,json=isFirstTunnelInSession,proto3" json:"is_first_tunnel_in_session,omitempty"`
	IsReplay                                      bool                   `protobuf:"varint,69,opt,name=is_replay,json=isReplay,proto3" json:"is_replay,omitempty"`
	LastConnected                                 *timestamppb.Timestamp `protobuf:"bytes,70,opt,name=last_connected,json=lastConnected,proto3" json:"last_connected,omitempty"`
	NetworkLatencyMultiplier                      float64                `protobuf:"fixed64,71,opt,name=network_latency_multiplier,json=networkLatencyMultiplier,proto3" json:"network_latency_multiplier,omitempty"`
	NetworkType                                   string                 `protobuf:"bytes,72,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`         //LowCardinality
	NewTacticsTag                                 string                 `protobuf:"bytes,73,opt,name=new_tactics_tag,json=newTacticsTag,proto3" json:"new_tactics_tag,omitempty"` //LowCardinality
	OsshPrefix                                    string                 `protobuf:"bytes,74,opt,name=ossh_prefix,json=osshPrefix,proto3" json:"ossh_prefix,omitempty"`            //LowCardinality
	PadResponse                                   uint64                 `protobuf:"varint,75,opt,name=pad_response,json=padResponse,proto3" json:"pad_response,omitempty"`
	Padding                                       uint64                 `protobuf:"varint,76,opt,name=padding,proto3" json:"padding,omitempty"`
	PassthroughAddress                            string                 `protobuf:"bytes,77,opt,name=passthrough_address,json=passthroughAddress,proto3" json:"passthrough_address,omitempty"` //LowCardinality
	PeakConcurrentDialingPortForwardCountTcp      int64                  `protobuf:"varint,78,opt,name=peak_concurrent_dialing_port_forward_count_tcp,json=peakConcurrentDialingPortForwardCountTcp,proto3" json:"peak_concurrent_dialing_port_forward_count_tcp,omitempty"`
	PeakConcurrentPortForwardCountTcp             int64                  `protobuf:"varint,79,opt,name=peak_concurrent_port_forward_count_tcp,json=peakConcurrentPortForwardCountTcp,proto3" json:"peak_concurrent_port_forward_count_tcp,omitempty"`
	PeakConcurrentPortForwardCountUdp             int64                  `protobuf:"varint,80,opt,name=peak_concurrent_port_forward_count_udp,json=peakConcurrentPortForwardCountUdp,proto3" json:"peak_concurrent_port_forward_count_udp,omitempty"`
	PeakConcurrentProximateAcceptedClients        int64                  `protobuf:"varint,81,opt,name=peak_concurrent_proximate_accepted_clients,json=peakConcurrentProximateAcceptedClients,proto3" json:"peak_concurrent_proximate_accepted_clients,omitempty"`
	PeakConcurrentProximateEstablishedClients     int64                  `protobuf:"varint,82,opt,name=peak_concurrent_proximate_established_clients,json=peakConcurrentProximateEstablishedClients,proto3" json:"peak_concurrent_proximate_established_clients,omitempty"`
	PeakDnsFailureRate                            float64                `protobuf:"fixed64,83,opt,name=peak_dns_failure_rate,json=peakDnsFailureRate,proto3" json:"peak_dns_failure_rate,omitempty"`
	PeakDnsFailureRateSampleSize                  int64                  `protobuf:"varint,84,opt,name=peak_dns_failure_rate_sample_size,json=peakDnsFailureRateSampleSize,proto3" json:"peak_dns_failure_rate_sample_size,omitempty"`
	PeakTcpPortForwardFailureRate                 float64                `protobuf:"fixed64,85,opt,name=peak_tcp_port_forward_failure_rate,json=peakTcpPortForwardFailureRate,proto3" json:"peak_tcp_port_forward_failure_rate,omitempty"`
	PeakTcpPortForwardFailureRateSampleSize       int64                  `protobuf:"varint,86,opt,name=peak_tcp_port_forward_failure_rate_sample_size,json=peakTcpPortForwardFailureRateSampleSize,proto3" json:"peak_tcp_port_forward_failure_rate_sample_size,omitempty"`
	PreHandshakeRandomStreamCount                 int64                  `protobuf:"varint,87,opt,name=pre_handshake_random_stream_count,json=preHandshakeRandomStreamCount,proto3" json:"pre_handshake_random_stream_count,omitempty"`
	PreHandshakeRandomStreamDownstreamBytes       int64                  `protobuf:"varint,88,opt,name=pre_handshake_random_stream_downstream_bytes,json=preHandshakeRandomStreamDownstreamBytes,proto3" json:"pre_handshake_random_stream_downstream_bytes,omitempty"`
	PreHandshakeRandomStreamReceivedUpstreamBytes int64                  `protobuf:"varint,89,opt,name=pre_handshake_random_stream_received_upstream_bytes,json=preHandshakeRandomStreamReceivedUpstreamBytes,proto3" json:"pre_handshake_random_stream_received_upstream_bytes,omitempty"`
	PreHandshakeRandomStreamSentDownstreamBytes   int64                  `protobuf:"varint,90,opt,name=pre_handshake_random_stream_sent_downstream_bytes,json=preHandshakeRandomStreamSentDownstreamBytes,proto3" json:"pre_handshake_random_stream_sent_downstream_bytes,omitempty"`
	PreHandshakeRandomStreamUpstreamBytes         int64                  `protobuf:"varint,91,opt,name=pre_handshake_random_stream_upstream_bytes,json=preHandshakeRandomStreamUpstreamBytes,proto3" json:"pre_handshake_random_stream_upstream_bytes,omitempty"`
	RelayProtocol                                 string                 `protobuf:"bytes,92,opt,name=relay_protocol,json=relayProtocol,proto3" json:"relay_protocol,omitempty"` //LowCardinality
	SeedTransform                                 string                 `protobuf:"bytes,93,opt,name=seed_transform,json=seedTransform,proto3" json:"seed_transform,omitempty"` //LowCardinality
	ServerBpf                                     string                 `protobuf:"bytes,94,opt,name=server_bpf,json=serverBpf,proto3" json:"server_bpf,omitempty"`             //LowCardinality
	SplitTunnel                                   bool                   `protobuf:"varint,95,opt,name=split_tunnel,json=splitTunnel,proto3" json:"split_tunnel,omitempty"`
	SshClientVersion                              string                 `protobuf:"bytes,96,opt,name=ssh_client_version,json=sshClientVersion,proto3" json:"ssh_client_version,omitempty"` //LowCardinality
	StartTime                                     *timestamppb.Timestamp `protobuf:"bytes,97,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StationIpAddress                              string                 `protobuf:"bytes,98,opt,name=station_ip_address,json=stationIpAddress,proto3" json:"station_ip_address,omitempty"` //LowCardinality
	TotalPacketTunnelChannelCount                 int64                  `protobuf:"varint,99,opt,name=total_packet_tunnel_channel_count,json=totalPacketTunnelChannelCount,proto3" json:"total_packet_tunnel_channel_count,omitempty"`
	TotalPortForwardCountTcp                      int64                  `protobuf:"varint,100,opt,name=total_port_forward_count_tcp,json=totalPortForwardCountTcp,proto3" json:"total_port_forward_count_tcp,omitempty"`
	TotalPortForwardCountUdp                      int64                  `protobuf:"varint,101,opt,name=total_port_forward_count_udp,json=totalPortForwardCountUdp,proto3" json:"total_port_forward_count_udp,omitempty"`
	TotalUdpgwChannelCount                        int64                  `protobuf:"varint,102,opt,name=total_udpgw_channel_count,json=totalUdpgwChannelCount,proto3" json:"total_udpgw_channel_count,omitempty"`
	UpstreamBytesFragmented                       uint64                 `protobuf:"varint,103,opt,name=upstream_bytes_fragmented,json=upstreamBytesFragmented,proto3" json:"upstream_bytes_fragmented,omitempty"`
	UpstreamMaxBytesWritten                       uint64                 `protobuf:"varint,104,opt,name=upstream_max_bytes_written,json=upstreamMaxBytesWritten,proto3" json:"upstream_max_bytes_written,omitempty"`
	UpstreamMaxDelayed                            uint64                 `protobuf:"varint,105,opt,name=upstream_max_delayed,json=upstreamMaxDelayed,proto3" json:"upstream_max_delayed,omitempty"`
	UpstreamMinBytesWritten                       uint64                 `protobuf:"varint,106,opt,name=upstream_min_bytes_written,json=upstreamMinBytesWritten,proto3" json:"upstream_min_bytes_written,omitempty"`
	UpstreamMinDelayed                            uint64                 `protobuf:"varint,107,opt,name=upstream_min_delayed,json=upstreamMinDelayed,proto3" json:"upstream_min_delayed,omitempty"`
	UpstreamOsshPadding                           uint64                 `protobuf:"varint,108,opt,name=upstream_ossh_padding,json=upstreamOsshPadding,proto3" json:"upstream_ossh_padding,omitempty"`
	UpstreamProxyCustomHeaderNames                string                 `protobuf:"bytes,109,opt,name=upstream_proxy_custom_header_names,json=upstreamProxyCustomHeaderNames,proto3" json:"upstream_proxy_custom_header_names,omitempty"` //LowCardinality
	UpstreamProxyType                             string                 `protobuf:"bytes,110,opt,name=upstream_proxy_type,json=upstreamProxyType,proto3" json:"upstream_proxy_type,omitempty"`                                            //LowCardinality
	UserAgent                                     string                 `protobuf:"bytes,111,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Post-handshake random stream fields
	RandomStreamCount                 int64 `protobuf:"varint,112,opt,name=random_stream_count,json=randomStreamCount,proto3" json:"random_stream_count,omitempty"`
	RandomStreamUpstreamBytes         int64 `protobuf:"varint,113,opt,name=random_stream_upstream_bytes,json=randomStreamUpstreamBytes,proto3" json:"random_stream_upstream_bytes,omitempty"`
	RandomStreamReceivedUpstreamBytes int64 `protobuf:"varint,114,opt,name=random_stream_received_upstream_bytes,json=randomStreamReceivedUpstreamBytes,proto3" json:"random_stream_received_upstream_bytes,omitempty"`
	RandomStreamDownstreamBytes       int64 `protobuf:"varint,115,opt,name=random_stream_downstream_bytes,json=randomStreamDownstreamBytes,proto3" json:"random_stream_downstream_bytes,omitempty"`
	RandomStreamSentDownstreamBytes   int64 `protobuf:"varint,116,opt,name=random_stream_sent_downstream_bytes,json=randomStreamSentDownstreamBytes,proto3" json:"random_stream_sent_downstream_bytes,omitempty"`
	// Destination bytes fields (legacy format)
	DestBytesAsn     string `protobuf:"bytes,117,opt,name=dest_bytes_asn,json=destBytesAsn,proto3" json:"dest_bytes_asn,omitempty"`
	DestBytes        int64  `protobuf:"varint,118,opt,name=dest_bytes,json=destBytes,proto3" json:"dest_bytes,omitempty"`
	DestBytesUpTcp   int64  `protobuf:"varint,119,opt,name=dest_bytes_up_tcp,json=destBytesUpTcp,proto3" json:"dest_bytes_up_tcp,omitempty"`
	DestBytesDownTcp int64  `protobuf:"varint,120,opt,name=dest_bytes_down_tcp,json=destBytesDownTcp,proto3" json:"dest_bytes_down_tcp,omitempty"`
	DestBytesUpUdp   int64  `protobuf:"varint,121,opt,name=dest_bytes_up_udp,json=destBytesUpUdp,proto3" json:"dest_bytes_up_udp,omitempty"`
	DestBytesDownUdp int64  `protobuf:"varint,122,opt,name=dest_bytes_down_udp,json=destBytesDownUdp,proto3" json:"dest_bytes_down_udp,omitempty"`
	// Additional transport and server entry fields
	RelayedSteeringIp           string `protobuf:"bytes,123,opt,name=relayed_steering_ip,json=relayedSteeringIp,proto3" json:"relayed_steering_ip,omitempty"`
	RequestCheckServerEntryTags int64  `protobuf:"varint,124,opt,name=request_check_server_entry_tags,json=requestCheckServerEntryTags,proto3" json:"request_check_server_entry_tags,omitempty"`
	CheckedServerEntryTags      int64  `protobuf:"varint,125,opt,name=checked_server_entry_tags,json=checkedServerEntryTags,proto3" json:"checked_server_entry_tags,omitempty"`
	InvalidServerEntryTags      int64  `protobuf:"varint,126,opt,name=invalid_server_entry_tags,json=invalidServerEntryTags,proto3" json:"invalid_server_entry_tags,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ServerTunnel) Reset() {
	*x = ServerTunnel{}
	mi := &file_proto_server_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTunnel) ProtoMessage() {}

func (x *ServerTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTunnel.ProtoReflect.Descriptor instead.
func (*ServerTunnel) Descriptor() ([]byte, []int) {
	return file_proto_server_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ServerTunnel) GetMetadataClient() *MetadataClient {
	if x != nil {
		return x.MetadataClient
	}
	return nil
}

func (x *ServerTunnel) GetMetadataDevice() *MetadataDevice {
	if x != nil {
		return x.MetadataDevice
	}
	return nil
}

func (x *ServerTunnel) GetMetadataSession() *MetadataSession {
	if x != nil {
		return x.MetadataSession
	}
	return nil
}

func (x *ServerTunnel) GetMetadataServerEntry() *MetadataServerEntry {
	if x != nil {
		return x.MetadataServerEntry
	}
	return nil
}

func (x *ServerTunnel) GetMetadataMeek() *MetadataMeek {
	if x != nil {
		return x.MetadataMeek
	}
	return nil
}

func (x *ServerTunnel) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ServerTunnel) GetAppliedTacticsTag() string {
	if x != nil {
		return x.AppliedTacticsTag
	}
	return ""
}

func (x *ServerTunnel) GetAuthorizedAccessTypes() string {
	if x != nil {
		return x.AuthorizedAccessTypes
	}
	return ""
}

func (x *ServerTunnel) GetBurstDownstreamFirstBytes() uint64 {
	if x != nil {
		return x.BurstDownstreamFirstBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamFirstDuration() uint64 {
	if x != nil {
		return x.BurstDownstreamFirstDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamFirstOffset() uint64 {
	if x != nil {
		return x.BurstDownstreamFirstOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamFirstRate() uint64 {
	if x != nil {
		return x.BurstDownstreamFirstRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamLastBytes() uint64 {
	if x != nil {
		return x.BurstDownstreamLastBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamLastDuration() uint64 {
	if x != nil {
		return x.BurstDownstreamLastDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamLastOffset() uint64 {
	if x != nil {
		return x.BurstDownstreamLastOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamLastRate() uint64 {
	if x != nil {
		return x.BurstDownstreamLastRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMaxBytes() uint64 {
	if x != nil {
		return x.BurstDownstreamMaxBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMaxDuration() uint64 {
	if x != nil {
		return x.BurstDownstreamMaxDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMaxOffset() uint64 {
	if x != nil {
		return x.BurstDownstreamMaxOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMaxRate() uint64 {
	if x != nil {
		return x.BurstDownstreamMaxRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMinBytes() uint64 {
	if x != nil {
		return x.BurstDownstreamMinBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMinDuration() uint64 {
	if x != nil {
		return x.BurstDownstreamMinDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMinOffset() uint64 {
	if x != nil {
		return x.BurstDownstreamMinOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstDownstreamMinRate() uint64 {
	if x != nil {
		return x.BurstDownstreamMinRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamFirstBytes() uint64 {
	if x != nil {
		return x.BurstUpstreamFirstBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamFirstDuration() uint64 {
	if x != nil {
		return x.BurstUpstreamFirstDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamFirstOffset() uint64 {
	if x != nil {
		return x.BurstUpstreamFirstOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamFirstRate() uint64 {
	if x != nil {
		return x.BurstUpstreamFirstRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamLastBytes() uint64 {
	if x != nil {
		return x.BurstUpstreamLastBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamLastDuration() uint64 {
	if x != nil {
		return x.BurstUpstreamLastDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamLastOffset() uint64 {
	if x != nil {
		return x.BurstUpstreamLastOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamLastRate() uint64 {
	if x != nil {
		return x.BurstUpstreamLastRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMaxBytes() uint64 {
	if x != nil {
		return x.BurstUpstreamMaxBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMaxDuration() uint64 {
	if x != nil {
		return x.BurstUpstreamMaxDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMaxOffset() uint64 {
	if x != nil {
		return x.BurstUpstreamMaxOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMaxRate() uint64 {
	if x != nil {
		return x.BurstUpstreamMaxRate
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMinBytes() uint64 {
	if x != nil {
		return x.BurstUpstreamMinBytes
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMinDuration() uint64 {
	if x != nil {
		return x.BurstUpstreamMinDuration
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMinOffset() uint64 {
	if x != nil {
		return x.BurstUpstreamMinOffset
	}
	return 0
}

func (x *ServerTunnel) GetBurstUpstreamMinRate() uint64 {
	if x != nil {
		return x.BurstUpstreamMinRate
	}
	return 0
}

func (x *ServerTunnel) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ServerTunnel) GetBytesDownTcp() int64 {
	if x != nil {
		return x.BytesDownTcp
	}
	return 0
}

func (x *ServerTunnel) GetBytesDownUdp() int64 {
	if x != nil {
		return x.BytesDownUdp
	}
	return 0
}

func (x *ServerTunnel) GetBytesUpTcp() int64 {
	if x != nil {
		return x.BytesUpTcp
	}
	return 0
}

func (x *ServerTunnel) GetBytesUpUdp() int64 {
	if x != nil {
		return x.BytesUpUdp
	}
	return 0
}

func (x *ServerTunnel) GetCandidateNumber() uint64 {
	if x != nil {
		return x.CandidateNumber
	}
	return 0
}

func (x *ServerTunnel) GetDialDuration() uint64 {
	if x != nil {
		return x.DialDuration
	}
	return 0
}

func (x *ServerTunnel) GetDialPortNumber() uint64 {
	if x != nil {
		return x.DialPortNumber
	}
	return 0
}

func (x *ServerTunnel) GetDnsAttempt() uint64 {
	if x != nil {
		return x.DnsAttempt
	}
	return 0
}

func (x *ServerTunnel) GetDnsPreferred() string {
	if x != nil {
		return x.DnsPreferred
	}
	return ""
}

func (x *ServerTunnel) GetDnsPreresolved() string {
	if x != nil {
		return x.DnsPreresolved
	}
	return ""
}

func (x *ServerTunnel) GetDnsQnameMismatches() uint64 {
	if x != nil {
		return x.DnsQnameMismatches
	}
	return 0
}

func (x *ServerTunnel) GetDnsQnameRandomCasing() bool {
	if x != nil {
		return x.DnsQnameRandomCasing
	}
	return false
}

func (x *ServerTunnel) GetDnsTransform() string {
	if x != nil {
		return x.DnsTransform
	}
	return ""
}

func (x *ServerTunnel) GetDownstreamBytesFragmented() uint64 {
	if x != nil {
		return x.DownstreamBytesFragmented
	}
	return 0
}

func (x *ServerTunnel) GetDownstreamMaxBytesWritten() uint64 {
	if x != nil {
		return x.DownstreamMaxBytesWritten
	}
	return 0
}

func (x *ServerTunnel) GetDownstreamMaxDelayed() uint64 {
	if x != nil {
		return x.DownstreamMaxDelayed
	}
	return 0
}

func (x *ServerTunnel) GetDownstreamMinBytesWritten() uint64 {
	if x != nil {
		return x.DownstreamMinBytesWritten
	}
	return 0
}

func (x *ServerTunnel) GetDownstreamMinDelayed() uint64 {
	if x != nil {
		return x.DownstreamMinDelayed
	}
	return 0
}

func (x *ServerTunnel) GetDownstreamOsshPadding() uint64 {
	if x != nil {
		return x.DownstreamOsshPadding
	}
	return 0
}

func (x *ServerTunnel) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ServerTunnel) GetEgressRegion() string {
	if x != nil {
		return x.EgressRegion
	}
	return ""
}

func (x *ServerTunnel) GetEstablishedTunnelsCount() uint64 {
	if x != nil {
		return x.EstablishedTunnelsCount
	}
	return 0
}

func (x *ServerTunnel) GetEstablishmentDuration() uint64 {
	if x != nil {
		return x.EstablishmentDuration
	}
	return 0
}

func (x *ServerTunnel) GetFrontingProviderId() string {
	if x != nil {
		return x.FrontingProviderId
	}
	return ""
}

func (x *ServerTunnel) GetHandshakeCompleted() bool {
	if x != nil {
		return x.HandshakeCompleted
	}
	return false
}

func (x *ServerTunnel) GetHttpTransform() string {
	if x != nil {
		return x.HttpTransform
	}
	return ""
}

func (x *ServerTunnel) GetIsFirstTunnelInSession() bool {
	if x != nil {
		return x.IsFirstTunnelInSession
	}
	return false
}

func (x *ServerTunnel) GetIsReplay() bool {
	if x != nil {
		return x.IsReplay
	}
	return false
}

func (x *ServerTunnel) GetLastConnected() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConnected
	}
	return nil
}

func (x *ServerTunnel) GetNetworkLatencyMultiplier() float64 {
	if x != nil {
		return x.NetworkLatencyMultiplier
	}
	return 0
}

func (x *ServerTunnel) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *ServerTunnel) GetNewTacticsTag() string {
	if x != nil {
		return x.NewTacticsTag
	}
	return ""
}

func (x *ServerTunnel) GetOsshPrefix() string {
	if x != nil {
		return x.OsshPrefix
	}
	return ""
}

func (x *ServerTunnel) GetPadResponse() uint64 {
	if x != nil {
		return x.PadResponse
	}
	return 0
}

func (x *ServerTunnel) GetPadding() uint64 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *ServerTunnel) GetPassthroughAddress() string {
	if x != nil {
		return x.PassthroughAddress
	}
	return ""
}

func (x *ServerTunnel) GetPeakConcurrentDialingPortForwardCountTcp() int64 {
	if x != nil {
		return x.PeakConcurrentDialingPortForwardCountTcp
	}
	return 0
}

func (x *ServerTunnel) GetPeakConcurrentPortForwardCountTcp() int64 {
	if x != nil {
		return x.PeakConcurrentPortForwardCountTcp
	}
	return 0
}

func (x *ServerTunnel) GetPeakConcurrentPortForwardCountUdp() int64 {
	if x != nil {
		return x.PeakConcurrentPortForwardCountUdp
	}
	return 0
}

func (x *ServerTunnel) GetPeakConcurrentProximateAcceptedClients() int64 {
	if x != nil {
		return x.PeakConcurrentProximateAcceptedClients
	}
	return 0
}

func (x *ServerTunnel) GetPeakConcurrentProximateEstablishedClients() int64 {
	if x != nil {
		return x.PeakConcurrentProximateEstablishedClients
	}
	return 0
}

func (x *ServerTunnel) GetPeakDnsFailureRate() float64 {
	if x != nil {
		return x.PeakDnsFailureRate
	}
	return 0
}

func (x *ServerTunnel) GetPeakDnsFailureRateSampleSize() int64 {
	if x != nil {
		return x.PeakDnsFailureRateSampleSize
	}
	return 0
}

func (x *ServerTunnel) GetPeakTcpPortForwardFailureRate() float64 {
	if x != nil {
		return x.PeakTcpPortForwardFailureRate
	}
	return 0
}

func (x *ServerTunnel) GetPeakTcpPortForwardFailureRateSampleSize() int64 {
	if x != nil {
		return x.PeakTcpPortForwardFailureRateSampleSize
	}
	return 0
}

func (x *ServerTunnel) GetPreHandshakeRandomStreamCount() int64 {
	if x != nil {
		return x.PreHandshakeRandomStreamCount
	}
	return 0
}

func (x *ServerTunnel) GetPreHandshakeRandomStreamDownstreamBytes() int64 {
	if x != nil {
		return x.PreHandshakeRandomStreamDownstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetPreHandshakeRandomStreamReceivedUpstreamBytes() int64 {
	if x != nil {
		return x.PreHandshakeRandomStreamReceivedUpstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetPreHandshakeRandomStreamSentDownstreamBytes() int64 {
	if x != nil {
		return x.PreHandshakeRandomStreamSentDownstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetPreHandshakeRandomStreamUpstreamBytes() int64 {
	if x != nil {
		return x.PreHandshakeRandomStreamUpstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetRelayProtocol() string {
	if x != nil {
		return x.RelayProtocol
	}
	return ""
}

func (x *ServerTunnel) GetSeedTransform() string {
	if x != nil {
		return x.SeedTransform
	}
	return ""
}

func (x *ServerTunnel) GetServerBpf() string {
	if x != nil {
		return x.ServerBpf
	}
	return ""
}

func (x *ServerTunnel) GetSplitTunnel() bool {
	if x != nil {
		return x.SplitTunnel
	}
	return false
}

func (x *ServerTunnel) GetSshClientVersion() string {
	if x != nil {
		return x.SshClientVersion
	}
	return ""
}

func (x *ServerTunnel) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ServerTunnel) GetStationIpAddress() string {
	if x != nil {
		return x.StationIpAddress
	}
	return ""
}

func (x *ServerTunnel) GetTotalPacketTunnelChannelCount() int64 {
	if x != nil {
		return x.TotalPacketTunnelChannelCount
	}
	return 0
}

func (x *ServerTunnel) GetTotalPortForwardCountTcp() int64 {
	if x != nil {
		return x.TotalPortForwardCountTcp
	}
	return 0
}

func (x *ServerTunnel) GetTotalPortForwardCountUdp() int64 {
	if x != nil {
		return x.TotalPortForwardCountUdp
	}
	return 0
}

func (x *ServerTunnel) GetTotalUdpgwChannelCount() int64 {
	if x != nil {
		return x.TotalUdpgwChannelCount
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamBytesFragmented() uint64 {
	if x != nil {
		return x.UpstreamBytesFragmented
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamMaxBytesWritten() uint64 {
	if x != nil {
		return x.UpstreamMaxBytesWritten
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamMaxDelayed() uint64 {
	if x != nil {
		return x.UpstreamMaxDelayed
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamMinBytesWritten() uint64 {
	if x != nil {
		return x.UpstreamMinBytesWritten
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamMinDelayed() uint64 {
	if x != nil {
		return x.UpstreamMinDelayed
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamOsshPadding() uint64 {
	if x != nil {
		return x.UpstreamOsshPadding
	}
	return 0
}

func (x *ServerTunnel) GetUpstreamProxyCustomHeaderNames() string {
	if x != nil {
		return x.UpstreamProxyCustomHeaderNames
	}
	return ""
}

func (x *ServerTunnel) GetUpstreamProxyType() string {
	if x != nil {
		return x.UpstreamProxyType
	}
	return ""
}

func (x *ServerTunnel) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ServerTunnel) GetRandomStreamCount() int64 {
	if x != nil {
		return x.RandomStreamCount
	}
	return 0
}

func (x *ServerTunnel) GetRandomStreamUpstreamBytes() int64 {
	if x != nil {
		return x.RandomStreamUpstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetRandomStreamReceivedUpstreamBytes() int64 {
	if x != nil {
		return x.RandomStreamReceivedUpstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetRandomStreamDownstreamBytes() int64 {
	if x != nil {
		return x.RandomStreamDownstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetRandomStreamSentDownstreamBytes() int64 {
	if x != nil {
		return x.RandomStreamSentDownstreamBytes
	}
	return 0
}

func (x *ServerTunnel) GetDestBytesAsn() string {
	if x != nil {
		return x.DestBytesAsn
	}
	return ""
}

func (x *ServerTunnel) GetDestBytes() int64 {
	if x != nil {
		return x.DestBytes
	}
	return 0
}

func (x *ServerTunnel) GetDestBytesUpTcp() int64 {
	if x != nil {
		return x.DestBytesUpTcp
	}
	return 0
}

func (x *ServerTunnel) GetDestBytesDownTcp() int64 {
	if x != nil {
		return x.DestBytesDownTcp
	}
	return 0
}

func (x *ServerTunnel) GetDestBytesUpUdp() int64 {
	if x != nil {
		return x.DestBytesUpUdp
	}
	return 0
}

func (x *ServerTunnel) GetDestBytesDownUdp() int64 {
	if x != nil {
		return x.DestBytesDownUdp
	}
	return 0
}

func (x *ServerTunnel) GetRelayedSteeringIp() string {
	if x != nil {
		return x.RelayedSteeringIp
	}
	return ""
}

func (x *ServerTunnel) GetRequestCheckServerEntryTags() int64 {
	if x != nil {
		return x.RequestCheckServerEntryTags
	}
	return 0
}

func (x *ServerTunnel) GetCheckedServerEntryTags() int64 {
	if x != nil {
		return x.CheckedServerEntryTags
	}
	return 0
}

func (x *ServerTunnel) GetInvalidServerEntryTags() int64 {
	if x != nil {
		return x.InvalidServerEntryTags
	}
	return 0
}

type ServerTunnelASNDestBytes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TunnelId         string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	DestAsn          string                 `protobuf:"bytes,2,opt,name=dest_asn,json=destAsn,proto3" json:"dest_asn,omitempty"`
	DestBytes        int64                  `protobuf:"varint,3,opt,name=dest_bytes,json=destBytes,proto3" json:"dest_bytes,omitempty"`
	DestBytesUpTcp   int64                  `protobuf:"varint,4,opt,name=dest_bytes_up_tcp,json=destBytesUpTcp,proto3" json:"dest_bytes_up_tcp,omitempty"`
	DestBytesDownTcp int64                  `protobuf:"varint,5,opt,name=dest_bytes_down_tcp,json=destBytesDownTcp,proto3" json:"dest_bytes_down_tcp,omitempty"`
	DestBytesUpUdp   int64                  `protobuf:"varint,6,opt,name=dest_bytes_up_udp,json=destBytesUpUdp,proto3" json:"dest_bytes_up_udp,omitempty"`
	DestBytesDownUdp int64                  `protobuf:"varint,7,opt,name=dest_bytes_down_udp,json=destBytesDownUdp,proto3" json:"dest_bytes_down_udp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerTunnelASNDestBytes) Reset() {
	*x = ServerTunnelASNDestBytes{}
	mi := &file_proto_server_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTunnelASNDestBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTunnelASNDestBytes) ProtoMessage() {}

func (x *ServerTunnelASNDestBytes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTunnelASNDestBytes.ProtoReflect.Descriptor instead.
func (*ServerTunnelASNDestBytes) Descriptor() ([]byte, []int) {
	return file_proto_server_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerTunnelASNDestBytes) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ServerTunnelASNDestBytes) GetDestAsn() string {
	if x != nil {
		return x.DestAsn
	}
	return ""
}

func (x *ServerTunnelASNDestBytes) GetDestBytes() int64 {
	if x != nil {
		return x.DestBytes
	}
	return 0
}

func (x *ServerTunnelASNDestBytes) GetDestBytesUpTcp() int64 {
	if x != nil {
		return x.DestBytesUpTcp
	}
	return 0
}

func (x *ServerTunnelASNDestBytes) GetDestBytesDownTcp() int64 {
	if x != nil {
		return x.DestBytesDownTcp
	}
	return 0
}

func (x *ServerTunnelASNDestBytes) GetDestBytesUpUdp() int64 {
	if x != nil {
		return x.DestBytesUpUdp
	}
	return 0
}

func (x *ServerTunnelASNDestBytes) GetDestBytesDownUdp() int64 {
	if x != nil {
		return x.DestBytesDownUdp
	}
	return 0
}

var File_proto_server_tunnel_proto protoreflect.FileDescriptor

const file_proto_server_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x19proto/server_tunnel.proto\x12\bpsiphond\x1a\x14proto/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba8\n" +
	"\fServerTunnel\x12A\n" +
	"\x0fmetadata_client\x18\x01 \x01(\v2\x18.psiphond.MetadataClientR\x0emetadataClient\x12A\n" +
	"\x0fmetadata_device\x18\x02 \x01(\v2\x18.psiphond.MetadataDeviceR\x0emetadataDevice\x12D\n" +
	"\x10metadata_session\x18\x03 \x01(\v2\x19.psiphond.MetadataSessionR\x0fmetadataSession\x12Q\n" +
	"\x15metadata_server_entry\x18\x04 \x01(\v2\x1d.psiphond.MetadataServerEntryR\x13metadataServerEntry\x12;\n" +
	"\rmetadata_meek\x18\x05 \x01(\v2\x16.psiphond.MetadataMeekR\fmetadataMeek\x12\x1b\n" +
	"\ttunnel_id\x18\x06 \x01(\tR\btunnelId\x12.\n" +
	"\x13applied_tactics_tag\x18\a \x01(\tR\x11appliedTacticsTag\x126\n" +
	"\x17authorized_access_types\x18\b \x01(\tR\x15authorizedAccessTypes\x12?\n" +
	"\x1cburst_downstream_first_bytes\x18\t \x01(\x04R\x19burstDownstreamFirstBytes\x12E\n" +
	"\x1fburst_downstream_first_duration\x18\n" +
	" \x01(\x04R\x1cburstDownstreamFirstDuration\x12A\n" +
	"\x1dburst_downstream_first_offset\x18\v \x01(\x04R\x1aburstDownstreamFirstOffset\x12=\n" +
	"\x1bburst_downstream_first_rate\x18\f \x01(\x04R\x18burstDownstreamFirstRate\x12=\n" +
	"\x1bburst_downstream_last_bytes\x18\r \x01(\x04R\x18burstDownstreamLastBytes\x12C\n" +
	"\x1eburst_downstream_last_duration\x18\x0e \x01(\x04R\x1bburstDownstreamLastDuration\x12?\n" +
	"\x1cburst_downstream_last_offset\x18\x0f \x01(\x04R\x19burstDownstreamLastOffset\x12;\n" +
	"\x1aburst_downstream_last_rate\x18\x10 \x01(\x04R\x17burstDownstreamLastRate\x12;\n" +
	"\x1aburst_downstream_max_bytes\x18\x11 \x01(\x04R\x17burstDownstreamMaxBytes\x12A\n" +
	"\x1dburst_downstream_max_duration\x18\x12 \x01(\x04R\x1aburstDownstreamMaxDuration\x12=\n" +
	"\x1bburst_downstream_max_offset\x18\x13 \x01(\x04R\x18burstDownstreamMaxOffset\x129\n" +
	"\x19burst_downstream_max_rate\x18\x14 \x01(\x04R\x16burstDownstreamMaxRate\x12;\n" +
	"\x1aburst_downstream_min_bytes\x18\x15 \x01(\x04R\x17burstDownstreamMinBytes\x12A\n" +
	"\x1dburst_downstream_min_duration\x18\x16 \x01(\x04R\x1aburstDownstreamMinDuration\x12=\n" +
	"\x1bburst_downstream_min_offset\x18\x17 \x01(\x04R\x18burstDownstreamMinOffset\x129\n" +
	"\x19burst_downstream_min_rate\x18\x18 \x01(\x04R\x16burstDownstreamMinRate\x12;\n" +
	"\x1aburst_upstream_first_bytes\x18\x19 \x01(\x04R\x17burstUpstreamFirstBytes\x12A\n" +
	"\x1dburst_upstream_first_duration\x18\x1a \x01(\x04R\x1aburstUpstreamFirstDuration\x12=\n" +
	"\x1bburst_upstream_first_offset\x18\x1b \x01(\x04R\x18burstUpstreamFirstOffset\x129\n" +
	"\x19burst_upstream_first_rate\x18\x1c \x01(\x04R\x16burstUpstreamFirstRate\x129\n" +
	"\x19burst_upstream_last_bytes\x18\x1d \x01(\x04R\x16burstUpstreamLastBytes\x12?\n" +
	"\x1cburst_upstream_last_duration\x18\x1e \x01(\x04R\x19burstUpstreamLastDuration\x12;\n" +
	"\x1aburst_upstream_last_offset\x18\x1f \x01(\x04R\x17burstUpstreamLastOffset\x127\n" +
	"\x18burst_upstream_last_rate\x18  \x01(\x04R\x15burstUpstreamLastRate\x127\n" +
	"\x18burst_upstream_max_bytes\x18! \x01(\x04R\x15burstUpstreamMaxBytes\x12=\n" +
	"\x1bburst_upstream_max_duration\x18\" \x01(\x04R\x18burstUpstreamMaxDuration\x129\n" +
	"\x19burst_upstream_max_offset\x18# \x01(\x04R\x16burstUpstreamMaxOffset\x125\n" +
	"\x17burst_upstream_max_rate\x18$ \x01(\x04R\x14burstUpstreamMaxRate\x127\n" +
	"\x18burst_upstream_min_bytes\x18% \x01(\x04R\x15burstUpstreamMinBytes\x12=\n" +
	"\x1bburst_upstream_min_duration\x18& \x01(\x04R\x18burstUpstreamMinDuration\x129\n" +
	"\x19burst_upstream_min_offset\x18' \x01(\x04R\x16burstUpstreamMinOffset\x125\n" +
	"\x17burst_upstream_min_rate\x18( \x01(\x04R\x14burstUpstreamMinRate\x12\x14\n" +
	"\x05bytes\x18) \x01(\x03R\x05bytes\x12$\n" +
	"\x0ebytes_down_tcp\x18* \x01(\x03R\fbytesDownTcp\x12$\n" +
	"\x0ebytes_down_udp\x18+ \x01(\x03R\fbytesDownUdp\x12 \n" +
	"\fbytes_up_tcp\x18, \x01(\x03R\n" +
	"bytesUpTcp\x12 \n" +
	"\fbytes_up_udp\x18- \x01(\x03R\n" +
	"bytesUpUdp\x12)\n" +
	"\x10candidate_number\x18. \x01(\x04R\x0fcandidateNumber\x12#\n" +
	"\rdial_duration\x18/ \x01(\x04R\fdialDuration\x12(\n" +
	"\x10dial_port_number\x180 \x01(\x04R\x0edialPortNumber\x12\x1f\n" +
	"\vdns_attempt\x181 \x01(\x04R\n" +
	"dnsAttempt\x12#\n" +
	"\rdns_preferred\x182 \x01(\tR\fdnsPreferred\x12'\n" +
	"\x0fdns_preresolved\x183 \x01(\tR\x0ednsPreresolved\x120\n" +
	"\x14dns_qname_mismatches\x184 \x01(\x04R\x12dnsQnameMismatches\x125\n" +
	"\x17dns_qname_random_casing\x185 \x01(\bR\x14dnsQnameRandomCasing\x12#\n" +
	"\rdns_transform\x186 \x01(\tR\fdnsTransform\x12>\n" +
	"\x1bdownstream_bytes_fragmented\x187 \x01(\x04R\x19downstreamBytesFragmented\x12?\n" +
	"\x1cdownstream_max_bytes_written\x188 \x01(\x04R\x19downstreamMaxBytesWritten\x124\n" +
	"\x16downstream_max_delayed\x189 \x01(\x04R\x14downstreamMaxDelayed\x12?\n" +
	"\x1cdownstream_min_bytes_written\x18: \x01(\x04R\x19downstreamMinBytesWritten\x124\n" +
	"\x16downstream_min_delayed\x18; \x01(\x04R\x14downstreamMinDelayed\x126\n" +
	"\x17downstream_ossh_padding\x18< \x01(\x04R\x15downstreamOsshPadding\x12\x1a\n" +
	"\bduration\x18= \x01(\x04R\bduration\x12#\n" +
	"\regress_region\x18> \x01(\tR\fegressRegion\x12:\n" +
	"\x19established_tunnels_count\x18? \x01(\x04R\x17establishedTunnelsCount\x125\n" +
	"\x16establishment_duration\x18@ \x01(\x04R\x15establishmentDuration\x120\n" +
	"\x14fronting_provider_id\x18A \x01(\tR\x12frontingProviderId\x12/\n" +
	"\x13handshake_completed\x18B \x01(\bR\x12handshakeCompleted\x12%\n" +
	"\x0ehttp_transform\x18C \x01(\tR\rhttpTransform\x12:\n" +
	"\x1ais_first_tunnel_in_session\x18D \x01(\bR\x16isFirstTunnelInSession\x12\x1b\n" +
	"\tis_replay\x18E \x01(\bR\bisReplay\x12A\n" +
	"\x0elast_connected\x18F \x01(\v2\x1a.google.protobuf.TimestampR\rlastConnected\x12<\n" +
	"\x1anetwork_latency_multiplier\x18G \x01(\x01R\x18networkLatencyMultiplier\x12!\n" +
	"\fnetwork_type\x18H \x01(\tR\vnetworkType\x12&\n" +
	"\x0fnew_tactics_tag\x18I \x01(\tR\rnewTacticsTag\x12\x1f\n" +
	"\vossh_prefix\x18J \x01(\tR\n" +
	"osshPrefix\x12!\n" +
	"\fpad_response\x18K \x01(\x04R\vpadResponse\x12\x18\n" +
	"\apadding\x18L \x01(\x04R\apadding\x12/\n" +
	"\x13passthrough_address\x18M \x01(\tR\x12passthroughAddress\x12`\n" +
	".peak_concurrent_dialing_port_forward_count_tcp\x18N \x01(\x03R(peakConcurrentDialingPortForwardCountTcp\x12Q\n" +
	"&peak_concurrent_port_forward_count_tcp\x18O \x01(\x03R!peakConcurrentPortForwardCountTcp\x12Q\n" +
	"&peak_concurrent_port_forward_count_udp\x18P \x01(\x03R!peakConcurrentPortForwardCountUdp\x12Z\n" +
	"*peak_concurrent_proximate_accepted_clients\x18Q \x01(\x03R&peakConcurrentProximateAcceptedClients\x12`\n" +
	"-peak_concurrent_proximate_established_clients\x18R \x01(\x03R)peakConcurrentProximateEstablishedClients\x121\n" +
	"\x15peak_dns_failure_rate\x18S \x01(\x01R\x12peakDnsFailureRate\x12G\n" +
	"!peak_dns_failure_rate_sample_size\x18T \x01(\x03R\x1cpeakDnsFailureRateSampleSize\x12I\n" +
	"\"peak_tcp_port_forward_failure_rate\x18U \x01(\x01R\x1dpeakTcpPortForwardFailureRate\x12_\n" +
	".peak_tcp_port_forward_failure_rate_sample_size\x18V \x01(\x03R'peakTcpPortForwardFailureRateSampleSize\x12H\n" +
	"!pre_handshake_random_stream_count\x18W \x01(\x03R\x1dpreHandshakeRandomStreamCount\x12]\n" +
	",pre_handshake_random_stream_downstream_bytes\x18X \x01(\x03R'preHandshakeRandomStreamDownstreamBytes\x12j\n" +
	"3pre_handshake_random_stream_received_upstream_bytes\x18Y \x01(\x03R-preHandshakeRandomStreamReceivedUpstreamBytes\x12f\n" +
	"1pre_handshake_random_stream_sent_downstream_bytes\x18Z \x01(\x03R+preHandshakeRandomStreamSentDownstreamBytes\x12Y\n" +
	"*pre_handshake_random_stream_upstream_bytes\x18[ \x01(\x03R%preHandshakeRandomStreamUpstreamBytes\x12%\n" +
	"\x0erelay_protocol\x18\\ \x01(\tR\rrelayProtocol\x12%\n" +
	"\x0eseed_transform\x18] \x01(\tR\rseedTransform\x12\x1d\n" +
	"\n" +
	"server_bpf\x18^ \x01(\tR\tserverBpf\x12!\n" +
	"\fsplit_tunnel\x18_ \x01(\bR\vsplitTunnel\x12,\n" +
	"\x12ssh_client_version\x18` \x01(\tR\x10sshClientVersion\x129\n" +
	"\n" +
	"start_time\x18a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12,\n" +
	"\x12station_ip_address\x18b \x01(\tR\x10stationIpAddress\x12H\n" +
	"!total_packet_tunnel_channel_count\x18c \x01(\x03R\x1dtotalPacketTunnelChannelCount\x12>\n" +
	"\x1ctotal_port_forward_count_tcp\x18d \x01(\x03R\x18totalPortForwardCountTcp\x12>\n" +
	"\x1ctotal_port_forward_count_udp\x18e \x01(\x03R\x18totalPortForwardCountUdp\x129\n" +
	"\x19total_udpgw_channel_count\x18f \x01(\x03R\x16totalUdpgwChannelCount\x12:\n" +
	"\x19upstream_bytes_fragmented\x18g \x01(\x04R\x17upstreamBytesFragmented\x12;\n" +
	"\x1aupstream_max_bytes_written\x18h \x01(\x04R\x17upstreamMaxBytesWritten\x120\n" +
	"\x14upstream_max_delayed\x18i \x01(\x04R\x12upstreamMaxDelayed\x12;\n" +
	"\x1aupstream_min_bytes_written\x18j \x01(\x04R\x17upstreamMinBytesWritten\x120\n" +
	"\x14upstream_min_delayed\x18k \x01(\x04R\x12upstreamMinDelayed\x122\n" +
	"\x15upstream_ossh_padding\x18l \x01(\x04R\x13upstreamOsshPadding\x12J\n" +
	"\"upstream_proxy_custom_header_names\x18m \x01(\tR\x1eupstreamProxyCustomHeaderNames\x12.\n" +
	"\x13upstream_proxy_type\x18n \x01(\tR\x11upstreamProxyType\x12\x1d\n" +
	"\n" +
	"user_agent\x18o \x01(\tR\tuserAgent\x12.\n" +
	"\x13random_stream_count\x18p \x01(\x03R\x11randomStreamCount\x12?\n" +
	"\x1crandom_stream_upstream_bytes\x18q \x01(\x03R\x19randomStreamUpstreamBytes\x12P\n" +
	"%random_stream_received_upstream_bytes\x18r \x01(\x03R!randomStreamReceivedUpstreamBytes\x12C\n" +
	"\x1erandom_stream_downstream_bytes\x18s \x01(\x03R\x1brandomStreamDownstreamBytes\x12L\n" +
	"#random_stream_sent_downstream_bytes\x18t \x01(\x03R\x1frandomStreamSentDownstreamBytes\x12$\n" +
	"\x0edest_bytes_asn\x18u \x01(\tR\fdestBytesAsn\x12\x1d\n" +
	"\n" +
	"dest_bytes\x18v \x01(\x03R\tdestBytes\x12)\n" +
	"\x11dest_bytes_up_tcp\x18w \x01(\x03R\x0edestBytesUpTcp\x12-\n" +
	"\x13dest_bytes_down_tcp\x18x \x01(\x03R\x10destBytesDownTcp\x12)\n" +
	"\x11dest_bytes_up_udp\x18y \x01(\x03R\x0edestBytesUpUdp\x12-\n" +
	"\x13dest_bytes_down_udp\x18z \x01(\x03R\x10destBytesDownUdp\x12.\n" +
	"\x13relayed_steering_ip\x18{ \x01(\tR\x11relayedSteeringIp\x12D\n" +
	"\x1frequest_check_server_entry_tags\x18| \x01(\x03R\x1brequestCheckServerEntryTags\x129\n" +
	"\x19checked_server_entry_tags\x18} \x01(\x03R\x16checkedServerEntryTags\x129\n" +
	"\x19invalid_server_entry_tags\x18~ \x01(\x03R\x16invalidServerEntryTags\"\xa5\x02\n" +
	"\x18ServerTunnelASNDestBytes\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x19\n" +
	"\bdest_asn\x18\x02 \x01(\tR\adestAsn\x12\x1d\n" +
	"\n" +
	"dest_bytes\x18\x03 \x01(\x03R\tdestBytes\x12)\n" +
	"\x11dest_bytes_up_tcp\x18\x04 \x01(\x03R\x0edestBytesUpTcp\x12-\n" +
	"\x13dest_bytes_down_tcp\x18\x05 \x01(\x03R\x10destBytesDownTcp\x12)\n" +
	"\x11dest_bytes_up_udp\x18\x06 \x01(\x03R\x0edestBytesUpUdp\x12-\n" +
	"\x13dest_bytes_down_udp\x18\a \x01(\x03R\x10destBytesDownUdpB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_server_tunnel_proto_rawDescOnce sync.Once
	file_proto_server_tunnel_proto_rawDescData []byte
)

func file_proto_server_tunnel_proto_rawDescGZIP() []byte {
	file_proto_server_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_server_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_tunnel_proto_rawDesc), len(file_proto_server_tunnel_proto_rawDesc)))
	})
	return file_proto_server_tunnel_proto_rawDescData
}

var file_proto_server_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_server_tunnel_proto_goTypes = []any{
	(*ServerTunnel)(nil),             // 0: psiphond.ServerTunnel
	(*ServerTunnelASNDestBytes)(nil), // 1: psiphond.ServerTunnelASNDestBytes
	(*MetadataClient)(nil),           // 2: psiphond.MetadataClient
	(*MetadataDevice)(nil),           // 3: psiphond.MetadataDevice
	(*MetadataSession)(nil),          // 4: psiphond.MetadataSession
	(*MetadataServerEntry)(nil),      // 5: psiphond.MetadataServerEntry
	(*MetadataMeek)(nil),             // 6: psiphond.MetadataMeek
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_proto_server_tunnel_proto_depIdxs = []int32{
	2, // 0: psiphond.ServerTunnel.metadata_client:type_name -> psiphond.MetadataClient
	3, // 1: psiphond.ServerTunnel.metadata_device:type_name -> psiphond.MetadataDevice
	4, // 2: psiphond.ServerTunnel.metadata_session:type_name -> psiphond.MetadataSession
	5, // 3: psiphond.ServerTunnel.metadata_server_entry:type_name -> psiphond.MetadataServerEntry
	6, // 4: psiphond.ServerTunnel.metadata_meek:type_name -> psiphond.MetadataMeek
	7, // 5: psiphond.ServerTunnel.last_connected:type_name -> google.protobuf.Timestamp
	7, // 6: psiphond.ServerTunnel.start_time:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_server_tunnel_proto_init() }
func file_proto_server_tunnel_proto_init() {
	if File_proto_server_tunnel_proto != nil {
		return
	}
	file_proto_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_tunnel_proto_rawDesc), len(file_proto_server_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_server_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_server_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_server_tunnel_proto_msgTypes,
	}.Build()
	File_proto_server_tunnel_proto = out.File
	file_proto_server_tunnel_proto_goTypes = nil
	file_proto_server_tunnel_proto_depIdxs = nil
}
