// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/unique_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniqueUser struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MetadataClient        *MetadataClient        `protobuf:"bytes,1,opt,name=metadata_client,json=metadataClient,proto3,oneof" json:"metadata_client,omitempty"`
	MetadataDevice        *MetadataDevice        `protobuf:"bytes,2,opt,name=metadata_device,json=metadataDevice,proto3,oneof" json:"metadata_device,omitempty"`
	MetadataSession       *MetadataSession       `protobuf:"bytes,3,opt,name=metadata_session,json=metadataSession,proto3,oneof" json:"metadata_session,omitempty"`
	AuthorizedAccessTypes []string               `protobuf:"bytes,100,rep,name=authorized_access_types,json=authorizedAccessTypes,proto3" json:"authorized_access_types,omitempty"` //LowCardinality
	LastConnected         *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=last_connected,json=lastConnected,proto3,oneof" json:"last_connected,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UniqueUser) Reset() {
	*x = UniqueUser{}
	mi := &file_proto_unique_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueUser) ProtoMessage() {}

func (x *UniqueUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_unique_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueUser.ProtoReflect.Descriptor instead.
func (*UniqueUser) Descriptor() ([]byte, []int) {
	return file_proto_unique_user_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueUser) GetMetadataClient() *MetadataClient {
	if x != nil {
		return x.MetadataClient
	}
	return nil
}

func (x *UniqueUser) GetMetadataDevice() *MetadataDevice {
	if x != nil {
		return x.MetadataDevice
	}
	return nil
}

func (x *UniqueUser) GetMetadataSession() *MetadataSession {
	if x != nil {
		return x.MetadataSession
	}
	return nil
}

func (x *UniqueUser) GetAuthorizedAccessTypes() []string {
	if x != nil {
		return x.AuthorizedAccessTypes
	}
	return nil
}

func (x *UniqueUser) GetLastConnected() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConnected
	}
	return nil
}

var File_proto_unique_user_proto protoreflect.FileDescriptor

const file_proto_unique_user_proto_rawDesc = "" +
	"\n" +
	"\x17proto/unique_user.proto\x12\bpsiphond\x1a\x14proto/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n" +
	"\n" +
	"UniqueUser\x12F\n" +
	"\x0fmetadata_client\x18\x01 \x01(\v2\x18.psiphond.MetadataClientH\x00R\x0emetadataClient\x88\x01\x01\x12F\n" +
	"\x0fmetadata_device\x18\x02 \x01(\v2\x18.psiphond.MetadataDeviceH\x01R\x0emetadataDevice\x88\x01\x01\x12I\n" +
	"\x10metadata_session\x18\x03 \x01(\v2\x19.psiphond.MetadataSessionH\x02R\x0fmetadataSession\x88\x01\x01\x126\n" +
	"\x17authorized_access_types\x18d \x03(\tR\x15authorizedAccessTypes\x12F\n" +
	"\x0elast_connected\x18e \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rlastConnected\x88\x01\x01B\x12\n" +
	"\x10_metadata_clientB\x12\n" +
	"\x10_metadata_deviceB\x13\n" +
	"\x11_metadata_sessionB\x11\n" +
	"\x0f_last_connectedB?Z=github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pbb\x06proto3"

var (
	file_proto_unique_user_proto_rawDescOnce sync.Once
	file_proto_unique_user_proto_rawDescData []byte
)

func file_proto_unique_user_proto_rawDescGZIP() []byte {
	file_proto_unique_user_proto_rawDescOnce.Do(func() {
		file_proto_unique_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_unique_user_proto_rawDesc), len(file_proto_unique_user_proto_rawDesc)))
	})
	return file_proto_unique_user_proto_rawDescData
}

var file_proto_unique_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_unique_user_proto_goTypes = []any{
	(*UniqueUser)(nil),            // 0: psiphond.UniqueUser
	(*MetadataClient)(nil),        // 1: psiphond.MetadataClient
	(*MetadataDevice)(nil),        // 2: psiphond.MetadataDevice
	(*MetadataSession)(nil),       // 3: psiphond.MetadataSession
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_unique_user_proto_depIdxs = []int32{
	1, // 0: psiphond.UniqueUser.metadata_client:type_name -> psiphond.MetadataClient
	2, // 1: psiphond.UniqueUser.metadata_device:type_name -> psiphond.MetadataDevice
	3, // 2: psiphond.UniqueUser.metadata_session:type_name -> psiphond.MetadataSession
	4, // 3: psiphond.UniqueUser.last_connected:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_unique_user_proto_init() }
func file_proto_unique_user_proto_init() {
	if File_proto_unique_user_proto != nil {
		return
	}
	file_proto_metadata_proto_init()
	file_proto_unique_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_unique_user_proto_rawDesc), len(file_proto_unique_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_unique_user_proto_goTypes,
		DependencyIndexes: file_proto_unique_user_proto_depIdxs,
		MessageInfos:      file_proto_unique_user_proto_msgTypes,
	}.Build()
	File_proto_unique_user_proto = out.File
	file_proto_unique_user_proto_goTypes = nil
	file_proto_unique_user_proto_depIdxs = nil
}
