// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ca.psiphon.psiphond/dest_params.proto

package psiphond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientAsn      *string                `protobuf:"bytes,1,opt,name=client_asn,json=clientAsn,proto3,oneof" json:"client_asn,omitempty"`
	ClientPlatform *string                `protobuf:"bytes,2,opt,name=client_platform,json=clientPlatform,proto3,oneof" json:"client_platform,omitempty"`
	ClientRegion   *string                `protobuf:"bytes,3,opt,name=client_region,json=clientRegion,proto3,oneof" json:"client_region,omitempty"`
	DeviceRegion   *string                `protobuf:"bytes,4,opt,name=device_region,json=deviceRegion,proto3,oneof" json:"device_region,omitempty"`
	SponsorId      *string                `protobuf:"bytes,5,opt,name=sponsor_id,json=sponsorId,proto3,oneof" json:"sponsor_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DestParams) Reset() {
	*x = DestParams{}
	mi := &file_ca_psiphon_psiphond_dest_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestParams) ProtoMessage() {}

func (x *DestParams) ProtoReflect() protoreflect.Message {
	mi := &file_ca_psiphon_psiphond_dest_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestParams.ProtoReflect.Descriptor instead.
func (*DestParams) Descriptor() ([]byte, []int) {
	return file_ca_psiphon_psiphond_dest_params_proto_rawDescGZIP(), []int{0}
}

func (x *DestParams) GetClientAsn() string {
	if x != nil && x.ClientAsn != nil {
		return *x.ClientAsn
	}
	return ""
}

func (x *DestParams) GetClientPlatform() string {
	if x != nil && x.ClientPlatform != nil {
		return *x.ClientPlatform
	}
	return ""
}

func (x *DestParams) GetClientRegion() string {
	if x != nil && x.ClientRegion != nil {
		return *x.ClientRegion
	}
	return ""
}

func (x *DestParams) GetDeviceRegion() string {
	if x != nil && x.DeviceRegion != nil {
		return *x.DeviceRegion
	}
	return ""
}

func (x *DestParams) GetSponsorId() string {
	if x != nil && x.SponsorId != nil {
		return *x.SponsorId
	}
	return ""
}

var File_ca_psiphon_psiphond_dest_params_proto protoreflect.FileDescriptor

const file_ca_psiphon_psiphond_dest_params_proto_rawDesc = "" +
	"\n" +
	"%ca.psiphon.psiphond/dest_params.proto\x12\x13ca.psiphon.psiphond\"\xac\x02\n" +
	"\n" +
	"DestParams\x12\"\n" +
	"\n" +
	"client_asn\x18\x01 \x01(\tH\x00R\tclientAsn\x88\x01\x01\x12,\n" +
	"\x0fclient_platform\x18\x02 \x01(\tH\x01R\x0eclientPlatform\x88\x01\x01\x12(\n" +
	"\rclient_region\x18\x03 \x01(\tH\x02R\fclientRegion\x88\x01\x01\x12(\n" +
	"\rdevice_region\x18\x04 \x01(\tH\x03R\fdeviceRegion\x88\x01\x01\x12\"\n" +
	"\n" +
	"sponsor_id\x18\x05 \x01(\tH\x04R\tsponsorId\x88\x01\x01B\r\n" +
	"\v_client_asnB\x12\n" +
	"\x10_client_platformB\x10\n" +
	"\x0e_client_regionB\x10\n" +
	"\x0e_device_regionB\r\n" +
	"\v_sponsor_idBHZFgithub.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pb/psiphondb\x06proto3"

var (
	file_ca_psiphon_psiphond_dest_params_proto_rawDescOnce sync.Once
	file_ca_psiphon_psiphond_dest_params_proto_rawDescData []byte
)

func file_ca_psiphon_psiphond_dest_params_proto_rawDescGZIP() []byte {
	file_ca_psiphon_psiphond_dest_params_proto_rawDescOnce.Do(func() {
		file_ca_psiphon_psiphond_dest_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_dest_params_proto_rawDesc), len(file_ca_psiphon_psiphond_dest_params_proto_rawDesc)))
	})
	return file_ca_psiphon_psiphond_dest_params_proto_rawDescData
}

var file_ca_psiphon_psiphond_dest_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ca_psiphon_psiphond_dest_params_proto_goTypes = []any{
	(*DestParams)(nil), // 0: ca.psiphon.psiphond.DestParams
}
var file_ca_psiphon_psiphond_dest_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ca_psiphon_psiphond_dest_params_proto_init() }
func file_ca_psiphon_psiphond_dest_params_proto_init() {
	if File_ca_psiphon_psiphond_dest_params_proto != nil {
		return
	}
	file_ca_psiphon_psiphond_dest_params_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_dest_params_proto_rawDesc), len(file_ca_psiphon_psiphond_dest_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ca_psiphon_psiphond_dest_params_proto_goTypes,
		DependencyIndexes: file_ca_psiphon_psiphond_dest_params_proto_depIdxs,
		MessageInfos:      file_ca_psiphon_psiphond_dest_params_proto_msgTypes,
	}.Build()
	File_ca_psiphon_psiphond_dest_params_proto = out.File
	file_ca_psiphon_psiphond_dest_params_proto_goTypes = nil
	file_ca_psiphon_psiphond_dest_params_proto_depIdxs = nil
}
