// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ca.psiphon.psiphond/domain_bytes.proto

package psiphond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseParams    *BaseParams            `protobuf:"bytes,1,opt,name=base_params,json=baseParams,proto3,oneof" json:"base_params,omitempty"`
	Bytes         *int64                 `protobuf:"varint,100,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	Domain        *string                `protobuf:"bytes,101,opt,name=domain,proto3,oneof" json:"domain,omitempty"` //LowCardinality
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBytes) Reset() {
	*x = DomainBytes{}
	mi := &file_ca_psiphon_psiphond_domain_bytes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBytes) ProtoMessage() {}

func (x *DomainBytes) ProtoReflect() protoreflect.Message {
	mi := &file_ca_psiphon_psiphond_domain_bytes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBytes.ProtoReflect.Descriptor instead.
func (*DomainBytes) Descriptor() ([]byte, []int) {
	return file_ca_psiphon_psiphond_domain_bytes_proto_rawDescGZIP(), []int{0}
}

func (x *DomainBytes) GetBaseParams() *BaseParams {
	if x != nil {
		return x.BaseParams
	}
	return nil
}

func (x *DomainBytes) GetBytes() int64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *DomainBytes) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

var File_ca_psiphon_psiphond_domain_bytes_proto protoreflect.FileDescriptor

const file_ca_psiphon_psiphond_domain_bytes_proto_rawDesc = "" +
	"\n" +
	"&ca.psiphon.psiphond/domain_bytes.proto\x12\x13ca.psiphon.psiphond\x1a%ca.psiphon.psiphond/base_params.proto\"\xb1\x01\n" +
	"\vDomainBytes\x12E\n" +
	"\vbase_params\x18\x01 \x01(\v2\x1f.ca.psiphon.psiphond.BaseParamsH\x00R\n" +
	"baseParams\x88\x01\x01\x12\x19\n" +
	"\x05bytes\x18d \x01(\x03H\x01R\x05bytes\x88\x01\x01\x12\x1b\n" +
	"\x06domain\x18e \x01(\tH\x02R\x06domain\x88\x01\x01B\x0e\n" +
	"\f_base_paramsB\b\n" +
	"\x06_bytesB\t\n" +
	"\a_domainBHZFgithub.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pb/psiphondb\x06proto3"

var (
	file_ca_psiphon_psiphond_domain_bytes_proto_rawDescOnce sync.Once
	file_ca_psiphon_psiphond_domain_bytes_proto_rawDescData []byte
)

func file_ca_psiphon_psiphond_domain_bytes_proto_rawDescGZIP() []byte {
	file_ca_psiphon_psiphond_domain_bytes_proto_rawDescOnce.Do(func() {
		file_ca_psiphon_psiphond_domain_bytes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_domain_bytes_proto_rawDesc), len(file_ca_psiphon_psiphond_domain_bytes_proto_rawDesc)))
	})
	return file_ca_psiphon_psiphond_domain_bytes_proto_rawDescData
}

var file_ca_psiphon_psiphond_domain_bytes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ca_psiphon_psiphond_domain_bytes_proto_goTypes = []any{
	(*DomainBytes)(nil), // 0: ca.psiphon.psiphond.DomainBytes
	(*BaseParams)(nil),  // 1: ca.psiphon.psiphond.BaseParams
}
var file_ca_psiphon_psiphond_domain_bytes_proto_depIdxs = []int32{
	1, // 0: ca.psiphon.psiphond.DomainBytes.base_params:type_name -> ca.psiphon.psiphond.BaseParams
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ca_psiphon_psiphond_domain_bytes_proto_init() }
func file_ca_psiphon_psiphond_domain_bytes_proto_init() {
	if File_ca_psiphon_psiphond_domain_bytes_proto != nil {
		return
	}
	file_ca_psiphon_psiphond_base_params_proto_init()
	file_ca_psiphon_psiphond_domain_bytes_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_domain_bytes_proto_rawDesc), len(file_ca_psiphon_psiphond_domain_bytes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ca_psiphon_psiphond_domain_bytes_proto_goTypes,
		DependencyIndexes: file_ca_psiphon_psiphond_domain_bytes_proto_depIdxs,
		MessageInfos:      file_ca_psiphon_psiphond_domain_bytes_proto_msgTypes,
	}.Build()
	File_ca_psiphon_psiphond_domain_bytes_proto = out.File
	file_ca_psiphon_psiphond_domain_bytes_proto_goTypes = nil
	file_ca_psiphon_psiphond_domain_bytes_proto_depIdxs = nil
}
