// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ca.psiphon.psiphond/inproxy_dial_params.proto

package psiphond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InproxyDialParams struct {
	state                                            protoimpl.MessageState `protogen:"open.v1"`
	InproxyBrokerClientBpf                           *string                `protobuf:"bytes,1,opt,name=inproxy_broker_client_bpf,json=inproxyBrokerClientBpf,proto3,oneof" json:"inproxy_broker_client_bpf,omitempty"`       //LowCardinality
	InproxyBrokerDialAddress                         *string                `protobuf:"bytes,2,opt,name=inproxy_broker_dial_address,json=inproxyBrokerDialAddress,proto3,oneof" json:"inproxy_broker_dial_address,omitempty"` //LowCardinality
	InproxyBrokerDnsAttempt                          *int64                 `protobuf:"varint,3,opt,name=inproxy_broker_dns_attempt,json=inproxyBrokerDnsAttempt,proto3,oneof" json:"inproxy_broker_dns_attempt,omitempty"`
	InproxyBrokerDnsPreferred                        *string                `protobuf:"bytes,4,opt,name=inproxy_broker_dns_preferred,json=inproxyBrokerDnsPreferred,proto3,oneof" json:"inproxy_broker_dns_preferred,omitempty"`       //LowCardinality
	InproxyBrokerDnsPreresolved                      *string                `protobuf:"bytes,5,opt,name=inproxy_broker_dns_preresolved,json=inproxyBrokerDnsPreresolved,proto3,oneof" json:"inproxy_broker_dns_preresolved,omitempty"` //LowCardinality
	InproxyBrokerDnsQnameMismatches                  *int64                 `protobuf:"varint,6,opt,name=inproxy_broker_dns_qname_mismatches,json=inproxyBrokerDnsQnameMismatches,proto3,oneof" json:"inproxy_broker_dns_qname_mismatches,omitempty"`
	InproxyBrokerDnsQnameMustMatch                   *bool                  `protobuf:"varint,7,opt,name=inproxy_broker_dns_qname_must_match,json=inproxyBrokerDnsQnameMustMatch,proto3,oneof" json:"inproxy_broker_dns_qname_must_match,omitempty"`
	InproxyBrokerDnsQnameRandomCasing                *bool                  `protobuf:"varint,8,opt,name=inproxy_broker_dns_qname_random_casing,json=inproxyBrokerDnsQnameRandomCasing,proto3,oneof" json:"inproxy_broker_dns_qname_random_casing,omitempty"`
	InproxyBrokerDnsTransform                        *string                `protobuf:"bytes,9,opt,name=inproxy_broker_dns_transform,json=inproxyBrokerDnsTransform,proto3,oneof" json:"inproxy_broker_dns_transform,omitempty"` //LowCardinality
	InproxyBrokerDownstreamBytesFragmented           *int64                 `protobuf:"varint,10,opt,name=inproxy_broker_downstream_bytes_fragmented,json=inproxyBrokerDownstreamBytesFragmented,proto3,oneof" json:"inproxy_broker_downstream_bytes_fragmented,omitempty"`
	InproxyBrokerFrontingProviderId                  *string                `protobuf:"bytes,11,opt,name=inproxy_broker_fronting_provider_id,json=inproxyBrokerFrontingProviderId,proto3,oneof" json:"inproxy_broker_fronting_provider_id,omitempty"` //LowCardinality
	InproxyBrokerHostHeader                          *string                `protobuf:"bytes,12,opt,name=inproxy_broker_host_header,json=inproxyBrokerHostHeader,proto3,oneof" json:"inproxy_broker_host_header,omitempty"`                           //LowCardinality
	InproxyBrokerHttpTransform                       *string                `protobuf:"bytes,13,opt,name=inproxy_broker_http_transform,json=inproxyBrokerHttpTransform,proto3,oneof" json:"inproxy_broker_http_transform,omitempty"`                  //LowCardinality
	InproxyBrokerId                                  *string                `protobuf:"bytes,14,opt,name=inproxy_broker_id,json=inproxyBrokerId,proto3,oneof" json:"inproxy_broker_id,omitempty"`                                                     //LowCardinality
	InproxyBrokerIsReplay                            *bool                  `protobuf:"varint,15,opt,name=inproxy_broker_is_replay,json=inproxyBrokerIsReplay,proto3,oneof" json:"inproxy_broker_is_replay,omitempty"`
	InproxyBrokerIsReuse                             *bool                  `protobuf:"varint,16,opt,name=inproxy_broker_is_reuse,json=inproxyBrokerIsReuse,proto3,oneof" json:"inproxy_broker_is_reuse,omitempty"`
	InproxyBrokerResolvedIpAddress                   *string                `protobuf:"bytes,17,opt,name=inproxy_broker_resolved_ip_address,json=inproxyBrokerResolvedIpAddress,proto3,oneof" json:"inproxy_broker_resolved_ip_address,omitempty"` //LowCardinality
	InproxyBrokerSniServerName                       *string                `protobuf:"bytes,18,opt,name=inproxy_broker_sni_server_name,json=inproxyBrokerSniServerName,proto3,oneof" json:"inproxy_broker_sni_server_name,omitempty"`             //LowCardinality
	InproxyBrokerTlsFragmented                       *bool                  `protobuf:"varint,19,opt,name=inproxy_broker_tls_fragmented,json=inproxyBrokerTlsFragmented,proto3,oneof" json:"inproxy_broker_tls_fragmented,omitempty"`
	InproxyBrokerTlsProfile                          *string                `protobuf:"bytes,20,opt,name=inproxy_broker_tls_profile,json=inproxyBrokerTlsProfile,proto3,oneof" json:"inproxy_broker_tls_profile,omitempty"` //LowCardinality
	InproxyBrokerTlsVersion                          *string                `protobuf:"bytes,21,opt,name=inproxy_broker_tls_version,json=inproxyBrokerTlsVersion,proto3,oneof" json:"inproxy_broker_tls_version,omitempty"` //LowCardinality
	InproxyBrokerTransformedHostName                 *bool                  `protobuf:"varint,22,opt,name=inproxy_broker_transformed_host_name,json=inproxyBrokerTransformedHostName,proto3,oneof" json:"inproxy_broker_transformed_host_name,omitempty"`
	InproxyBrokerTransport                           *string                `protobuf:"bytes,23,opt,name=inproxy_broker_transport,json=inproxyBrokerTransport,proto3,oneof" json:"inproxy_broker_transport,omitempty"` //LowCardinality
	InproxyBrokerUpstreamBytesFragmented             *int64                 `protobuf:"varint,24,opt,name=inproxy_broker_upstream_bytes_fragmented,json=inproxyBrokerUpstreamBytesFragmented,proto3,oneof" json:"inproxy_broker_upstream_bytes_fragmented,omitempty"`
	InproxyBrokerUserAgent                           *string                `protobuf:"bytes,25,opt,name=inproxy_broker_user_agent,json=inproxyBrokerUserAgent,proto3,oneof" json:"inproxy_broker_user_agent,omitempty"`                  //LowCardinality
	InproxyClientNatType                             *string                `protobuf:"bytes,26,opt,name=inproxy_client_nat_type,json=inproxyClientNatType,proto3,oneof" json:"inproxy_client_nat_type,omitempty"`                        //LowCardinality
	InproxyClientPortMappingTypes                    []string               `protobuf:"bytes,27,rep,name=inproxy_client_port_mapping_types,json=inproxyClientPortMappingTypes,proto3" json:"inproxy_client_port_mapping_types,omitempty"` //LowCardinality
	InproxyConnectionId                              *string                `protobuf:"bytes,28,opt,name=inproxy_connection_id,json=inproxyConnectionId,proto3,oneof" json:"inproxy_connection_id,omitempty"`
	InproxyDialBrokerOfferDuration                   *int64                 `protobuf:"varint,29,opt,name=inproxy_dial_broker_offer_duration,json=inproxyDialBrokerOfferDuration,proto3,oneof" json:"inproxy_dial_broker_offer_duration,omitempty"`
	InproxyDialFailedAttemptsDuration                *int64                 `protobuf:"varint,30,opt,name=inproxy_dial_failed_attempts_duration,json=inproxyDialFailedAttemptsDuration,proto3,oneof" json:"inproxy_dial_failed_attempts_duration,omitempty"`
	InproxyDialNatDisoveryDuration                   *int64                 `protobuf:"varint,31,opt,name=inproxy_dial_nat_disovery_duration,json=inproxyDialNatDisoveryDuration,proto3,oneof" json:"inproxy_dial_nat_disovery_duration,omitempty"`
	InproxyDialWebrtcConnectionDuration              *int64                 `protobuf:"varint,32,opt,name=inproxy_dial_webrtc_connection_duration,json=inproxyDialWebrtcConnectionDuration,proto3,oneof" json:"inproxy_dial_webrtc_connection_duration,omitempty"`
	InproxyDialWebrtcIceGatheringDuration            *int64                 `protobuf:"varint,33,opt,name=inproxy_dial_webrtc_ice_gathering_duration,json=inproxyDialWebrtcIceGatheringDuration,proto3,oneof" json:"inproxy_dial_webrtc_ice_gathering_duration,omitempty"`
	InproxyMatchedCommonCompartments                 *bool                  `protobuf:"varint,34,opt,name=inproxy_matched_common_compartments,json=inproxyMatchedCommonCompartments,proto3,oneof" json:"inproxy_matched_common_compartments,omitempty"` //LowCardinality
	InproxyMatchedPersonalCompartments               *bool                  `protobuf:"varint,35,opt,name=inproxy_matched_personal_compartments,json=inproxyMatchedPersonalCompartments,proto3,oneof" json:"inproxy_matched_personal_compartments,omitempty"`
	InproxyProxyAppliedTacticsTag                    *string                `protobuf:"bytes,36,opt,name=inproxy_proxy_applied_tactics_tag,json=inproxyProxyAppliedTacticsTag,proto3,oneof" json:"inproxy_proxy_applied_tactics_tag,omitempty"` //LowCardinality
	InproxyProxyAsn                                  *string                `protobuf:"bytes,37,opt,name=inproxy_proxy_asn,json=inproxyProxyAsn,proto3,oneof" json:"inproxy_proxy_asn,omitempty"`                                               //LowCardinality
	InproxyProxyAso                                  *string                `protobuf:"bytes,38,opt,name=inproxy_proxy_aso,json=inproxyProxyAso,proto3,oneof" json:"inproxy_proxy_aso,omitempty"`                                               //LowCardinality
	InproxyProxyCity                                 *string                `protobuf:"bytes,39,opt,name=inproxy_proxy_city,json=inproxyProxyCity,proto3,oneof" json:"inproxy_proxy_city,omitempty"`                                            //LowCardinality
	InproxyProxyClientBuildRev                       *string                `protobuf:"bytes,40,opt,name=inproxy_proxy_client_build_rev,json=inproxyProxyClientBuildRev,proto3,oneof" json:"inproxy_proxy_client_build_rev,omitempty"`          //LowCardinality
	InproxyProxyClientPlatform                       *string                `protobuf:"bytes,41,opt,name=inproxy_proxy_client_platform,json=inproxyProxyClientPlatform,proto3,oneof" json:"inproxy_proxy_client_platform,omitempty"`            //LowCardinality
	InproxyProxyClientVersion                        *int64                 `protobuf:"varint,42,opt,name=inproxy_proxy_client_version,json=inproxyProxyClientVersion,proto3,oneof" json:"inproxy_proxy_client_version,omitempty"`              //LowCardinality
	InproxyProxyConnectedClients                     *int64                 `protobuf:"varint,43,opt,name=inproxy_proxy_connected_clients,json=inproxyProxyConnectedClients,proto3,oneof" json:"inproxy_proxy_connected_clients,omitempty"`
	InproxyProxyConnectingClients                    *int64                 `protobuf:"varint,44,opt,name=inproxy_proxy_connecting_clients,json=inproxyProxyConnectingClients,proto3,oneof" json:"inproxy_proxy_connecting_clients,omitempty"`
	InproxyProxyDeviceLocation                       *string                `protobuf:"bytes,45,opt,name=inproxy_proxy_device_location,json=inproxyProxyDeviceLocation,proto3,oneof" json:"inproxy_proxy_device_location,omitempty"`
	InproxyProxyDeviceRegion                         *string                `protobuf:"bytes,46,opt,name=inproxy_proxy_device_region,json=inproxyProxyDeviceRegion,proto3,oneof" json:"inproxy_proxy_device_region,omitempty"`                     //LowCardinality
	InproxyProxyFeatures                             *string                `protobuf:"bytes,47,opt,name=inproxy_proxy_features,json=inproxyProxyFeatures,proto3,oneof" json:"inproxy_proxy_features,omitempty"`                                   //LowCardinality
	InproxyProxyFrontingProviderId                   *string                `protobuf:"bytes,48,opt,name=inproxy_proxy_fronting_provider_id,json=inproxyProxyFrontingProviderId,proto3,oneof" json:"inproxy_proxy_fronting_provider_id,omitempty"` //LowCardinality
	InproxyProxyId                                   *string                `protobuf:"bytes,49,opt,name=inproxy_proxy_id,json=inproxyProxyId,proto3,oneof" json:"inproxy_proxy_id,omitempty"`
	InproxyProxyIsPriority                           *bool                  `protobuf:"varint,50,opt,name=inproxy_proxy_is_priority,json=inproxyProxyIsPriority,proto3,oneof" json:"inproxy_proxy_is_priority,omitempty"`
	InproxyProxyIsp                                  *string                `protobuf:"bytes,51,opt,name=inproxy_proxy_isp,json=inproxyProxyIsp,proto3,oneof" json:"inproxy_proxy_isp,omitempty"` //LowCardinality
	InproxyProxyLimitDownstreamBytesPerSecond        *int64                 `protobuf:"varint,52,opt,name=inproxy_proxy_limit_downstream_bytes_per_second,json=inproxyProxyLimitDownstreamBytesPerSecond,proto3,oneof" json:"inproxy_proxy_limit_downstream_bytes_per_second,omitempty"`
	InproxyProxyLimitUpstreamBytesPerSecond          *int64                 `protobuf:"varint,53,opt,name=inproxy_proxy_limit_upstream_bytes_per_second,json=inproxyProxyLimitUpstreamBytesPerSecond,proto3,oneof" json:"inproxy_proxy_limit_upstream_bytes_per_second,omitempty"`
	InproxyProxyMaxClients                           *int64                 `protobuf:"varint,54,opt,name=inproxy_proxy_max_clients,json=inproxyProxyMaxClients,proto3,oneof" json:"inproxy_proxy_max_clients,omitempty"`
	InproxyProxyNatType                              *string                `protobuf:"bytes,55,opt,name=inproxy_proxy_nat_type,json=inproxyProxyNatType,proto3,oneof" json:"inproxy_proxy_nat_type,omitempty"`             //LowCardinality
	InproxyProxyNetworkType                          *string                `protobuf:"bytes,56,opt,name=inproxy_proxy_network_type,json=inproxyProxyNetworkType,proto3,oneof" json:"inproxy_proxy_network_type,omitempty"` //LowCardinality
	InproxyProxyPeakDownstreamBytesPerSecond         *int64                 `protobuf:"varint,57,opt,name=inproxy_proxy_peak_downstream_bytes_per_second,json=inproxyProxyPeakDownstreamBytesPerSecond,proto3,oneof" json:"inproxy_proxy_peak_downstream_bytes_per_second,omitempty"`
	InproxyProxyPeakUpstreamBytesPerSecond           *int64                 `protobuf:"varint,58,opt,name=inproxy_proxy_peak_upstream_bytes_per_second,json=inproxyProxyPeakUpstreamBytesPerSecond,proto3,oneof" json:"inproxy_proxy_peak_upstream_bytes_per_second,omitempty"`
	InproxyProxyPortMappingTypes                     []string               `protobuf:"bytes,59,rep,name=inproxy_proxy_port_mapping_types,json=inproxyProxyPortMappingTypes,proto3" json:"inproxy_proxy_port_mapping_types,omitempty"`                   //LowCardinality
	InproxyProxyPropagationChannelId                 *string                `protobuf:"bytes,60,opt,name=inproxy_proxy_propagation_channel_id,json=inproxyProxyPropagationChannelId,proto3,oneof" json:"inproxy_proxy_propagation_channel_id,omitempty"` //LowCardinality
	InproxyProxyProtocolVersion                      *int64                 `protobuf:"varint,61,opt,name=inproxy_proxy_protocol_version,json=inproxyProxyProtocolVersion,proto3,oneof" json:"inproxy_proxy_protocol_version,omitempty"`
	InproxyProxyRegion                               *string                `protobuf:"bytes,62,opt,name=inproxy_proxy_region,json=inproxyProxyRegion,proto3,oneof" json:"inproxy_proxy_region,omitempty"` //LowCardinality
	InproxyProxySessionId                            *string                `protobuf:"bytes,63,opt,name=inproxy_proxy_session_id,json=inproxyProxySessionId,proto3,oneof" json:"inproxy_proxy_session_id,omitempty"`
	InproxyProxySponsorId                            *string                `protobuf:"bytes,64,opt,name=inproxy_proxy_sponsor_id,json=inproxyProxySponsorId,proto3,oneof" json:"inproxy_proxy_sponsor_id,omitempty"`                        //LowCardinality
	InproxyProxyStoredTacticsTag                     *string                `protobuf:"bytes,65,opt,name=inproxy_proxy_stored_tactics_tag,json=inproxyProxyStoredTacticsTag,proto3,oneof" json:"inproxy_proxy_stored_tactics_tag,omitempty"` //LowCardinality
	InproxyProxyClientFeatures                       []string               `protobuf:"bytes,66,rep,name=inproxy_proxy_client_features,json=inproxyProxyClientFeatures,proto3" json:"inproxy_proxy_client_features,omitempty"`               //LowCardinality
	InproxyWebrtcDecoyMessagesReceived               *int64                 `protobuf:"varint,67,opt,name=inproxy_webrtc_decoy_messages_received,json=inproxyWebrtcDecoyMessagesReceived,proto3,oneof" json:"inproxy_webrtc_decoy_messages_received,omitempty"`
	InproxyWebrtcDecoyMessagesSent                   *int64                 `protobuf:"varint,68,opt,name=inproxy_webrtc_decoy_messages_sent,json=inproxyWebrtcDecoyMessagesSent,proto3,oneof" json:"inproxy_webrtc_decoy_messages_sent,omitempty"`
	InproxyWebrtcDnsAttempt                          *int64                 `protobuf:"varint,69,opt,name=inproxy_webrtc_dns_attempt,json=inproxyWebrtcDnsAttempt,proto3,oneof" json:"inproxy_webrtc_dns_attempt,omitempty"`
	InproxyWebrtcDnsPreferred                        *string                `protobuf:"bytes,70,opt,name=inproxy_webrtc_dns_preferred,json=inproxyWebrtcDnsPreferred,proto3,oneof" json:"inproxy_webrtc_dns_preferred,omitempty"`       //LowCardinality
	InproxyWebrtcDnsPreresolved                      *string                `protobuf:"bytes,71,opt,name=inproxy_webrtc_dns_preresolved,json=inproxyWebrtcDnsPreresolved,proto3,oneof" json:"inproxy_webrtc_dns_preresolved,omitempty"` //LowCardinality
	InproxyWebrtcDnsQnameMismatches                  *int64                 `protobuf:"varint,72,opt,name=inproxy_webrtc_dns_qname_mismatches,json=inproxyWebrtcDnsQnameMismatches,proto3,oneof" json:"inproxy_webrtc_dns_qname_mismatches,omitempty"`
	InproxyWebrtcDnsQnameMustMatch                   *bool                  `protobuf:"varint,73,opt,name=inproxy_webrtc_dns_qname_must_match,json=inproxyWebrtcDnsQnameMustMatch,proto3,oneof" json:"inproxy_webrtc_dns_qname_must_match,omitempty"`
	InproxyWebrtcDnsQnameRandomCasing                *bool                  `protobuf:"varint,74,opt,name=inproxy_webrtc_dns_qname_random_casing,json=inproxyWebrtcDnsQnameRandomCasing,proto3,oneof" json:"inproxy_webrtc_dns_qname_random_casing,omitempty"`
	InproxyWebrtcDnsTransform                        *string                `protobuf:"bytes,75,opt,name=inproxy_webrtc_dns_transform,json=inproxyWebrtcDnsTransform,proto3,oneof" json:"inproxy_webrtc_dns_transform,omitempty"` //LowCardinality
	InproxyWebrtcLocalIceCandidateIs_IPv6            *bool                  `protobuf:"varint,76,opt,name=inproxy_webrtc_local_ice_candidate_is_IPv6,json=inproxyWebrtcLocalIceCandidateIsIPv6,proto3,oneof" json:"inproxy_webrtc_local_ice_candidate_is_IPv6,omitempty"`
	InproxyWebrtcLocalIceCandidateIsInitiator        *bool                  `protobuf:"varint,77,opt,name=inproxy_webrtc_local_ice_candidate_is_initiator,json=inproxyWebrtcLocalIceCandidateIsInitiator,proto3,oneof" json:"inproxy_webrtc_local_ice_candidate_is_initiator,omitempty"`
	InproxyWebrtcLocalIceCandidatePort               *int64                 `protobuf:"varint,78,opt,name=inproxy_webrtc_local_ice_candidate_port,json=inproxyWebrtcLocalIceCandidatePort,proto3,oneof" json:"inproxy_webrtc_local_ice_candidate_port,omitempty"`
	InproxyWebrtcLocalIceCandidateType               *string                `protobuf:"bytes,79,opt,name=inproxy_webrtc_local_ice_candidate_type,json=inproxyWebrtcLocalIceCandidateType,proto3,oneof" json:"inproxy_webrtc_local_ice_candidate_type,omitempty"` //LowCardinality
	InproxyWebrtcPaddedMessagesReceived              *int64                 `protobuf:"varint,80,opt,name=inproxy_webrtc_padded_messages_received,json=inproxyWebrtcPaddedMessagesReceived,proto3,oneof" json:"inproxy_webrtc_padded_messages_received,omitempty"`
	InproxyWebrtcPaddedMessagesSent                  *int64                 `protobuf:"varint,81,opt,name=inproxy_webrtc_padded_messages_sent,json=inproxyWebrtcPaddedMessagesSent,proto3,oneof" json:"inproxy_webrtc_padded_messages_sent,omitempty"`
	InproxyWebrtcRandomizeDtls                       *bool                  `protobuf:"varint,82,opt,name=inproxy_webrtc_randomize_dtls,json=inproxyWebrtcRandomizeDtls,proto3,oneof" json:"inproxy_webrtc_randomize_dtls,omitempty"`
	InproxyWebrtcRemoteIceCandidateIs_IPv6           *bool                  `protobuf:"varint,83,opt,name=inproxy_webrtc_remote_ice_candidate_is_IPv6,json=inproxyWebrtcRemoteIceCandidateIsIPv6,proto3,oneof" json:"inproxy_webrtc_remote_ice_candidate_is_IPv6,omitempty"`
	InproxyWebrtcRemoteIceCandidatePort              *int64                 `protobuf:"varint,84,opt,name=inproxy_webrtc_remote_ice_candidate_port,json=inproxyWebrtcRemoteIceCandidatePort,proto3,oneof" json:"inproxy_webrtc_remote_ice_candidate_port,omitempty"`
	InproxyWebrtcRemoteIceCandidateType              *string                `protobuf:"bytes,85,opt,name=inproxy_webrtc_remote_ice_candidate_type,json=inproxyWebrtcRemoteIceCandidateType,proto3,oneof" json:"inproxy_webrtc_remote_ice_candidate_type,omitempty"`                                         //LowCardinality
	InproxyWebrtcStunServer                          *string                `protobuf:"bytes,86,opt,name=inproxy_webrtc_stun_server,json=inproxyWebrtcStunServer,proto3,oneof" json:"inproxy_webrtc_stun_server,omitempty"`                                                                                 //LowCardinality
	InproxyWebrtcStunServer_RFC5780                  *string                `protobuf:"bytes,87,opt,name=inproxy_webrtc_stun_server_RFC5780,json=inproxyWebrtcStunServerRFC5780,proto3,oneof" json:"inproxy_webrtc_stun_server_RFC5780,omitempty"`                                                          //LowCardinality
	InproxyWebrtcStunServer_RFC5780ResolvedIpAddress *string                `protobuf:"bytes,88,opt,name=inproxy_webrtc_stun_server_RFC5780_resolved_ip_address,json=inproxyWebrtcStunServerRFC5780ResolvedIpAddress,proto3,oneof" json:"inproxy_webrtc_stun_server_RFC5780_resolved_ip_address,omitempty"` //LowCardinality
	InproxyWebrtcStunServerResolvedIpAddress         *string                `protobuf:"bytes,89,opt,name=inproxy_webrtc_stun_server_resolved_ip_address,json=inproxyWebrtcStunServerResolvedIpAddress,proto3,oneof" json:"inproxy_webrtc_stun_server_resolved_ip_address,omitempty"`                        //LowCardinality
	InproxyWebrtcUseMediaStreams                     *bool                  `protobuf:"varint,90,opt,name=inproxy_webrtc_use_media_streams,json=inproxyWebrtcUseMediaStreams,proto3,oneof" json:"inproxy_webrtc_use_media_streams,omitempty"`
	unknownFields                                    protoimpl.UnknownFields
	sizeCache                                        protoimpl.SizeCache
}

func (x *InproxyDialParams) Reset() {
	*x = InproxyDialParams{}
	mi := &file_ca_psiphon_psiphond_inproxy_dial_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InproxyDialParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InproxyDialParams) ProtoMessage() {}

func (x *InproxyDialParams) ProtoReflect() protoreflect.Message {
	mi := &file_ca_psiphon_psiphond_inproxy_dial_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InproxyDialParams.ProtoReflect.Descriptor instead.
func (*InproxyDialParams) Descriptor() ([]byte, []int) {
	return file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescGZIP(), []int{0}
}

func (x *InproxyDialParams) GetInproxyBrokerClientBpf() string {
	if x != nil && x.InproxyBrokerClientBpf != nil {
		return *x.InproxyBrokerClientBpf
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerDialAddress() string {
	if x != nil && x.InproxyBrokerDialAddress != nil {
		return *x.InproxyBrokerDialAddress
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerDnsAttempt() int64 {
	if x != nil && x.InproxyBrokerDnsAttempt != nil {
		return *x.InproxyBrokerDnsAttempt
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyBrokerDnsPreferred() string {
	if x != nil && x.InproxyBrokerDnsPreferred != nil {
		return *x.InproxyBrokerDnsPreferred
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerDnsPreresolved() string {
	if x != nil && x.InproxyBrokerDnsPreresolved != nil {
		return *x.InproxyBrokerDnsPreresolved
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerDnsQnameMismatches() int64 {
	if x != nil && x.InproxyBrokerDnsQnameMismatches != nil {
		return *x.InproxyBrokerDnsQnameMismatches
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyBrokerDnsQnameMustMatch() bool {
	if x != nil && x.InproxyBrokerDnsQnameMustMatch != nil {
		return *x.InproxyBrokerDnsQnameMustMatch
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerDnsQnameRandomCasing() bool {
	if x != nil && x.InproxyBrokerDnsQnameRandomCasing != nil {
		return *x.InproxyBrokerDnsQnameRandomCasing
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerDnsTransform() string {
	if x != nil && x.InproxyBrokerDnsTransform != nil {
		return *x.InproxyBrokerDnsTransform
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerDownstreamBytesFragmented() int64 {
	if x != nil && x.InproxyBrokerDownstreamBytesFragmented != nil {
		return *x.InproxyBrokerDownstreamBytesFragmented
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyBrokerFrontingProviderId() string {
	if x != nil && x.InproxyBrokerFrontingProviderId != nil {
		return *x.InproxyBrokerFrontingProviderId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerHostHeader() string {
	if x != nil && x.InproxyBrokerHostHeader != nil {
		return *x.InproxyBrokerHostHeader
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerHttpTransform() string {
	if x != nil && x.InproxyBrokerHttpTransform != nil {
		return *x.InproxyBrokerHttpTransform
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerId() string {
	if x != nil && x.InproxyBrokerId != nil {
		return *x.InproxyBrokerId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerIsReplay() bool {
	if x != nil && x.InproxyBrokerIsReplay != nil {
		return *x.InproxyBrokerIsReplay
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerIsReuse() bool {
	if x != nil && x.InproxyBrokerIsReuse != nil {
		return *x.InproxyBrokerIsReuse
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerResolvedIpAddress() string {
	if x != nil && x.InproxyBrokerResolvedIpAddress != nil {
		return *x.InproxyBrokerResolvedIpAddress
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerSniServerName() string {
	if x != nil && x.InproxyBrokerSniServerName != nil {
		return *x.InproxyBrokerSniServerName
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerTlsFragmented() bool {
	if x != nil && x.InproxyBrokerTlsFragmented != nil {
		return *x.InproxyBrokerTlsFragmented
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerTlsProfile() string {
	if x != nil && x.InproxyBrokerTlsProfile != nil {
		return *x.InproxyBrokerTlsProfile
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerTlsVersion() string {
	if x != nil && x.InproxyBrokerTlsVersion != nil {
		return *x.InproxyBrokerTlsVersion
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerTransformedHostName() bool {
	if x != nil && x.InproxyBrokerTransformedHostName != nil {
		return *x.InproxyBrokerTransformedHostName
	}
	return false
}

func (x *InproxyDialParams) GetInproxyBrokerTransport() string {
	if x != nil && x.InproxyBrokerTransport != nil {
		return *x.InproxyBrokerTransport
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyBrokerUpstreamBytesFragmented() int64 {
	if x != nil && x.InproxyBrokerUpstreamBytesFragmented != nil {
		return *x.InproxyBrokerUpstreamBytesFragmented
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyBrokerUserAgent() string {
	if x != nil && x.InproxyBrokerUserAgent != nil {
		return *x.InproxyBrokerUserAgent
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyClientNatType() string {
	if x != nil && x.InproxyClientNatType != nil {
		return *x.InproxyClientNatType
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyClientPortMappingTypes() []string {
	if x != nil {
		return x.InproxyClientPortMappingTypes
	}
	return nil
}

func (x *InproxyDialParams) GetInproxyConnectionId() string {
	if x != nil && x.InproxyConnectionId != nil {
		return *x.InproxyConnectionId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyDialBrokerOfferDuration() int64 {
	if x != nil && x.InproxyDialBrokerOfferDuration != nil {
		return *x.InproxyDialBrokerOfferDuration
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyDialFailedAttemptsDuration() int64 {
	if x != nil && x.InproxyDialFailedAttemptsDuration != nil {
		return *x.InproxyDialFailedAttemptsDuration
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyDialNatDisoveryDuration() int64 {
	if x != nil && x.InproxyDialNatDisoveryDuration != nil {
		return *x.InproxyDialNatDisoveryDuration
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyDialWebrtcConnectionDuration() int64 {
	if x != nil && x.InproxyDialWebrtcConnectionDuration != nil {
		return *x.InproxyDialWebrtcConnectionDuration
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyDialWebrtcIceGatheringDuration() int64 {
	if x != nil && x.InproxyDialWebrtcIceGatheringDuration != nil {
		return *x.InproxyDialWebrtcIceGatheringDuration
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyMatchedCommonCompartments() bool {
	if x != nil && x.InproxyMatchedCommonCompartments != nil {
		return *x.InproxyMatchedCommonCompartments
	}
	return false
}

func (x *InproxyDialParams) GetInproxyMatchedPersonalCompartments() bool {
	if x != nil && x.InproxyMatchedPersonalCompartments != nil {
		return *x.InproxyMatchedPersonalCompartments
	}
	return false
}

func (x *InproxyDialParams) GetInproxyProxyAppliedTacticsTag() string {
	if x != nil && x.InproxyProxyAppliedTacticsTag != nil {
		return *x.InproxyProxyAppliedTacticsTag
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyAsn() string {
	if x != nil && x.InproxyProxyAsn != nil {
		return *x.InproxyProxyAsn
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyAso() string {
	if x != nil && x.InproxyProxyAso != nil {
		return *x.InproxyProxyAso
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyCity() string {
	if x != nil && x.InproxyProxyCity != nil {
		return *x.InproxyProxyCity
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyClientBuildRev() string {
	if x != nil && x.InproxyProxyClientBuildRev != nil {
		return *x.InproxyProxyClientBuildRev
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyClientPlatform() string {
	if x != nil && x.InproxyProxyClientPlatform != nil {
		return *x.InproxyProxyClientPlatform
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyClientVersion() int64 {
	if x != nil && x.InproxyProxyClientVersion != nil {
		return *x.InproxyProxyClientVersion
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyConnectedClients() int64 {
	if x != nil && x.InproxyProxyConnectedClients != nil {
		return *x.InproxyProxyConnectedClients
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyConnectingClients() int64 {
	if x != nil && x.InproxyProxyConnectingClients != nil {
		return *x.InproxyProxyConnectingClients
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyDeviceLocation() string {
	if x != nil && x.InproxyProxyDeviceLocation != nil {
		return *x.InproxyProxyDeviceLocation
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyDeviceRegion() string {
	if x != nil && x.InproxyProxyDeviceRegion != nil {
		return *x.InproxyProxyDeviceRegion
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyFeatures() string {
	if x != nil && x.InproxyProxyFeatures != nil {
		return *x.InproxyProxyFeatures
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyFrontingProviderId() string {
	if x != nil && x.InproxyProxyFrontingProviderId != nil {
		return *x.InproxyProxyFrontingProviderId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyId() string {
	if x != nil && x.InproxyProxyId != nil {
		return *x.InproxyProxyId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyIsPriority() bool {
	if x != nil && x.InproxyProxyIsPriority != nil {
		return *x.InproxyProxyIsPriority
	}
	return false
}

func (x *InproxyDialParams) GetInproxyProxyIsp() string {
	if x != nil && x.InproxyProxyIsp != nil {
		return *x.InproxyProxyIsp
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyLimitDownstreamBytesPerSecond() int64 {
	if x != nil && x.InproxyProxyLimitDownstreamBytesPerSecond != nil {
		return *x.InproxyProxyLimitDownstreamBytesPerSecond
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyLimitUpstreamBytesPerSecond() int64 {
	if x != nil && x.InproxyProxyLimitUpstreamBytesPerSecond != nil {
		return *x.InproxyProxyLimitUpstreamBytesPerSecond
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyMaxClients() int64 {
	if x != nil && x.InproxyProxyMaxClients != nil {
		return *x.InproxyProxyMaxClients
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyNatType() string {
	if x != nil && x.InproxyProxyNatType != nil {
		return *x.InproxyProxyNatType
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyNetworkType() string {
	if x != nil && x.InproxyProxyNetworkType != nil {
		return *x.InproxyProxyNetworkType
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyPeakDownstreamBytesPerSecond() int64 {
	if x != nil && x.InproxyProxyPeakDownstreamBytesPerSecond != nil {
		return *x.InproxyProxyPeakDownstreamBytesPerSecond
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyPeakUpstreamBytesPerSecond() int64 {
	if x != nil && x.InproxyProxyPeakUpstreamBytesPerSecond != nil {
		return *x.InproxyProxyPeakUpstreamBytesPerSecond
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyPortMappingTypes() []string {
	if x != nil {
		return x.InproxyProxyPortMappingTypes
	}
	return nil
}

func (x *InproxyDialParams) GetInproxyProxyPropagationChannelId() string {
	if x != nil && x.InproxyProxyPropagationChannelId != nil {
		return *x.InproxyProxyPropagationChannelId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyProtocolVersion() int64 {
	if x != nil && x.InproxyProxyProtocolVersion != nil {
		return *x.InproxyProxyProtocolVersion
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyProxyRegion() string {
	if x != nil && x.InproxyProxyRegion != nil {
		return *x.InproxyProxyRegion
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxySessionId() string {
	if x != nil && x.InproxyProxySessionId != nil {
		return *x.InproxyProxySessionId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxySponsorId() string {
	if x != nil && x.InproxyProxySponsorId != nil {
		return *x.InproxyProxySponsorId
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyStoredTacticsTag() string {
	if x != nil && x.InproxyProxyStoredTacticsTag != nil {
		return *x.InproxyProxyStoredTacticsTag
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyProxyClientFeatures() []string {
	if x != nil {
		return x.InproxyProxyClientFeatures
	}
	return nil
}

func (x *InproxyDialParams) GetInproxyWebrtcDecoyMessagesReceived() int64 {
	if x != nil && x.InproxyWebrtcDecoyMessagesReceived != nil {
		return *x.InproxyWebrtcDecoyMessagesReceived
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcDecoyMessagesSent() int64 {
	if x != nil && x.InproxyWebrtcDecoyMessagesSent != nil {
		return *x.InproxyWebrtcDecoyMessagesSent
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsAttempt() int64 {
	if x != nil && x.InproxyWebrtcDnsAttempt != nil {
		return *x.InproxyWebrtcDnsAttempt
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsPreferred() string {
	if x != nil && x.InproxyWebrtcDnsPreferred != nil {
		return *x.InproxyWebrtcDnsPreferred
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsPreresolved() string {
	if x != nil && x.InproxyWebrtcDnsPreresolved != nil {
		return *x.InproxyWebrtcDnsPreresolved
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsQnameMismatches() int64 {
	if x != nil && x.InproxyWebrtcDnsQnameMismatches != nil {
		return *x.InproxyWebrtcDnsQnameMismatches
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsQnameMustMatch() bool {
	if x != nil && x.InproxyWebrtcDnsQnameMustMatch != nil {
		return *x.InproxyWebrtcDnsQnameMustMatch
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsQnameRandomCasing() bool {
	if x != nil && x.InproxyWebrtcDnsQnameRandomCasing != nil {
		return *x.InproxyWebrtcDnsQnameRandomCasing
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcDnsTransform() string {
	if x != nil && x.InproxyWebrtcDnsTransform != nil {
		return *x.InproxyWebrtcDnsTransform
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcLocalIceCandidateIs_IPv6() bool {
	if x != nil && x.InproxyWebrtcLocalIceCandidateIs_IPv6 != nil {
		return *x.InproxyWebrtcLocalIceCandidateIs_IPv6
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcLocalIceCandidateIsInitiator() bool {
	if x != nil && x.InproxyWebrtcLocalIceCandidateIsInitiator != nil {
		return *x.InproxyWebrtcLocalIceCandidateIsInitiator
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcLocalIceCandidatePort() int64 {
	if x != nil && x.InproxyWebrtcLocalIceCandidatePort != nil {
		return *x.InproxyWebrtcLocalIceCandidatePort
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcLocalIceCandidateType() string {
	if x != nil && x.InproxyWebrtcLocalIceCandidateType != nil {
		return *x.InproxyWebrtcLocalIceCandidateType
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcPaddedMessagesReceived() int64 {
	if x != nil && x.InproxyWebrtcPaddedMessagesReceived != nil {
		return *x.InproxyWebrtcPaddedMessagesReceived
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcPaddedMessagesSent() int64 {
	if x != nil && x.InproxyWebrtcPaddedMessagesSent != nil {
		return *x.InproxyWebrtcPaddedMessagesSent
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcRandomizeDtls() bool {
	if x != nil && x.InproxyWebrtcRandomizeDtls != nil {
		return *x.InproxyWebrtcRandomizeDtls
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcRemoteIceCandidateIs_IPv6() bool {
	if x != nil && x.InproxyWebrtcRemoteIceCandidateIs_IPv6 != nil {
		return *x.InproxyWebrtcRemoteIceCandidateIs_IPv6
	}
	return false
}

func (x *InproxyDialParams) GetInproxyWebrtcRemoteIceCandidatePort() int64 {
	if x != nil && x.InproxyWebrtcRemoteIceCandidatePort != nil {
		return *x.InproxyWebrtcRemoteIceCandidatePort
	}
	return 0
}

func (x *InproxyDialParams) GetInproxyWebrtcRemoteIceCandidateType() string {
	if x != nil && x.InproxyWebrtcRemoteIceCandidateType != nil {
		return *x.InproxyWebrtcRemoteIceCandidateType
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcStunServer() string {
	if x != nil && x.InproxyWebrtcStunServer != nil {
		return *x.InproxyWebrtcStunServer
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcStunServer_RFC5780() string {
	if x != nil && x.InproxyWebrtcStunServer_RFC5780 != nil {
		return *x.InproxyWebrtcStunServer_RFC5780
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcStunServer_RFC5780ResolvedIpAddress() string {
	if x != nil && x.InproxyWebrtcStunServer_RFC5780ResolvedIpAddress != nil {
		return *x.InproxyWebrtcStunServer_RFC5780ResolvedIpAddress
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcStunServerResolvedIpAddress() string {
	if x != nil && x.InproxyWebrtcStunServerResolvedIpAddress != nil {
		return *x.InproxyWebrtcStunServerResolvedIpAddress
	}
	return ""
}

func (x *InproxyDialParams) GetInproxyWebrtcUseMediaStreams() bool {
	if x != nil && x.InproxyWebrtcUseMediaStreams != nil {
		return *x.InproxyWebrtcUseMediaStreams
	}
	return false
}

var File_ca_psiphon_psiphond_inproxy_dial_params_proto protoreflect.FileDescriptor

const file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDesc = "" +
	"\n" +
	"-ca.psiphon.psiphond/inproxy_dial_params.proto\x12\x13ca.psiphon.psiphond\"\xc7N\n" +
	"\x11InproxyDialParams\x12>\n" +
	"\x19inproxy_broker_client_bpf\x18\x01 \x01(\tH\x00R\x16inproxyBrokerClientBpf\x88\x01\x01\x12B\n" +
	"\x1binproxy_broker_dial_address\x18\x02 \x01(\tH\x01R\x18inproxyBrokerDialAddress\x88\x01\x01\x12@\n" +
	"\x1ainproxy_broker_dns_attempt\x18\x03 \x01(\x03H\x02R\x17inproxyBrokerDnsAttempt\x88\x01\x01\x12D\n" +
	"\x1cinproxy_broker_dns_preferred\x18\x04 \x01(\tH\x03R\x19inproxyBrokerDnsPreferred\x88\x01\x01\x12H\n" +
	"\x1einproxy_broker_dns_preresolved\x18\x05 \x01(\tH\x04R\x1binproxyBrokerDnsPreresolved\x88\x01\x01\x12Q\n" +
	"#inproxy_broker_dns_qname_mismatches\x18\x06 \x01(\x03H\x05R\x1finproxyBrokerDnsQnameMismatches\x88\x01\x01\x12P\n" +
	"#inproxy_broker_dns_qname_must_match\x18\a \x01(\bH\x06R\x1einproxyBrokerDnsQnameMustMatch\x88\x01\x01\x12V\n" +
	"&inproxy_broker_dns_qname_random_casing\x18\b \x01(\bH\aR!inproxyBrokerDnsQnameRandomCasing\x88\x01\x01\x12D\n" +
	"\x1cinproxy_broker_dns_transform\x18\t \x01(\tH\bR\x19inproxyBrokerDnsTransform\x88\x01\x01\x12_\n" +
	"*inproxy_broker_downstream_bytes_fragmented\x18\n" +
	" \x01(\x03H\tR&inproxyBrokerDownstreamBytesFragmented\x88\x01\x01\x12Q\n" +
	"#inproxy_broker_fronting_provider_id\x18\v \x01(\tH\n" +
	"R\x1finproxyBrokerFrontingProviderId\x88\x01\x01\x12@\n" +
	"\x1ainproxy_broker_host_header\x18\f \x01(\tH\vR\x17inproxyBrokerHostHeader\x88\x01\x01\x12F\n" +
	"\x1dinproxy_broker_http_transform\x18\r \x01(\tH\fR\x1ainproxyBrokerHttpTransform\x88\x01\x01\x12/\n" +
	"\x11inproxy_broker_id\x18\x0e \x01(\tH\rR\x0finproxyBrokerId\x88\x01\x01\x12<\n" +
	"\x18inproxy_broker_is_replay\x18\x0f \x01(\bH\x0eR\x15inproxyBrokerIsReplay\x88\x01\x01\x12:\n" +
	"\x17inproxy_broker_is_reuse\x18\x10 \x01(\bH\x0fR\x14inproxyBrokerIsReuse\x88\x01\x01\x12O\n" +
	"\"inproxy_broker_resolved_ip_address\x18\x11 \x01(\tH\x10R\x1einproxyBrokerResolvedIpAddress\x88\x01\x01\x12G\n" +
	"\x1einproxy_broker_sni_server_name\x18\x12 \x01(\tH\x11R\x1ainproxyBrokerSniServerName\x88\x01\x01\x12F\n" +
	"\x1dinproxy_broker_tls_fragmented\x18\x13 \x01(\bH\x12R\x1ainproxyBrokerTlsFragmented\x88\x01\x01\x12@\n" +
	"\x1ainproxy_broker_tls_profile\x18\x14 \x01(\tH\x13R\x17inproxyBrokerTlsProfile\x88\x01\x01\x12@\n" +
	"\x1ainproxy_broker_tls_version\x18\x15 \x01(\tH\x14R\x17inproxyBrokerTlsVersion\x88\x01\x01\x12S\n" +
	"$inproxy_broker_transformed_host_name\x18\x16 \x01(\bH\x15R inproxyBrokerTransformedHostName\x88\x01\x01\x12=\n" +
	"\x18inproxy_broker_transport\x18\x17 \x01(\tH\x16R\x16inproxyBrokerTransport\x88\x01\x01\x12[\n" +
	"(inproxy_broker_upstream_bytes_fragmented\x18\x18 \x01(\x03H\x17R$inproxyBrokerUpstreamBytesFragmented\x88\x01\x01\x12>\n" +
	"\x19inproxy_broker_user_agent\x18\x19 \x01(\tH\x18R\x16inproxyBrokerUserAgent\x88\x01\x01\x12:\n" +
	"\x17inproxy_client_nat_type\x18\x1a \x01(\tH\x19R\x14inproxyClientNatType\x88\x01\x01\x12H\n" +
	"!inproxy_client_port_mapping_types\x18\x1b \x03(\tR\x1dinproxyClientPortMappingTypes\x127\n" +
	"\x15inproxy_connection_id\x18\x1c \x01(\tH\x1aR\x13inproxyConnectionId\x88\x01\x01\x12O\n" +
	"\"inproxy_dial_broker_offer_duration\x18\x1d \x01(\x03H\x1bR\x1einproxyDialBrokerOfferDuration\x88\x01\x01\x12U\n" +
	"%inproxy_dial_failed_attempts_duration\x18\x1e \x01(\x03H\x1cR!inproxyDialFailedAttemptsDuration\x88\x01\x01\x12O\n" +
	"\"inproxy_dial_nat_disovery_duration\x18\x1f \x01(\x03H\x1dR\x1einproxyDialNatDisoveryDuration\x88\x01\x01\x12Y\n" +
	"'inproxy_dial_webrtc_connection_duration\x18  \x01(\x03H\x1eR#inproxyDialWebrtcConnectionDuration\x88\x01\x01\x12^\n" +
	"*inproxy_dial_webrtc_ice_gathering_duration\x18! \x01(\x03H\x1fR%inproxyDialWebrtcIceGatheringDuration\x88\x01\x01\x12R\n" +
	"#inproxy_matched_common_compartments\x18\" \x01(\bH R inproxyMatchedCommonCompartments\x88\x01\x01\x12V\n" +
	"%inproxy_matched_personal_compartments\x18# \x01(\bH!R\"inproxyMatchedPersonalCompartments\x88\x01\x01\x12M\n" +
	"!inproxy_proxy_applied_tactics_tag\x18$ \x01(\tH\"R\x1dinproxyProxyAppliedTacticsTag\x88\x01\x01\x12/\n" +
	"\x11inproxy_proxy_asn\x18% \x01(\tH#R\x0finproxyProxyAsn\x88\x01\x01\x12/\n" +
	"\x11inproxy_proxy_aso\x18& \x01(\tH$R\x0finproxyProxyAso\x88\x01\x01\x121\n" +
	"\x12inproxy_proxy_city\x18' \x01(\tH%R\x10inproxyProxyCity\x88\x01\x01\x12G\n" +
	"\x1einproxy_proxy_client_build_rev\x18( \x01(\tH&R\x1ainproxyProxyClientBuildRev\x88\x01\x01\x12F\n" +
	"\x1dinproxy_proxy_client_platform\x18) \x01(\tH'R\x1ainproxyProxyClientPlatform\x88\x01\x01\x12D\n" +
	"\x1cinproxy_proxy_client_version\x18* \x01(\x03H(R\x19inproxyProxyClientVersion\x88\x01\x01\x12J\n" +
	"\x1finproxy_proxy_connected_clients\x18+ \x01(\x03H)R\x1cinproxyProxyConnectedClients\x88\x01\x01\x12L\n" +
	" inproxy_proxy_connecting_clients\x18, \x01(\x03H*R\x1dinproxyProxyConnectingClients\x88\x01\x01\x12F\n" +
	"\x1dinproxy_proxy_device_location\x18- \x01(\tH+R\x1ainproxyProxyDeviceLocation\x88\x01\x01\x12B\n" +
	"\x1binproxy_proxy_device_region\x18. \x01(\tH,R\x18inproxyProxyDeviceRegion\x88\x01\x01\x129\n" +
	"\x16inproxy_proxy_features\x18/ \x01(\tH-R\x14inproxyProxyFeatures\x88\x01\x01\x12O\n" +
	"\"inproxy_proxy_fronting_provider_id\x180 \x01(\tH.R\x1einproxyProxyFrontingProviderId\x88\x01\x01\x12-\n" +
	"\x10inproxy_proxy_id\x181 \x01(\tH/R\x0einproxyProxyId\x88\x01\x01\x12>\n" +
	"\x19inproxy_proxy_is_priority\x182 \x01(\bH0R\x16inproxyProxyIsPriority\x88\x01\x01\x12/\n" +
	"\x11inproxy_proxy_isp\x183 \x01(\tH1R\x0finproxyProxyIsp\x88\x01\x01\x12g\n" +
	"/inproxy_proxy_limit_downstream_bytes_per_second\x184 \x01(\x03H2R)inproxyProxyLimitDownstreamBytesPerSecond\x88\x01\x01\x12c\n" +
	"-inproxy_proxy_limit_upstream_bytes_per_second\x185 \x01(\x03H3R'inproxyProxyLimitUpstreamBytesPerSecond\x88\x01\x01\x12>\n" +
	"\x19inproxy_proxy_max_clients\x186 \x01(\x03H4R\x16inproxyProxyMaxClients\x88\x01\x01\x128\n" +
	"\x16inproxy_proxy_nat_type\x187 \x01(\tH5R\x13inproxyProxyNatType\x88\x01\x01\x12@\n" +
	"\x1ainproxy_proxy_network_type\x188 \x01(\tH6R\x17inproxyProxyNetworkType\x88\x01\x01\x12e\n" +
	".inproxy_proxy_peak_downstream_bytes_per_second\x189 \x01(\x03H7R(inproxyProxyPeakDownstreamBytesPerSecond\x88\x01\x01\x12a\n" +
	",inproxy_proxy_peak_upstream_bytes_per_second\x18: \x01(\x03H8R&inproxyProxyPeakUpstreamBytesPerSecond\x88\x01\x01\x12F\n" +
	" inproxy_proxy_port_mapping_types\x18; \x03(\tR\x1cinproxyProxyPortMappingTypes\x12S\n" +
	"$inproxy_proxy_propagation_channel_id\x18< \x01(\tH9R inproxyProxyPropagationChannelId\x88\x01\x01\x12H\n" +
	"\x1einproxy_proxy_protocol_version\x18= \x01(\x03H:R\x1binproxyProxyProtocolVersion\x88\x01\x01\x125\n" +
	"\x14inproxy_proxy_region\x18> \x01(\tH;R\x12inproxyProxyRegion\x88\x01\x01\x12<\n" +
	"\x18inproxy_proxy_session_id\x18? \x01(\tH<R\x15inproxyProxySessionId\x88\x01\x01\x12<\n" +
	"\x18inproxy_proxy_sponsor_id\x18@ \x01(\tH=R\x15inproxyProxySponsorId\x88\x01\x01\x12K\n" +
	" inproxy_proxy_stored_tactics_tag\x18A \x01(\tH>R\x1cinproxyProxyStoredTacticsTag\x88\x01\x01\x12A\n" +
	"\x1dinproxy_proxy_client_features\x18B \x03(\tR\x1ainproxyProxyClientFeatures\x12W\n" +
	"&inproxy_webrtc_decoy_messages_received\x18C \x01(\x03H?R\"inproxyWebrtcDecoyMessagesReceived\x88\x01\x01\x12O\n" +
	"\"inproxy_webrtc_decoy_messages_sent\x18D \x01(\x03H@R\x1einproxyWebrtcDecoyMessagesSent\x88\x01\x01\x12@\n" +
	"\x1ainproxy_webrtc_dns_attempt\x18E \x01(\x03HAR\x17inproxyWebrtcDnsAttempt\x88\x01\x01\x12D\n" +
	"\x1cinproxy_webrtc_dns_preferred\x18F \x01(\tHBR\x19inproxyWebrtcDnsPreferred\x88\x01\x01\x12H\n" +
	"\x1einproxy_webrtc_dns_preresolved\x18G \x01(\tHCR\x1binproxyWebrtcDnsPreresolved\x88\x01\x01\x12Q\n" +
	"#inproxy_webrtc_dns_qname_mismatches\x18H \x01(\x03HDR\x1finproxyWebrtcDnsQnameMismatches\x88\x01\x01\x12P\n" +
	"#inproxy_webrtc_dns_qname_must_match\x18I \x01(\bHER\x1einproxyWebrtcDnsQnameMustMatch\x88\x01\x01\x12V\n" +
	"&inproxy_webrtc_dns_qname_random_casing\x18J \x01(\bHFR!inproxyWebrtcDnsQnameRandomCasing\x88\x01\x01\x12D\n" +
	"\x1cinproxy_webrtc_dns_transform\x18K \x01(\tHGR\x19inproxyWebrtcDnsTransform\x88\x01\x01\x12]\n" +
	"*inproxy_webrtc_local_ice_candidate_is_IPv6\x18L \x01(\bHHR$inproxyWebrtcLocalIceCandidateIsIPv6\x88\x01\x01\x12g\n" +
	"/inproxy_webrtc_local_ice_candidate_is_initiator\x18M \x01(\bHIR)inproxyWebrtcLocalIceCandidateIsInitiator\x88\x01\x01\x12X\n" +
	"'inproxy_webrtc_local_ice_candidate_port\x18N \x01(\x03HJR\"inproxyWebrtcLocalIceCandidatePort\x88\x01\x01\x12X\n" +
	"'inproxy_webrtc_local_ice_candidate_type\x18O \x01(\tHKR\"inproxyWebrtcLocalIceCandidateType\x88\x01\x01\x12Y\n" +
	"'inproxy_webrtc_padded_messages_received\x18P \x01(\x03HLR#inproxyWebrtcPaddedMessagesReceived\x88\x01\x01\x12Q\n" +
	"#inproxy_webrtc_padded_messages_sent\x18Q \x01(\x03HMR\x1finproxyWebrtcPaddedMessagesSent\x88\x01\x01\x12F\n" +
	"\x1dinproxy_webrtc_randomize_dtls\x18R \x01(\bHNR\x1ainproxyWebrtcRandomizeDtls\x88\x01\x01\x12_\n" +
	"+inproxy_webrtc_remote_ice_candidate_is_IPv6\x18S \x01(\bHOR%inproxyWebrtcRemoteIceCandidateIsIPv6\x88\x01\x01\x12Z\n" +
	"(inproxy_webrtc_remote_ice_candidate_port\x18T \x01(\x03HPR#inproxyWebrtcRemoteIceCandidatePort\x88\x01\x01\x12Z\n" +
	"(inproxy_webrtc_remote_ice_candidate_type\x18U \x01(\tHQR#inproxyWebrtcRemoteIceCandidateType\x88\x01\x01\x12@\n" +
	"\x1ainproxy_webrtc_stun_server\x18V \x01(\tHRR\x17inproxyWebrtcStunServer\x88\x01\x01\x12O\n" +
	"\"inproxy_webrtc_stun_server_RFC5780\x18W \x01(\tHSR\x1einproxyWebrtcStunServerRFC5780\x88\x01\x01\x12t\n" +
	"6inproxy_webrtc_stun_server_RFC5780_resolved_ip_address\x18X \x01(\tHTR/inproxyWebrtcStunServerRFC5780ResolvedIpAddress\x88\x01\x01\x12e\n" +
	".inproxy_webrtc_stun_server_resolved_ip_address\x18Y \x01(\tHUR(inproxyWebrtcStunServerResolvedIpAddress\x88\x01\x01\x12K\n" +
	" inproxy_webrtc_use_media_streams\x18Z \x01(\bHVR\x1cinproxyWebrtcUseMediaStreams\x88\x01\x01B\x1c\n" +
	"\x1a_inproxy_broker_client_bpfB\x1e\n" +
	"\x1c_inproxy_broker_dial_addressB\x1d\n" +
	"\x1b_inproxy_broker_dns_attemptB\x1f\n" +
	"\x1d_inproxy_broker_dns_preferredB!\n" +
	"\x1f_inproxy_broker_dns_preresolvedB&\n" +
	"$_inproxy_broker_dns_qname_mismatchesB&\n" +
	"$_inproxy_broker_dns_qname_must_matchB)\n" +
	"'_inproxy_broker_dns_qname_random_casingB\x1f\n" +
	"\x1d_inproxy_broker_dns_transformB-\n" +
	"+_inproxy_broker_downstream_bytes_fragmentedB&\n" +
	"$_inproxy_broker_fronting_provider_idB\x1d\n" +
	"\x1b_inproxy_broker_host_headerB \n" +
	"\x1e_inproxy_broker_http_transformB\x14\n" +
	"\x12_inproxy_broker_idB\x1b\n" +
	"\x19_inproxy_broker_is_replayB\x1a\n" +
	"\x18_inproxy_broker_is_reuseB%\n" +
	"#_inproxy_broker_resolved_ip_addressB!\n" +
	"\x1f_inproxy_broker_sni_server_nameB \n" +
	"\x1e_inproxy_broker_tls_fragmentedB\x1d\n" +
	"\x1b_inproxy_broker_tls_profileB\x1d\n" +
	"\x1b_inproxy_broker_tls_versionB'\n" +
	"%_inproxy_broker_transformed_host_nameB\x1b\n" +
	"\x19_inproxy_broker_transportB+\n" +
	")_inproxy_broker_upstream_bytes_fragmentedB\x1c\n" +
	"\x1a_inproxy_broker_user_agentB\x1a\n" +
	"\x18_inproxy_client_nat_typeB\x18\n" +
	"\x16_inproxy_connection_idB%\n" +
	"#_inproxy_dial_broker_offer_durationB(\n" +
	"&_inproxy_dial_failed_attempts_durationB%\n" +
	"#_inproxy_dial_nat_disovery_durationB*\n" +
	"(_inproxy_dial_webrtc_connection_durationB-\n" +
	"+_inproxy_dial_webrtc_ice_gathering_durationB&\n" +
	"$_inproxy_matched_common_compartmentsB(\n" +
	"&_inproxy_matched_personal_compartmentsB$\n" +
	"\"_inproxy_proxy_applied_tactics_tagB\x14\n" +
	"\x12_inproxy_proxy_asnB\x14\n" +
	"\x12_inproxy_proxy_asoB\x15\n" +
	"\x13_inproxy_proxy_cityB!\n" +
	"\x1f_inproxy_proxy_client_build_revB \n" +
	"\x1e_inproxy_proxy_client_platformB\x1f\n" +
	"\x1d_inproxy_proxy_client_versionB\"\n" +
	" _inproxy_proxy_connected_clientsB#\n" +
	"!_inproxy_proxy_connecting_clientsB \n" +
	"\x1e_inproxy_proxy_device_locationB\x1e\n" +
	"\x1c_inproxy_proxy_device_regionB\x19\n" +
	"\x17_inproxy_proxy_featuresB%\n" +
	"#_inproxy_proxy_fronting_provider_idB\x13\n" +
	"\x11_inproxy_proxy_idB\x1c\n" +
	"\x1a_inproxy_proxy_is_priorityB\x14\n" +
	"\x12_inproxy_proxy_ispB2\n" +
	"0_inproxy_proxy_limit_downstream_bytes_per_secondB0\n" +
	"._inproxy_proxy_limit_upstream_bytes_per_secondB\x1c\n" +
	"\x1a_inproxy_proxy_max_clientsB\x19\n" +
	"\x17_inproxy_proxy_nat_typeB\x1d\n" +
	"\x1b_inproxy_proxy_network_typeB1\n" +
	"/_inproxy_proxy_peak_downstream_bytes_per_secondB/\n" +
	"-_inproxy_proxy_peak_upstream_bytes_per_secondB'\n" +
	"%_inproxy_proxy_propagation_channel_idB!\n" +
	"\x1f_inproxy_proxy_protocol_versionB\x17\n" +
	"\x15_inproxy_proxy_regionB\x1b\n" +
	"\x19_inproxy_proxy_session_idB\x1b\n" +
	"\x19_inproxy_proxy_sponsor_idB#\n" +
	"!_inproxy_proxy_stored_tactics_tagB)\n" +
	"'_inproxy_webrtc_decoy_messages_receivedB%\n" +
	"#_inproxy_webrtc_decoy_messages_sentB\x1d\n" +
	"\x1b_inproxy_webrtc_dns_attemptB\x1f\n" +
	"\x1d_inproxy_webrtc_dns_preferredB!\n" +
	"\x1f_inproxy_webrtc_dns_preresolvedB&\n" +
	"$_inproxy_webrtc_dns_qname_mismatchesB&\n" +
	"$_inproxy_webrtc_dns_qname_must_matchB)\n" +
	"'_inproxy_webrtc_dns_qname_random_casingB\x1f\n" +
	"\x1d_inproxy_webrtc_dns_transformB-\n" +
	"+_inproxy_webrtc_local_ice_candidate_is_IPv6B2\n" +
	"0_inproxy_webrtc_local_ice_candidate_is_initiatorB*\n" +
	"(_inproxy_webrtc_local_ice_candidate_portB*\n" +
	"(_inproxy_webrtc_local_ice_candidate_typeB*\n" +
	"(_inproxy_webrtc_padded_messages_receivedB&\n" +
	"$_inproxy_webrtc_padded_messages_sentB \n" +
	"\x1e_inproxy_webrtc_randomize_dtlsB.\n" +
	",_inproxy_webrtc_remote_ice_candidate_is_IPv6B+\n" +
	")_inproxy_webrtc_remote_ice_candidate_portB+\n" +
	")_inproxy_webrtc_remote_ice_candidate_typeB\x1d\n" +
	"\x1b_inproxy_webrtc_stun_serverB%\n" +
	"#_inproxy_webrtc_stun_server_RFC5780B9\n" +
	"7_inproxy_webrtc_stun_server_RFC5780_resolved_ip_addressB1\n" +
	"/_inproxy_webrtc_stun_server_resolved_ip_addressB#\n" +
	"!_inproxy_webrtc_use_media_streamsBHZFgithub.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pb/psiphondb\x06proto3"

var (
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescOnce sync.Once
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescData []byte
)

func file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescGZIP() []byte {
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescOnce.Do(func() {
		file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDesc), len(file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDesc)))
	})
	return file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDescData
}

var file_ca_psiphon_psiphond_inproxy_dial_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ca_psiphon_psiphond_inproxy_dial_params_proto_goTypes = []any{
	(*InproxyDialParams)(nil), // 0: ca.psiphon.psiphond.InproxyDialParams
}
var file_ca_psiphon_psiphond_inproxy_dial_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ca_psiphon_psiphond_inproxy_dial_params_proto_init() }
func file_ca_psiphon_psiphond_inproxy_dial_params_proto_init() {
	if File_ca_psiphon_psiphond_inproxy_dial_params_proto != nil {
		return
	}
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDesc), len(file_ca_psiphon_psiphond_inproxy_dial_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ca_psiphon_psiphond_inproxy_dial_params_proto_goTypes,
		DependencyIndexes: file_ca_psiphon_psiphond_inproxy_dial_params_proto_depIdxs,
		MessageInfos:      file_ca_psiphon_psiphond_inproxy_dial_params_proto_msgTypes,
	}.Build()
	File_ca_psiphon_psiphond_inproxy_dial_params_proto = out.File
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_goTypes = nil
	file_ca_psiphon_psiphond_inproxy_dial_params_proto_depIdxs = nil
}
