// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ca.psiphon.psiphond/remote_server_list.proto

package psiphond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteServerList struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BaseParams              *BaseParams            `protobuf:"bytes,1,opt,name=base_params,json=baseParams,proto3,oneof" json:"base_params,omitempty"`
	DialParams              *DialParams            `protobuf:"bytes,2,opt,name=dial_params,json=dialParams,proto3,oneof" json:"dial_params,omitempty"`
	Authenticated           *bool                  `protobuf:"varint,100,opt,name=authenticated,proto3,oneof" json:"authenticated,omitempty"`
	Bytes                   *int64                 `protobuf:"varint,101,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	ClientDownloadTimestamp *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=client_download_timestamp,json=clientDownloadTimestamp,proto3,oneof" json:"client_download_timestamp,omitempty"`
	Duration                *int64                 `protobuf:"varint,103,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Etag                    *string                `protobuf:"bytes,104,opt,name=etag,proto3,oneof" json:"etag,omitempty"`
	Tunneled                *bool                  `protobuf:"varint,105,opt,name=tunneled,proto3,oneof" json:"tunneled,omitempty"`
	Url                     *string                `protobuf:"bytes,106,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RemoteServerList) Reset() {
	*x = RemoteServerList{}
	mi := &file_ca_psiphon_psiphond_remote_server_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteServerList) ProtoMessage() {}

func (x *RemoteServerList) ProtoReflect() protoreflect.Message {
	mi := &file_ca_psiphon_psiphond_remote_server_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteServerList.ProtoReflect.Descriptor instead.
func (*RemoteServerList) Descriptor() ([]byte, []int) {
	return file_ca_psiphon_psiphond_remote_server_list_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteServerList) GetBaseParams() *BaseParams {
	if x != nil {
		return x.BaseParams
	}
	return nil
}

func (x *RemoteServerList) GetDialParams() *DialParams {
	if x != nil {
		return x.DialParams
	}
	return nil
}

func (x *RemoteServerList) GetAuthenticated() bool {
	if x != nil && x.Authenticated != nil {
		return *x.Authenticated
	}
	return false
}

func (x *RemoteServerList) GetBytes() int64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *RemoteServerList) GetClientDownloadTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientDownloadTimestamp
	}
	return nil
}

func (x *RemoteServerList) GetDuration() int64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *RemoteServerList) GetEtag() string {
	if x != nil && x.Etag != nil {
		return *x.Etag
	}
	return ""
}

func (x *RemoteServerList) GetTunneled() bool {
	if x != nil && x.Tunneled != nil {
		return *x.Tunneled
	}
	return false
}

func (x *RemoteServerList) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

var File_ca_psiphon_psiphond_remote_server_list_proto protoreflect.FileDescriptor

const file_ca_psiphon_psiphond_remote_server_list_proto_rawDesc = "" +
	"\n" +
	",ca.psiphon.psiphond/remote_server_list.proto\x12\x13ca.psiphon.psiphond\x1a%ca.psiphon.psiphond/base_params.proto\x1a%ca.psiphon.psiphond/dial_params.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x04\n" +
	"\x10RemoteServerList\x12E\n" +
	"\vbase_params\x18\x01 \x01(\v2\x1f.ca.psiphon.psiphond.BaseParamsH\x00R\n" +
	"baseParams\x88\x01\x01\x12E\n" +
	"\vdial_params\x18\x02 \x01(\v2\x1f.ca.psiphon.psiphond.DialParamsH\x01R\n" +
	"dialParams\x88\x01\x01\x12)\n" +
	"\rauthenticated\x18d \x01(\bH\x02R\rauthenticated\x88\x01\x01\x12\x19\n" +
	"\x05bytes\x18e \x01(\x03H\x03R\x05bytes\x88\x01\x01\x12[\n" +
	"\x19client_download_timestamp\x18f \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x17clientDownloadTimestamp\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18g \x01(\x03H\x05R\bduration\x88\x01\x01\x12\x17\n" +
	"\x04etag\x18h \x01(\tH\x06R\x04etag\x88\x01\x01\x12\x1f\n" +
	"\btunneled\x18i \x01(\bH\aR\btunneled\x88\x01\x01\x12\x15\n" +
	"\x03url\x18j \x01(\tH\bR\x03url\x88\x01\x01B\x0e\n" +
	"\f_base_paramsB\x0e\n" +
	"\f_dial_paramsB\x10\n" +
	"\x0e_authenticatedB\b\n" +
	"\x06_bytesB\x1c\n" +
	"\x1a_client_download_timestampB\v\n" +
	"\t_durationB\a\n" +
	"\x05_etagB\v\n" +
	"\t_tunneledB\x06\n" +
	"\x04_urlBHZFgithub.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pb/psiphondb\x06proto3"

var (
	file_ca_psiphon_psiphond_remote_server_list_proto_rawDescOnce sync.Once
	file_ca_psiphon_psiphond_remote_server_list_proto_rawDescData []byte
)

func file_ca_psiphon_psiphond_remote_server_list_proto_rawDescGZIP() []byte {
	file_ca_psiphon_psiphond_remote_server_list_proto_rawDescOnce.Do(func() {
		file_ca_psiphon_psiphond_remote_server_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_remote_server_list_proto_rawDesc), len(file_ca_psiphon_psiphond_remote_server_list_proto_rawDesc)))
	})
	return file_ca_psiphon_psiphond_remote_server_list_proto_rawDescData
}

var file_ca_psiphon_psiphond_remote_server_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ca_psiphon_psiphond_remote_server_list_proto_goTypes = []any{
	(*RemoteServerList)(nil),      // 0: ca.psiphon.psiphond.RemoteServerList
	(*BaseParams)(nil),            // 1: ca.psiphon.psiphond.BaseParams
	(*DialParams)(nil),            // 2: ca.psiphon.psiphond.DialParams
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ca_psiphon_psiphond_remote_server_list_proto_depIdxs = []int32{
	1, // 0: ca.psiphon.psiphond.RemoteServerList.base_params:type_name -> ca.psiphon.psiphond.BaseParams
	2, // 1: ca.psiphon.psiphond.RemoteServerList.dial_params:type_name -> ca.psiphon.psiphond.DialParams
	3, // 2: ca.psiphon.psiphond.RemoteServerList.client_download_timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ca_psiphon_psiphond_remote_server_list_proto_init() }
func file_ca_psiphon_psiphond_remote_server_list_proto_init() {
	if File_ca_psiphon_psiphond_remote_server_list_proto != nil {
		return
	}
	file_ca_psiphon_psiphond_base_params_proto_init()
	file_ca_psiphon_psiphond_dial_params_proto_init()
	file_ca_psiphon_psiphond_remote_server_list_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_psiphon_psiphond_remote_server_list_proto_rawDesc), len(file_ca_psiphon_psiphond_remote_server_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ca_psiphon_psiphond_remote_server_list_proto_goTypes,
		DependencyIndexes: file_ca_psiphon_psiphond_remote_server_list_proto_depIdxs,
		MessageInfos:      file_ca_psiphon_psiphond_remote_server_list_proto_msgTypes,
	}.Build()
	File_ca_psiphon_psiphond_remote_server_list_proto = out.File
	file_ca_psiphon_psiphond_remote_server_list_proto_goTypes = nil
	file_ca_psiphon_psiphond_remote_server_list_proto_depIdxs = nil
}
