/*
 * Copyright (c) 2026, Psiphon Inc.
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// This file is part of a hard fork of Tailscale's net/portmapper; see the
// package documentation in portmapper.go. Copied from tailscale v1.98.5:
//
//	https://github.com/tailscale/tailscale/blob/v1.98.5/net/portmapper/pcpresultcode_string.go
//
// The original Tailscale code is licensed as follows:
//
//	Copyright (c) Tailscale Inc & contributors
//	SPDX-License-Identifier: BSD-3-Clause

// Code generated by "stringer -type=pcpResultCode -trimprefix=pcpCode"; DO NOT EDIT.

package portmapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pcpCodeOK-0]
	_ = x[pcpCodeNotAuthorized-2]
	_ = x[pcpCodeAddressMismatch-12]
}

const (
	_pcpResultCode_name_0 = "OK"
	_pcpResultCode_name_1 = "NotAuthorized"
	_pcpResultCode_name_2 = "AddressMismatch"
)

func (i pcpResultCode) String() string {
	switch {
	case i == 0:
		return _pcpResultCode_name_0
	case i == 2:
		return _pcpResultCode_name_1
	case i == 12:
		return _pcpResultCode_name_2
	default:
		return "pcpResultCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
