package gquic

//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_frame_source_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go frameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_ack_frame_source_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go ackFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_sealing_manager_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go sealingManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_packer_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go packer"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_aead_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go quicAEAD"
//go:generate sh -c "./mockgen_private.sh quic mock_gquic_aead_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go gQUICAEAD"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/quic/gquic-go multiplexer"
