platform :ios, '10.0'

target 'TunneledWebRequest' do
    pod 'OpenSSL-Universal', '1.0.2.17'
    pod 'PsiphonTunnel', :git => 'https://github.com/Psiphon-Labs/psiphon-tunnel-core-iOS-library.git'
    pod 'OCSPCache', :git => "https://github.com/Psiphon-Labs/OCSPCache.git", :commit => '71e9f5d'
    #pod 'OCSPCache', :path => "../../../../../OCSPCache/"
end

