// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ca.psiphon.router/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Router struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *string                `protobuf:"bytes,1,opt,name=destination,proto3,oneof" json:"destination,omitempty"`
	MessageType   *string                `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3,oneof" json:"message_type,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Router) Reset() {
	*x = Router{}
	mi := &file_ca_psiphon_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Router) ProtoMessage() {}

func (x *Router) ProtoReflect() protoreflect.Message {
	mi := &file_ca_psiphon_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Router.ProtoReflect.Descriptor instead.
func (*Router) Descriptor() ([]byte, []int) {
	return file_ca_psiphon_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *Router) GetDestination() string {
	if x != nil && x.Destination != nil {
		return *x.Destination
	}
	return ""
}

func (x *Router) GetMessageType() string {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return ""
}

func (x *Router) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Router) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Router) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_ca_psiphon_router_router_proto protoreflect.FileDescriptor

const file_ca_psiphon_router_router_proto_rawDesc = "" +
	"\n" +
	"\x1eca.psiphon.router/router.proto\x12\x11ca.psiphon.router\"\xbe\x02\n" +
	"\x06Router\x12%\n" +
	"\vdestination\x18\x01 \x01(\tH\x00R\vdestination\x88\x01\x01\x12&\n" +
	"\fmessage_type\x18\x02 \x01(\tH\x01R\vmessageType\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x03 \x01(\fH\x02R\x03key\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\fH\x03R\x05value\x88\x01\x01\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.ca.psiphon.router.Router.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x0e\n" +
	"\f_destinationB\x0f\n" +
	"\r_message_typeB\x06\n" +
	"\x04_keyB\b\n" +
	"\x06_valueBFZDgithub.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/server/pb/routerb\x06proto3"

var (
	file_ca_psiphon_router_router_proto_rawDescOnce sync.Once
	file_ca_psiphon_router_router_proto_rawDescData []byte
)

func file_ca_psiphon_router_router_proto_rawDescGZIP() []byte {
	file_ca_psiphon_router_router_proto_rawDescOnce.Do(func() {
		file_ca_psiphon_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_psiphon_router_router_proto_rawDesc), len(file_ca_psiphon_router_router_proto_rawDesc)))
	})
	return file_ca_psiphon_router_router_proto_rawDescData
}

var file_ca_psiphon_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ca_psiphon_router_router_proto_goTypes = []any{
	(*Router)(nil), // 0: ca.psiphon.router.Router
	nil,            // 1: ca.psiphon.router.Router.MetadataEntry
}
var file_ca_psiphon_router_router_proto_depIdxs = []int32{
	1, // 0: ca.psiphon.router.Router.metadata:type_name -> ca.psiphon.router.Router.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ca_psiphon_router_router_proto_init() }
func file_ca_psiphon_router_router_proto_init() {
	if File_ca_psiphon_router_router_proto != nil {
		return
	}
	file_ca_psiphon_router_router_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_psiphon_router_router_proto_rawDesc), len(file_ca_psiphon_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ca_psiphon_router_router_proto_goTypes,
		DependencyIndexes: file_ca_psiphon_router_router_proto_depIdxs,
		MessageInfos:      file_ca_psiphon_router_router_proto_msgTypes,
	}.Build()
	File_ca_psiphon_router_router_proto = out.File
	file_ca_psiphon_router_router_proto_goTypes = nil
	file_ca_psiphon_router_router_proto_depIdxs = nil
}
